### ISSUE TITLE
How to change height of CalendarView and calendar days accordingly? 

### ISSUE THREAD

**Issue by jamacco94** [kizitonwose/CalendarView#10]

**Comment by jamacco94** [comment]
For example set height of CalendarView full height of its parent

**Comment by kizitonwose** [comment]
If I get you correctly, you want the CalendarView to match its parent's height and the date cells to also match the CalendarView's height?

**Comment by jamacco94** [comment]
yes sir

**Comment by kizitonwose** [comment]
To achieve this, you need to set the CalendarView's `layout_width` and `layout_height` to `match_parent` then calculate the `dayWidth` and `dayHeight` properties after the CalendarView is laid out:

```kotlin
calendarView.post {
    calendarView.dayWidth = calendarView.width / 7
    calendarView.dayHeight = calendarView.height / 6
}
```
