### ISSUE TITLE
Cannnot set padding between calendar months

### ISSUE THREAD

**Issue by bernardcosta** [kizitonwose/CalendarView#101]
From the sample App provided with the library I noticed that all calendars do not have a margin. I.e. every calendar goes from one of the screen to the other. When I try to put a margin (or padding) on the calendar, the previous and next month start to show up at the edges. It seems like I cannot set a padding between the months of the calendar. I am using page scrolling. How can I achieve this effect?

**Comment by bernardcosta** [comment]
Managed to solve this programmatically by using calendar.monthPaddingStart and calendar.monthPaddingEnd. Another problem, however, occurs where the first element (month) is not centered in the view it is offset to the right. why is that?

**Comment by kizitonwose** [comment]
Can I see a screenshot of this offset? 
Also, it'll be better to close this issue and open a new one with the offset problem.
