### ISSUE TITLE
dayView image clipchildren="false" not working

### ISSUE THREAD

**Issue by bernardcosta** [kizitonwose/CalendarView#103]
I added an image view as a background in each day cell. the background can be bigger than a single cell since I am setting its dimensions programmatically. I also do not want it to get cut by each day cell so I am setting `clipToPadding="false"` and` clipChildren="false"` to each parent and sub parent layout. This is not working. I think its because the day view layout is not directly included in the calendar layout but is referenced by passing it through `cv_dayViewResource`. Is this correct? is there a way I can still manage to let each day background overflow into its neighbors?

**Comment by kizitonwose** [comment]
Go to [DayHolder.kt - Line 40](https://github.com/kizitonwose/CalendarView/blob/31694c512e0c25fbb62ce40e0f080a41371bc2bb/library/src/main/java/com/kizitonwose/calendarview/ui/DayHolder.kt#L40), add `clipChildren = false` before the `addView(dateView)` and see if that fixes your issue. If it does, let me know and I'll do that in the library and publish a new version or open a PR, whichever is more convenient for you. 

The result should be this:

```kotlin
layoutParams = LinearLayout.LayoutParams(config.width, config.height, 1F)
clipChildren = false
addView(dateView)
```

**Comment by szeidner** [comment]
Has this been added to the library yet? I'm having the same challenge here.

**Comment by kizitonwose** [comment]
> Has this been added to the library yet? I'm having the same challenge here.

Yep, this is fixed. Please ensure that you are on the latest version.

**Comment by szeidner** [comment]
I didn't see it in included in version 0.4.0 which I think is the latest? I ended up creating a custom month view that I used to set `clipChildren` to false for each row:

```
class CustomMonthView(context: Context) : FrameLayout(context) {
    override fun onAttachedToWindow() {
        clipChildren = false
        (getChildAt(0) as? LinearLayout)?.clipChildren = false

        val calendarRows = ((getChildAt(0) as? LinearLayout)?.getChildAt(1) as LinearLayout)
        for (i in 0 until calendarRows.childCount) {
            val row = calendarRows.getChildAt(i) as? LinearLayout
            row?.clipChildren = false
        }
        super.onAttachedToWindow()
    }
}
```

and referred to it in my XML:
`app:cv_monthViewClass="path.to.CustomMonthView"`

**Comment by kizitonwose** [comment]
Sorry for the confusion. The fix makes it unnecessary to set the `clipChildren` property. The library set this to true in the past but this has since been removed long before `0.4.0`. I think you have a different use case. Glad you figured something out.

**Comment by szeidner** [comment]
Ah I see - thanks for the explanation and response!
