### ISSUE TITLE
Can I get dates from the CalendarView(week Mode and continuous scroll)?(scroll and get center date)

### ISSUE THREAD

**Issue by lugia2491** [kizitonwose/CalendarView#104]
I want get 7dates from the CalendarView(week Mode and continuous scroll)
Currently I use setMonthScrollListener to get 7dates.
But it seems to trigger only once a week.
Can I get dates in every time scroll?

Sorry, my bad English.

**Comment by kizitonwose** [comment]
The `CalendarDay` class just maps a `LocalDate` to a `DayOwner`. You can create a `LocalDate` instance as needed. If you can further explain what you're trying to do, maybe I can be of more help.

**Comment by lugia2491** [comment]
I want like this features.
![demo](https://user-images.githubusercontent.com/48899951/71188999-066a1400-22bd-11ea-9d95-ae6e0091e5d3.gif)
Always auto select the center date.
I want auto select center date of 7days(week mode).

Thank you.

**Comment by lugia2491** [comment]
I think i solved!

We can use addOnScrollListener onScrollStateChanged
If scroll stop, We can use CalendarView.findFirstVisibleDay() to smoothScrollToDate.

Like this:
CalendarView.smoothScrollToDay(CalendarView.findFirstVisibleDay());

And center day is:
CalendarView.findFirstVisibleDay().getDate().plusDays(3);

This is my sample code:

`int LeftRightScroll = 0;
boolean manualScroll = false;
private void selectMiddleItem(){
	CalendarViewBloodPressures.addOnScrollListener(new RecyclerView.OnScrollListener() {
		@Override
		public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
			super.onScrolled(recyclerView, dx, dy);
			LeftRightScroll = dx;
		}

		@Override
		public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
			super.onScrollStateChanged(recyclerView, newState);

			if(newState == 1){
				manualScroll = true;
			}
			if(newState == 0 && manualScroll){
				LocalDate scrollDay;
				manualScroll = false;
				if(LeftRightScroll < 0){//RightScroll

					scrollDay = CalendarViewBloodPressures.findFirstVisibleDay().getDate();
					CalendarViewBloodPressures.smoothScrollToDate(scrollDay);
					tvDate.setText(scrollDay.plusDays(3).toString());
					
				}else if(LeftRightScroll > 0){//LeftScroll

					scrollDay = CalendarViewBloodPressures.findFirstVisibleDay().getDate().plusDays(1);
					CalendarViewBloodPressures.smoothScrollToDate(scrollDay);
					tvDate.setText(scrollDay.plusDays(3).toString());
					
				}
			}
		}
	});
}`

**Comment by kizitonwose** [comment]
Looks like you've figured it out, kudos!
I'll close this now.
