### ISSUE TITLE
How to notify DayBinder for update or rebind like notifyDataSetChanged in RecyclerView?

### ISSUE THREAD

**Issue by urmatt** [kizitonwose/CalendarView#105]
I have data objects with date insight. In Calendar view specific date must be market dynamic. 
For example after click button add Calendar view must be updated.

**Comment by kizitonwose** [comment]
Just call `notifyDateChanged()` or `notifyDayChanged()`

**Comment by kizitonwose** [comment]
These trigger the day binder for the date you pass into the method.
