### ISSUE TITLE
Background for certain dates for a month repeats every six months

### ISSUE THREAD

**Issue by shadygoneinsane** [kizitonwose/CalendarView#106]
### in my `onViewCreated( )` in fragment, after setting up calendar's currentmonth, weekdays, start and end month; I am using `dayBinder` to set background for the dates as below :

```
calendarView.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)

            override fun bind(container: DayViewContainer, day: CalendarDay) {
                    //code to set backgrounds for start, middle and end dates here
            }
}
```

![device-2019-12-24-170923](https://user-images.githubusercontent.com/13831192/71411777-c5814f00-2670-11ea-8056-ba0fe2814b0b.png)

### Everything works fine but the same dates which are highlighted repeats after every 6 months which shouldn't be the case

![device-2019-12-24-170942](https://user-images.githubusercontent.com/13831192/71411784-d03be400-2670-11ea-8a12-af79c2fa8f52.png)
![device-2019-12-24-170953](https://user-images.githubusercontent.com/13831192/71411785-d03be400-2670-11ea-8494-44aca87fc947.png)

### I tried using `notifyCalendarChanged()` after every month change but that didn't help
If you have any suggestions as to what might be causing this issue, can you please point me in the right direction

**Comment by kizitonwose** [comment]
This is due to view reuse, you have to set the view background to `null` for the cells where you don't want the background to show. If you can share your logic for setting the background, maybe I can figure out exactly what needs to change.
