### ISSUE TITLE
How can i set calender view height?

### ISSUE THREAD

**Issue by nicemak** [kizitonwose/CalendarView#107]
Hi, is there any way to set height on calendar so that it can adjust calendar according to given height? because wrap_content take almost 80 percent of screen size on some tablets.

**Comment by kizitonwose** [comment]
All you have to do is set the height/width of the cells using the `dayHeight` and `dayWidth` properties on the `CalendarView` class.

**Comment by nicemak** [comment]
thank you for the reply, can you please tell me the way that calendar take only 50 percent screen size of every device?

**Comment by nicemak** [comment]
i fixed my problem with `app:cv_outDateStyle="none"`, after this it generates only 5 rows which covers 40 50 % screen size.

Thank you :)
