### ISSUE TITLE
Decouple ThreeTenABP from the library

### ISSUE THREAD

**Issue by kaushalyap** [kizitonwose/CalendarView#109]
Currently this library itself include [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP), so you do not have add it as a dependency. But this becomes problematic in multi module projects

ex: 

There is a multi module project with application module called `app` and library modules with `feature_1`, `feature_2`. And CalendarView library is used in `feature_2` module, so we add it as a dependency to `feature_2` module. But you have to initialize `ThreeTenABP` in `app` module. So you have to separately add `ThreeTenABP` to `app` module. Now  `ThreeTenABP` is added our project twice as a dependency. 

1. From the CalendarView library itself.
2. separately added to `app` module. 

So please consider decoupling `ThreeTenABP` from the library itself.

**Comment by kizitonwose** [comment]
It's actually not mandatory to initialize `ThreeTenABP` in your application class, you just have to do so before the CalendarView is used. For example, you can do this in your activity before setting the content view:

```kotlin
class DemoActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AndroidThreeTen.init(this) // Initialize ThreeTenABP
        setContentView(R.layout.demo_activity)
   }

}
```

Note that you do not have to worry about calling this multiple times as ThreeTenABP internally checks if it has been initialized before proceeding.

**Comment by kaushalyap** [comment]
My app uses a `single activity` and `main activity` lives in `app` module, even I initialize `ThreeTenABP` in `main activity` still I have to add `ThreeTenABP` to the `app` module as a dependency.

**Comment by kizitonwose** [comment]
You do not need to initialize it in the main activity. Just initialize it in the activity or fragment where it is being used. In the case of a fragment, do it in the `onCreate()` NOT `onCreateView()`.

**Comment by kaushalyap** [comment]
I tried followings in side a fragment still getting an exception. (`org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered`), which `ThreeTenABP` have not initialized.

```
  override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AndroidThreeTen.init(context)
    }

```
```
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AndroidThreeTen.init(activity?.application)
    }
```

**Comment by kizitonwose** [comment]
This will happen if you have a field that triggers ThreeTenABP usage before `onCreate()` is called in your fragment. For example, if you have a field like this:
```kotlin
private val today = LocalDate.now()
``` 
The app will crash because the `today` property will be initialized first before `onCreate()` is called.

To fix this, you need to lazily initialize such properties:
```kotlin
private val today by lazy { LocalDate.now() }
```

**Comment by kaushalyap** [comment]
thanks it works now!
