### ISSUE TITLE
Require complete minimal project so configuration can be understood

### ISSUE THREAD

**Issue by acutetech** [kizitonwose/CalendarView#11]
I have played with the sample app from Github and want to try to use the library in my own app. However, attempts at creating a minimal app fail. I suspect instructions are missing from the instructions on Github. 

Please provide a complete worked example.

I did this:

1  In Android Studio, File > New > New Project and selected "Empty Activity"
2 Built and ran this successfully.
3 Added the two entries to the two build.gradle files described in readme.MD (version 0.1.2)
4 Sync fails with this:
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.
5 I added the suggestion to AndroidManifest.xml - now get "ERROR: Manifest merger failed with multiple errors, see logs"

I note the sample app mainfest file includes: tools:ignore="GoogleAppIndexingWarning"

But this does not fix the problem.

Some (relevant?) discussion here? https://github.com/material-components/material-components-android/issues/193

**Comment by kizitonwose** [comment]
This error is happening because the library uses the new AndroidX packages and your app does not. 

You need to migrate your project to use AndroidX: `Menu -> Refactor -> Migrate to AndroidX`. 

Alternatively, as suggested in the linked issue, you can add the two lines to your `gradle.properties` file: 

```xml
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by kizitonwose** [comment]
I understand from the [new issue](https://github.com/kizitonwose/CalendarView/issues/19#issuecomment-504406928) that this is resolved, as you have migrated to AndroidX. Will close this now.

I do believe the documentation can be improved in so many ways so less reference has to be made to the sample project and I am working on that.

**Comment by Jack79co** [comment]
i do the same it's worked but app is open for 4 second and crash after that

**Comment by kizitonwose** [comment]
> i do the same it's worked but app is open for 4 second and crash after that

Please open a new issue and explain clearly.
