### ISSUE TITLE
Is it possible to change (or better yet - animate) a particular calendar column width?

### ISSUE THREAD

**Issue by StevenKek** [kizitonwose/CalendarView#111]
Imagine a normal week calendar. We have multiple of those stacked on top of each other vertically.
Now we want to change the width of a specific week day (say, Tuesday for example) in every single one of those.

I know about the 'dayWidth' and 'dayHeight' CalendarView properties. But these are global for every single cell in the entire calendar.

User must be able to click a week day/column and that day will expand in all of the shown calendars.

Even a workaround will suffice, as long as I will be able to change a specific day width in some way and call the notifyCalendarChanged function to redraw the calendar.

I love this library btw! Thank you for sharing it, it really helped us a lot!

Cheers!

EDIT:
Reference image
![image](https://user-images.githubusercontent.com/46678816/71978768-70227180-321c-11ea-8a46-da4048277d75.png)

Come to think of it, maybe I should skip using CalendarView in this case and use a RecyclerView with GridLayout instead.

**Comment by kizitonwose** [comment]
This is a very interesting use case but unfortunately not supported by this library. I think your suggestion of using a RecyclerView with GridLayout would definitely work.

**Comment by StevenKek** [comment]
Thanks for the quick response :)

I believe I found even better solution.
- Use a single calendar (week mode)
- Every day of that calendar will contain recycler view of recycler views to show the events for every person as seen on the screenshot.

Now scrolling would work perfectly, I could reuse a lot of code since I use CalendarView in the same app on multiple places already, continuous scrolling, loading on demand, etc. All this we already do in the same app with the CalendarView.

But I will still need the ability to change day width on a day by day basis :(

How hard would it be to implement this (the variable day width)? I can do it myself, but I would still appreciate any tips you can provide me :)

**Comment by kizitonwose** [comment]
Currently, the `dayWith` is used in the [DayHolder](https://github.com/kizitonwose/CalendarView/blob/11594213e5a45851be3fa7d3f5f8e95a8d37e722/library/src/main/java/com/kizitonwose/calendarview/ui/DayHolder.kt#L40), you can instead provide a callback that will be used to produce this value for each date. Then where you implement this callback, you check the passed in date and return the appropriate value.

**Comment by StevenKek** [comment]
Thanks!
