### ISSUE TITLE
is there any method equivalent for MonthScrollListener for java?

### ISSUE THREAD

**Issue by ivannatividad** [kizitonwose/CalendarView#112]
I have tried to use this library in java environment despite the fact that it was created in kotlin. So far everything works fine until setting up the monthScrollListener which accepts kotlin native code.

**Comment by ivannatividad** [comment]
I have tried to use the this library in java environment despite the fact that it was created in kotlin. So far everything works fine until setting up the monthScrollListener which accepts kotlin native function.

**Comment by ivannatividad** [comment]
I have tried to use this library in java environment despite the fact that it was created in kotlin. So far everything works fine until setting up the monthScrollListener which accepts kotlin native function.

**Comment by kizitonwose** [comment]
See [this](https://github.com/kizitonwose/CalendarView/issues/74#issuecomment-549745063)
