### ISSUE TITLE
MonthScrollListener progress

### ISSUE THREAD

**Issue by DantheCodingGui** [kizitonwose/CalendarView#113]
Is there any way scroll progress could be added to the monthScrollListener callback? 

I want to animate the month text TextView I have in my header based on the scroll progress (paged mode).

**Comment by kizitonwose** [comment]
Why not add a new scroll listener on the CalendarView, just like you would with RecyclerView.

```kotlin
calendarVIew.addOnScrollListener(object : RecyclerView.OnScrollListener() {

    override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {

    }

    override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {

    }
})
```
