### ISSUE TITLE
Continuous horizontal scroll week calendar month header issue

### ISSUE THREAD

**Issue by StevenKek** [kizitonwose/CalendarView#115]
![image](https://user-images.githubusercontent.com/46678816/72450303-69ff3880-37ba-11ea-8235-f53d0083c200.png)

When I scroll through the calendar, sometimes the month header "cells" as squashed (multiple of them into a single day). The number of squashed cells varies. The interval of this bug varies as well.

My CalendarView setup:
XAML
`        <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/unitAttendancePlanCalendarHeader"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/background_white"
            app:cv_dayViewResource="@layout/calendar_week_day"
            app:cv_monthHeaderResource="@layout/calendar_header"
            app:cv_inDateStyle="none"
            app:cv_outDateStyle="none"
            app:cv_maxRowCount="1"
            app:cv_hasBoundaries="true"
            app:cv_orientation="horizontal"
            app:cv_scrollMode="continuous" />`

Month header binder:
`       class MonthViewContainer(view: View) : ViewContainer(view) {
            val legendLayout = view.legendLayout
        }
        calendarView.monthHeaderBinder = object : MonthHeaderFooterBinder<MonthViewContainer> {
            override fun create(view: View) = MonthViewContainer(view)

            override fun bind(container: MonthViewContainer, month: CalendarMonth) {
                // Setup each header day text if we have not done that already.
                if (container.legendLayout.tag == null) {
                    container.legendLayout.tag = month.yearMonth
                    val locale = Locale.getDefault()
                    container.legendLayout.children.map { it as TextView }.forEachIndexed { index, tv ->
                        tv.text = daysOfWeek[index].getDisplayName(TextStyle.SHORT, locale).toUpperCase(locale)
                    }
                    month.yearMonth
                }
            }
        }`

NOTE: Not the entire header (all week days) is visible. Not sure if that's important. Pretty much the idea is to have a calendar that has a fixed dayWidth and doesn't care whether 4, 7 or "10" week days are visible.

EDIT:
Fixed by changing few attributes as follows:
`            app:cv_inDateStyle="firstMonth"
            app:cv_outDateStyle="endOfRow"`

Also dates were not matching localized names until I changed the following attributes as well:
`app:cv_hasBoundaries="false"`

No idea why any of it worked TBH.
I thought setting 'hasBoundaries' to true in combination with settings both in and out date styles to none is reasonable, since there will be no in and out dates. And you don't want any in and out dates when doing a continuous horizontal scroll, right?

**Comment by kizitonwose** [comment]
I think the culprit here is the `maxRowCount` which is 1. Without outDates, some indices can have just 3 cells making the header to not have enough space as an index with the normal 7 cells. 

Glad you got it working anyways.
