### ISSUE TITLE
Performance issues and calendar flashing on 'dayHeight' change

### ISSUE THREAD

**Issue by StevenKek** [kizitonwose/CalendarView#118]
Hi,

We have an infinite continuous horizontal scrolling CalendarView.
When scrolling, I need to dynamically change day height.
The calendar is weekly, so in our case _columns_ = week days and _rows_ = employees.

As the time goes, new employees arrive and some leave. I implemented this in such a way that there is the horizontal calendar view at the root level. Each day then contains vertical recycler view that contains row cells.

This works, but changing the 'dayHeight' to account for variable visible row count hangs the UI thread for ~300ms and blinks with all cells (all cells seemingly disappear for a split second).

This is probably coming from the CalendarView.invalidateViewHolders function. Is it possible to optimize it somehow?

EDIT: I believe the CalendarView.invalidateViewHolders function is doing some unnecessary work when orientation != resized dimension.

Thanks,
Stepan

**Comment by kizitonwose** [comment]
`invalidateViewHolders` really just resets the adapter which forces the UI to be redrawn and restores scroll position etc. I'm not sure how it can lead to the problem you're having. Maybe you can try explaining further.

**Comment by kizitonwose** [comment]
I'll assume this is resolved.
