### ISSUE TITLE
Make CalendarView class open?

### ISSUE THREAD

**Issue by Yoshi3003** [kizitonwose/CalendarView#12]
Hi,

Would you consider making the CalendarView class open to allow developers to extend from it?

A use case would be to override onMeasureLayout to do something further.

Regards.

**Comment by kizitonwose** [comment]
This should come in the next release.

**Comment by Yoshi3003** [comment]
Thank you :)

**Comment by kizitonwose** [comment]
The class is now open in the latest version [0.2.0](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.0)
