### ISSUE TITLE
notifyMonthChanged does not work

### ISSUE THREAD

**Issue by alterpie** [kizitonwose/CalendarView#121]
Property ```months: List<CalendarMonth>``` in ```CalendarAdapter``` contains ```CalendarMonth``` instances which all have ```yearMonth: YearMonth``` property set to ```YearMonth.of(2000, 2)``` equivalent so ```getAdapterPosition(month)``` in method reloadMonth returns -1 for any ```YearMonth``` instance passed to notifyMonthChanged method.
This is calendar setup:
``` kotlin
val today = YearMonth.now()
calendar.setup(
    today.minusYears(20),
    today.plusYears(20),
    DayOfWeek.MONDAY
)
calendar.scrollToDate(LocalDate.now())
```
``` xml
 <com.kizitonwose.calendarview.CalendarView
     android:id="@+id/calendar_weekly"
     android:layout_width="match_parent"
     android:layout_height="wrap_content"
     android:background="?colorSurface"
     app:cv_dayViewResource="@layout/item_calendar_day_weekly"
     app:cv_hasBoundaries="false"
     app:cv_inDateStyle="allMonths"
     app:cv_maxRowCount="1"
     app:cv_orientation="horizontal"
     app:cv_outDateStyle="endOfRow"
     app:cv_scrollMode="paged"
     app:layout_constraintEnd_toEndOf="parent"
     app:layout_constraintStart_toStartOf="parent"
     app:layout_constraintTop_toTopOf="parent" />
```

**Comment by kizitonwose** [comment]
This is because `app:cv_hasBoundaries` is set to `false`. The value for `YearMonth ` becomes somewhat undefined when the calendar has no boundaries. You need to set this to `true`. However, if you must use `false`, then you have to rely on `notifyDateChanged` instead.

**Comment by alterpie** [comment]
Thanks!
