### ISSUE TITLE
Display only one month page when custom dayWidth value is provided

### ISSUE THREAD

**Issue by alterpie** [kizitonwose/CalendarView#122]
CalendarView has an issue when you set custom ```dayWidth``` value.

This is how it looks like after Activity is resumed and no interaction with calendar happened yet (you can see two Mondays displayed):
![image](https://user-images.githubusercontent.com/10796453/73936208-55aee700-48f3-11ea-8c36-42083f60b544.png)

And here how it looks like when I swipe page (you can see previous and next months bits at the edges of screen):
![image](https://user-images.githubusercontent.com/10796453/73936285-8727b280-48f3-11ea-8e0c-f2c52f9480ab.png)

Calendar setup is following:
``` xml
<com.kizitonwose.calendarview.CalendarView
        android:id="@+id/calendar"
        android:layout_width="match_parent"
        android:layout_height="400dp"
        android:background="?colorAccent"
        app:cv_dayViewResource="@layout/item_calendar_day_monthly"
        app:cv_monthHeaderResource="@layout/item_calendar_monthly_header"
        app:cv_orientation="horizontal"
        app:cv_scrollMode="paged"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

These are values supplied as dimensions:
``` xml
<dimen name="calendar_cell_width">52dp</dimen>
<dimen name="calendar_cell_height">56dp</dimen>
```
``` kotlin
calendar.dayWidth = resources.getDimensionPixelSize(R.dimen.calendar_cell_width)
calendar.dayHeight = resources.getDimensionPixelSize(R.dimen.calendar_cell_height)
```
A can assume that the same issue as displayed on the second image exists with custom height of cell and vertical orientation of ```CalendarView```

**Comment by kizitonwose** [comment]
This is because a 56dp width will be different on various devices when converted to px. You're better off just grabbing the screen width and dividing by 7.

**Comment by alterpie** [comment]
Sure, but at least widget should have only one state with provided values for height and width before and after user interaction, don't you think?

**Comment by kizitonwose** [comment]
> Sure, but at least widget should have only one state with provided values for height and width before and after user interaction, don't you think?

Yes, it should. Are you saying that clicks alter the view size? Can you please provide a mini sample where I can reproduce this?

**Comment by kizitonwose** [comment]
I'll assume this is resolved.
