### ISSUE TITLE
How to disable past dates (non Clickable)

### ISSUE THREAD

**Issue by ShahnawazDeveloper** [kizitonwose/CalendarView#124]
How to disable past dates is there any inbuilt method which will do that stuff like in default  Android date picker. 
i.e datePicker.setMinDate(System.currentTimeMillis() - 1000); 
so user will not able to select previous dates.

**Comment by kizitonwose** [comment]
See the included sample application. Basically, you just check the date passed into the DayBinder and disable the view if it is older than the current date.

**Comment by kizitonwose** [comment]
Note: You technically won't disable the view itself, you just style it to look disabled and ignore clicks on it.

**Comment by kizitonwose** [comment]
Again, see the sample code, this is done many times.

**Comment by ShahnawazDeveloper** [comment]
Thanks for the response, I already managed it in that way but i am asking for if there is any method which will provide that functionality so it would be better..

**Comment by kizitonwose** [comment]
I see, that is not available.
