### ISSUE TITLE
Pre-Selected Day

### ISSUE THREAD

**Issue by nicemak** [kizitonwose/CalendarView#125]
Hi,

can you please tell me how to show highlighter on a particular day without clicking the day?

i have a CalendarDay object, which is passed through Activity A to Activity B, and i want to show that day pre-selected, like when we clicked on a day it shows border around that day.

thanks

**Comment by nicemak** [comment]
i solved it with calendar_view.notifyDateChanged(selectedDate!!) :)

**Comment by Spettacolo83** [comment]
Thank you @nicemak !
`selectedDate` should be a CalendarDay type.
What should I put there if I want to select the entire mont?
