### ISSUE TITLE
Unable to set FirstDayOfWeek

### ISSUE THREAD

**Issue by vtison** [kizitonwose/CalendarView#128]
Hi,

I'm trying to set the FirstDayOfWeek for an horizontal calendar in one row (same as the exemple 7).
I want to display only the seven past days so I set everything to display only seven past days and I want to set the first day of the week to the next DayOfWeek than we are today to display only the seven last days. (if we are Wednesday, row must be starting at the past Thursday)

I'm using the following code : 
`exSevenCalendar.setup(currentMonth.minusMonths(1), currentMonth, DayOfWeek.THURSDAY)`

By doing this, whatever the value I put in firstDay (DayOfWeek.MONDAY or whatever), each time the first day of the week is the same as the first day of the first month set. For exemple, in my code above, the first day of the calendar is Saturday (first day of February), so each week begin by a Saturday.

I want something like this (we are 4th of March) :
![20200304_155551](https://user-images.githubusercontent.com/27421836/75891999-e7e1d680-5e30-11ea-9420-7e67389c7e99.png)

and by setting fistDayOfWeek at DayOfWeek.THURSDAY I've got : 
![20200304_155534](https://user-images.githubusercontent.com/27421836/75892091-0b0c8600-5e31-11ea-8b36-086d9a610832.png)

Calendar view settings : 
`<com.kizitonwose.calendarview.CalendarView`
`            android:id="@+id/exSevenCalendar"`
`            android:layout_width="match_parent"`
`            android:layout_height="match_parent"`
`            app:cv_dayViewResource="@layout/example_7_calendar_day"`
`            app:cv_hasBoundaries="false"`
`            app:cv_inDateStyle="none"`
`            app:cv_outDateStyle="none"`
`            app:cv_maxRowCount="1"`
`            app:cv_orientation="horizontal"`
`            app:cv_scrollMode="paged" />`

I don't think there are any other ways to perform that. Maybe methods to limit calendar by week or day and not only by months may also solve this issue ?

Thanks
Victor

**Comment by kizitonwose** [comment]
Looks like you need to enable `inDates` so the calendar is padded accordingly.

`app:cv_inDateStyle="firstMonth"`

**Comment by vtison** [comment]
Oh yes, thanks that's it.

Thanks for your library!
