### ISSUE TITLE
This library is fine if you have to show days of current month only

### ISSUE THREAD

**Issue by devilabhi** [kizitonwose/CalendarView#129]
It gives issues in the case if you have more than 1 month or years that you want to display in calendar and it has many more limitations
1. It do not picks full width of the screen my self. It gives different width in different phones
2. Infinite years cannot be shown on this calendar
3. If there are more than 2-3 months then it shows blank spaces in the calendar. Please check the [screenshot](https://postimg.cc/6ybPJfWL) attached

**Comment by kizitonwose** [comment]
Not sure if this is an issue or feature request or just general complaints about the library. If you need help, kindly create a clear issue and I will be able to help. Closing this.
