### ISSUE TITLE
How to disable scroll?

### ISSUE THREAD

**Issue by jamacco94** [kizitonwose/CalendarView#13]
Is there possible to disable scrolling? and can scroll only programmatically (smoothScrollToMonth() or scrollToMonth())

**Comment by kizitonwose** [comment]
You can intercept touch events on the calendar to achieve this effect.

```kotlin
calendarView.addOnItemTouchListener(object : RecyclerView.SimpleOnItemTouchListener() {
    override fun onInterceptTouchEvent(rv: RecyclerView, e: MotionEvent): Boolean {
        return if (e.action == MotionEvent.ACTION_MOVE) {
            true
        } else {
            super.onInterceptTouchEvent(rv, e)
        }
    }
})
```

**Comment by kizitonwose** [comment]
Maybe in the future, the ability to disable scrolling would be added to the library for easy usage, closing this for now.
