### ISSUE TITLE
how set same height of calendar in all month

### ISSUE THREAD

**Issue by Miteshmakwana73** [kizitonwose/CalendarView#131]
i want to set same height of calendar view in all month 
how do i set view according to column count if month have 5 column that set according to 5 column if 6 than set according to 6 column

`wrap_content ` is taking too much height 
 i am using `app:cv_outDateStyle="endOfRow"` cause i don't want to show extra column space in view

**Comment by kizitonwose** [comment]
Looks like [this workaround](https://github.com/kizitonwose/CalendarView/blob/242bdb60c3233f0883f21698fad141a8d9a7d16f/library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt#L198) should have handled that. You can see it in Example 3.
Does the Example 3 in the sample app have the extra bottom space in 5-row months on your device?

**Comment by Miteshmakwana73** [comment]
@kizitonwose thank you for replay

it's not showing extra space in  Example 3 but it's adding a new column and changing calendar height and i don't want to change height of calendar view  instead of that i want to make calendar day text size smaller and reduce padding and margin according to previous month calendar height

so the height stay same in all month only day text size and margin padding only change according to requirement

**Comment by kizitonwose** [comment]
That's quite tricky. But since you are already showing out dates by using `app:cv_outDateStyle="endOfRow"`, why not just use `app:cv_outDateStyle="endOfGrid"` instead so you have a nice 6 * 7 grid on all months.

**Comment by Miteshmakwana73** [comment]
`endOfGrid ` is not use full for my requirement cause it's show same height but with extra space in some month at bottom

**Comment by kizitonwose** [comment]
The calendar should not have any extra space if you use `endOfGrid`, can you share a screenshot where that happens? It would be a bug if that is the case.

**Comment by Miteshmakwana73** [comment]
![device-2020-03-27-111943](https://user-images.githubusercontent.com/38969602/77726025-fb8df080-701c-11ea-803f-203fa7118340.png)

**Comment by kizitonwose** [comment]
Oh, I get it now, you aren't even showing the outDates. In that case, what you need is `app:cv_outDateStyle="none"` so they are not generated at all.
