### ISSUE TITLE
Espresso UI test failed with ZoneRulesException

### ISSUE THREAD

**Issue by ChathurangaShanFMF** [kizitonwose/CalendarView#132]
I only added the basic calendar to a fragment. When that fragment starts from Espresso It crashes with the following error.

`Caused by: org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered`

This issue is caused by the `threetenabp` library which needed for this library to operate. As recommended in other places I added the following test implementation to both `threetenabp` initializing module and the module I'm actually using this calendar library.

```
testImplementation('org.threeten:threetenbp:1.3.2') {
        exclude group: 'com.jakewharton.threetenabp', module: 'threetenabp'
    }
```
But I end up with the same result. Is there anything else I should do to get this UI test run successfully. This fragment is working fine when the application is installed. Only having this problem with UI testing.

**Comment by kizitonwose** [comment]
Is the Espresso test not running on a device? In which case calling `AndroidThreeTen.init(this)` in the application `onCreate` method should work as usual?

The `testImplementation` fix is for local JVM tests that don't require a device.

**Comment by ChathurangaShanFMF** [comment]
I figured it out doing the following in my test class made my test run without an issue.

```
@Rule
@JvmField
var myActivity: ActivityTestRule<MyActivity> = ActivityTestRule<MyActivity>(MyActivity::class.java)

@Before
fun setUp() {
    AndroidThreeTen.init(myActivity.activity.application)
}
```
