### ISSUE TITLE
Horizontal Calendar And ViewPager 2

### ISSUE THREAD

**Issue by TyFancaoHuynh** [kizitonwose/CalendarView#133]
Hi @kizitonwose ,
I use horizontal calendar (at item fragment) with view pager 2.
So I have some problem with scroll page. 
It access parent scroll (viewpager) and can't scroll the calendar.
If you know this case. Please give me the solution to fix this.
Many Thanks!

**Comment by kizitonwose** [comment]
I think having a horizontally scrolling view in a horizontal view pager is not a good idea, an option would be to use a vertical calendar.

**Comment by TyFancaoHuynh** [comment]
Thank for your support 👍
