### ISSUE TITLE
Multiple problems on calendar

### ISSUE THREAD

**Issue by marianpavel** [kizitonwose/CalendarView#135]
Hi,

I have created a horizontal calendar with a scroll for 3 months.
I have another recyclerView under the calendar with dates and appointments.
Every time I scroll through the recyclerView I mark in a selectedDate variable the first visible item or firstCompleteVisibleItem. After that I notifyDateChanged on oldDate and the newDate

This works great, my bindings are updating, the only thing that I want is when I scroll through a date that is not visible on the screen, the calendar should smooth scroll to that date, or at last try to be in the center of the screen always with that date.

In the binding method I added the following:

```
                if (horizontalCalendarView.findLastVisibleDay() != null) {
                    if (dateText.isChecked && horizontalCalendarView.findLastVisibleDay()!!.date.isBefore(day.date)) {
                        horizontalCalendarView.smoothScrollToDate(day.date.minusDays(2))
                    }
                }
                else if (horizontalCalendarView.findFirstVisibleDay() != null) {
                    if (dateText.isChecked && horizontalCalendarView.findFirstVisibleDay()!!.date.isAfter(day.date)) {
                        horizontalCalendarView.smoothScrollToDate(day.date.plusDays(2))
                    }
                }
```
One problem is that findFirstVisibleDay or findLastVisibleDay something return null ... also, there is a glitch where the calendar infinite scroll to the end then scrolls to the right date or when simply doesn't work. Any idea why this would happen?

Thanks in advance

Also, some other code that I found relevant for this problem:

```
        val dm = DisplayMetrics()
        val wm = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
        wm.defaultDisplay.getMetrics(dm)

        view.horizontalCalendarView.dayWidth = dm.widthPixels / 7

        view.horizontalCalendarView.dayHeight = (view.horizontalCalendarView.dayWidth * 1.5).toInt()
```

or

```
        view.horizontalCalendarView.setup(currentMonth, currentMonth.plusMonths(3), DayOfWeek.values().random())
        view.horizontalCalendarView.scrollToDate(LocalDate.now())
```

```
    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/horizontalCalendarView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="8dp"
        android:layout_marginTop="16dp"
        android:layout_marginEnd="8dp"
        app:layout_constraintTop_toBottomOf="@id/month"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:cv_dayViewResource="@layout/calendar_book_day"
        app:cv_hasBoundaries="false"
        app:cv_inDateStyle="none"
        app:cv_outDateStyle="none"
        app:cv_maxRowCount="1"
        app:cv_orientation="horizontal"
        app:cv_scrollMode="continuous" />
```

**Comment by kizitonwose** [comment]
I see that this is similar to example 7 in the sample project, can I reproduce this issue using Example 7?

**Comment by marianpavel** [comment]
Example 7 doesn't have a secondary list. You can try to create a new recycler view with Dates for example and when you scroll through them to do what I said. It should reproduce

**Comment by kizitonwose** [comment]
It would be great if you can add the recycler view and share the project here. This way, you can clarify whatever problems you are facing.

**Comment by kizitonwose** [comment]
I'll assume this is resolved.
