### ISSUE TITLE
Adjust height for all days in a week if the height of a day ViewContainer is increased

### ISSUE THREAD

**Issue by spalmerin21** [kizitonwose/CalendarView#136]
In my project, I need to add optional views in the day view without increasing the height for every cell. Currently the library does this but the rest of the days of the week leave space below them. Is there a workaround to increase the height of the days in a particular week?

![Screen Shot 2020-03-25 at 11 24 39 AM](https://user-images.githubusercontent.com/2529790/77567963-80e29b00-6e8d-11ea-85bf-39b01677facc.png)

Thank you for creating this great library!

**Comment by kizitonwose** [comment]
How are you adding/removing the extra view? Is this a view in the cell that is just shown and hidden as needed?

**Comment by stevePalmerin** [comment]
Correct. I'm setting the view from View.GONE to View.VISIBLE.

**Comment by kizitonwose** [comment]
In that case, this would be happening because the check view is at the bottom and other views are above it. How about you make the white background the main view, let's say maybe a FrameLayout, then you add the check view inside it with a bottom gravity. This way, the white background is responsible for the cell height and not the check view which will still be correctly positioned at the bottom and there won't be an extra space when the check view is set to `GONE`

**Comment by spalmerin21** [comment]
If you use a bottom gravity, then the cell height will not increase. For example, I would like all view heights to be 100dp, but when one view increases to 112dp, I would like to only notify the views in that week to increase the height to 112dp. 

`
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/bpWhite"
    android:elevation="3dp"
    android:foreground="?android:attr/selectableItemBackground"
    tools:layout_width="60dp">

    <LinearLayout
        android:id="@+id/calendarDayBackground"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="1dp"
            android:layout_marginTop="@dimen/padding_half"
            android:layout_marginBottom="@dimen/padding_quarter"
            android:orientation="vertical">

            <TextView
                android:id="@+id/calendarDayText"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:gravity="center_horizontal"
                android:padding="@dimen/padding_half"
                android:textColor="@color/usuallydarknavy"
                android:textSize="18sp"
                tools:text="22" />


        </LinearLayout>


        <View
            android:id="@+id/reservedSpace"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:elevation="3dp" />


        <FrameLayout
            android:id="@+id/calendar_applied_event"
            android:layout_width="match_parent"
            android:layout_height="12dp"
            android:layout_gravity="bottom"
            android:background="@color/bpBlue"
            android:visibility="gone"
            tools:visibility="visible">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:src="@drawable/ic_check_white" />
        </FrameLayout>

    </LinearLayout>
</FrameLayout>`

**Comment by kizitonwose** [comment]
I think I am a bit lost. How are you able to get all the cells in the selected week in the screenshot you shared to have a different height than other weeks? The empty bottom spacing aside, how are you changing the height? 

I think just setting the checkmark view to VISIBLE/GONE would not be sufficient as the container's height is actually fixed. Could you clarify this?

**Comment by spalmerin21** [comment]
I'm using a linearlayout that wraps the height. When the `calendar_applied_event` is set to visible, the height will change. I'm also not specifying "dayHeight".  By doing this, the container's height seems to be dynamic.

**Comment by kizitonwose** [comment]
Interestingly, I am not able to get that to happen in the examples, looks like I'm missing something but not exactly sure what. Anyway, I am just trying to illustrate that you can notify all days on a row by setting a flag, then you can reload all views in that row and adjust them accordingly.

Let's say you want this to happen after you click a view. Normally, you would keep a reference to the selected view, then the next step would be finding all the days in that week, keep a reference to it and then reload them and in the binding, check if you're binding a view in the reference and update accordingly. Something like this:

```kotlin
val selectedDate = LocalDate.now()
val weekFields = WeekFields.of(Locale.getDefault()) // OR WeekFields.of(DayOfWeek.MONDAY, 1)
val selectedWeekRow: Int = selectedDate.get(weekFields.weekOfMonth())
val month = YearMonth.of(selectedDate.year, selectedDate.month)
val datesToWeek = (1..selectedDate.yearMonth.lengthOfMonth()).map { month.atDay(it) }.filter {
    it.get(weekFields.weekOfMonth()) == selectedWeekRow
}
datesToWeek.forEach { calendarView.notifyDateChanged(it) }


exFiveCalendar.dayBinder = object : DayBinder<DayViewContainer> {
    override fun create(view: View) = DayViewContainer(view)
    override fun bind(container: DayViewContainer, day: CalendarDay) {
        if (day.date in datesToWeek) {
            if (day.date == selectedDate) {
                // Show blue checkmark view
            } else {
                // Make blue checkmark view INVISIBLE so its space is still available.
            }
        } else {
            // Make blue checkmark view GONE so its space is no longer available.
        }
    }
}
```

This is rough but it gives an idea of what needs to be done. Of course, you also need to reload all the previously expanded days so you can reset them accordingly in the binder, or if you want to go extreme, just reload the current month.

**Comment by spalmerin21** [comment]
Perfect! That solved the issue. Thank you very much for you help.

I don't think I'm doing anything else special to make the height adjustable. Just not setting the height and making the layout height wrap the content did it for me. Either I really appreciate you taking the time to help solve this.

**Comment by kizitonwose** [comment]
So, I figured it out, the view height really does change if you set the day view width but have the CalendarView height/width as `match_parent`. 

I finished up my illustrations and you can see it in the gif.

<img src="https://user-images.githubusercontent.com/15170090/77730781-c6c07000-7001-11ea-8d2f-3dee899e96c4.gif" alt="Week and month modes" width="250">

Here's the full code:

```kotlin
private var selectedDate: LocalDate? = null
private val datesInSelectedWeek = mutableListOf<LocalDate>()

class DayViewContainer(view: View) : ViewContainer(view) {
    lateinit var day: CalendarDay
    val textView = view.calendarDayText
    val checkView = view.calendar_applied_event

    init {
        view.setOnClickListener {
            if (day.owner == DayOwner.THIS_MONTH && selectedDate != day.date) {
                val previousWeekDates = datesInSelectedWeek.toList() // Copy
                updateSelectedWeek(day.date)
                val currentWeekDates = datesInSelectedWeek.toList() // Copy, not really needed here
                previousWeekDates.forEach { calendarView.notifyDateChanged(it) }
                currentWeekDates.forEach { calendarView.notifyDateChanged(it) }
            }
        }
    }
}

calendarView.dayBinder = object : DayBinder<DayViewContainer> {
    override fun create(view: View) = DayViewContainer(view)
    override fun bind(container: DayViewContainer, day: CalendarDay) {
        container.day = day
        container.textView.text = day.date.dayOfMonth.toString()

        if (day.owner == DayOwner.THIS_MONTH) {
            container.textView.setTextColorRes(R.color.example_5_text_grey)
            if (day.date in  datesInSelectedWeek) {
                if (selectedDate == day.date) {
                    container.checkView.visibility = View.VISIBLE
                } else {
                    container.checkView.visibility = View.INVISIBLE
                }
            } else {
                container.checkView.visibility = View.GONE
            }
        } else {
            container.checkView.visibility = View.GONE
            container.textView.setTextColorRes(R.color.example_5_text_grey_light)
        }
    }
}

fun updateSelectedWeek(selectedDate: LocalDate) {
    val weekFields = WeekFields.of(Locale.getDefault()) // OR WeekFields.of(DayOfWeek.MONDAY, 1)
    val selectedWeekRow: Int = selectedDate.get(weekFields.weekOfMonth())
    val month = YearMonth.of(selectedDate.year, selectedDate.month)
    datesInSelectedWeek.clear()
    datesInSelectedWeek.addAll((1..month.lengthOfMonth()).map { month.atDay(it) }.filter {
        it.get(weekFields.weekOfMonth()) == selectedWeekRow
    })
    this.selectedDate = selectedDate
}
```

Note that if you have in/outDates, then you have to check for that and add them to the `datesInSelectedWeek` values and then bind accordingly. This is useful for the first and last week rows on the calendar. Calculating this is a bit tricky so I will be adding a feature in the library over the weekend to get the `CalendarMonth` for a date. The `CalendarMonth` holds all days in each month as `val weekDays: List<List<CalendarDay>>` so this saves you two things: 

- You will no longer need all of the logic in `updateSelectedWeek` method as you can just get all the dates in the row using `weekDays.first { it.any { it == selectedDate } }` from the `CalendarMonth` class.

- No extra logic for getting the in/out dates in a row as this is included in the `weekDays` property of the `CalendarMonth` class.
