### ISSUE TITLE
[Example 5][Horizontal Calendar][Disable Scroll By Action Move Calendar View]

### ISSUE THREAD

**Issue by TyFancaoHuynh** [kizitonwose/CalendarView#140]
Hello @kizitonwose 
At first let me say thank for your good calendar library.
I use example 5 of your samples calendar. And i want to disable horizontal scroll by touch listener (action move of calendar view) and just click to [next] or [previous] button to scroll to month.
Could you help me and give me a solution for this case.
Many thanks!

**Comment by kizitonwose** [comment]
Some discussions on how you can achieve this can be found in #38

**Comment by TyFancaoHuynh** [comment]
@kizitonwose Its work. 
Thank for your support.
Please close this issue.
Many Thanks!
