### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by hulisani-mudimeli** [kizitonwose/CalendarView#148]
Can someone tell me how I can implement this in a java project?

**Comment by kizitonwose** [comment]
Do you need help with something specific? Otherwise, I don't know how to answer this question.

**Comment by StevenKek** [comment]
> Do you need help with something specific? Otherwise, I don't know how to answer this question.

I thin he's asking whether or not it is possible to user this library in a java project.
Which I think it is.

**Comment by kizitonwose** [comment]
> I believe he's asking whether or not it is possible to use this library in a java project.
> Which I think it is.

Yep, it definitely is. The only problem is in implementing the month scroll listener which is not an interface but there's a fix [here](https://github.com/kizitonwose/CalendarView/issues/74#issuecomment-549745063)

**Comment by hulisani-mudimeli** [comment]
How do I implemet the calendar.setMonthScrollListener() in java. Im stuck on this

**Comment by kizitonwose** [comment]
@hulisani-mudimeli I have replied you [here](https://github.com/kizitonwose/CalendarView/issues/74#issuecomment-617017167).

**Comment by kizitonwose** [comment]
Guess I can close this now.
