### ISSUE TITLE
First Day Of Week not working

### ISSUE THREAD

**Issue by nmajstorovic** [kizitonwose/CalendarView#15]
Hi,

firstDayOfWeek paramater doesn't work. I try few things:
cvCalendarView.setup(currentMonth, lastMonth, DayOfWeek.MONDAY);
cvCalendarView.setup(currentMonth, lastMonth, DayOfWeek.of(1));

DayOfWeek firstDayOfWeek = WeekFields.of(DayOfWeek.MONDAY, 7).getFirstDayOfWeek();
cvCalendarView.setup(currentMonth, lastMonth, firstDayOfWeek);

Thank you for this great library! :)

**Comment by kizitonwose** [comment]
Hello, could you explain what you mean by "it does not work"? Are the days in a month not generated?

**Comment by nmajstorovic** [comment]
Sorry, my mistake. Close this and thanks again for great library.
