### ISSUE TITLE
Min Date

### ISSUE THREAD

**Issue by bommuraj27** [kizitonwose/CalendarView#151]
I can't set min date how to set minimum date in this calendar view

**Comment by kizitonwose** [comment]
Setting a minimum date is not currently supported. You can only set min/max month.

**Comment by bommuraj27** [comment]
I need  to set minimum because of my client is need to set minimum date support

**Comment by kizitonwose** [comment]
This is not possible. The alternative would be to make them look disabled/unclickable

**Comment by bommuraj27** [comment]
How  to disable and unclickable which method use to achieve it

**Comment by bommuraj27** [comment]
Please share the code for disable and unclickable dates

**Comment by kizitonwose** [comment]
See the included sample application. Basically, you just check the date passed into the `DayBinder` and disable the view if it is older than the desired date. You can use the same logic in Example 4 which I used to make dates in the past non-selectable.
