### ISSUE TITLE
Duplicate class error

### ISSUE THREAD

**Issue by acutetech** [kizitonwose/CalendarView#16]
I am looking for help resolving a duplicate class error.

Having got the library working in a trivial app I tried to add it to a larger project. I get this error:

Duplicate class androidx.concurrent.futures.DirectExecutor found in modules 
concurrent-futures-1.0.0-beta01.jar (androidx.concurrent:concurrent-futures:1.0.0-beta01) and 
futures-1.0.0-alpha01.jar (androidx.concurrent:futures:1.0.0-alpha01)

I am a newbie here, but looks like CalendarView uses the -beta01 library and the -alpha01 library is used by WorkManager:
https://developer.android.com/jetpack/androidx/releases/work

I had been using 'android.arch.work:work-runtime:1.0.0-alpha09' and it looks like if I change to  'android.arch.work:work-runtime:1.0.1' the duplicate class problem goes away, but the API seems significantly different and I would have to make big changes. Can I stay with 1.0.0-alpha09?

I see this: https://medium.com/mindorks/avoiding-conflicts-in-android-gradle-dependencies-28e4200ca235

but it is a bit over my head. Suggestions for working around this?

**Comment by acutetech** [comment]
I have dealt with this issue by updating my WorkManager code, so no longer need help with this issue. I suppose it does flag the issue that adding the library may require changes to other code...

**Comment by kizitonwose** [comment]
This is strange. The `androidx.concurrent:concurrent-futures` is not used directly in this library. I'll check to see if I can figure out what's going on. I'm glad you have resolved the issue though.

**Comment by kizitonwose** [comment]
I can't seem to figure out why there's a clash from an unused library. My best guess is that this is coming from appcompat which was declared in the library but not used, this has been removed in the latest release [0.2.0](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.0)

Hopefully, this was the problem. Will be closing this issue as it is no longer a problem for you.
