### ISSUE TITLE
translating to java

### ISSUE THREAD

**Issue by Bikjeun** [kizitonwose/CalendarView#160]
hi i need some help

1) dotView.isVisible = events[day.date].orEmpty().isNotEmpty()
what is this line in java, sorry im still cant really understand kotlin language

2)class Example3EventsAdapter(val onClick: (Event) -> Unit) :
    RecyclerView.Adapter<Example3EventsAdapter.Example3EventsViewHolder>() {

    val events = mutableListOf<Event>()

3) inner class Example3EventsViewHolder(override val containerView: View) :
        RecyclerView.ViewHolder(containerView), LayoutContainer {

        init {
            itemView.setOnClickListener {
                onClick(events[adapterPosition])
            }
        }

        fun bind(event: Event) {
            itemEventText.text = event.text
        }
    }

**Comment by Bikjeun** [comment]
exThreeCalendar.monthScrollListener = {
            requireActivity().homeToolbar.title = if (it.year == today.year) {
                titleSameYearFormatter.format(it.yearMonth)
            } else {
                titleFormatter.format(it.yearMonth)
            }

            // Select the first day of the month when
            // we scroll to a new month.
            selectDate(it.yearMonth.atDay(1))
        }
if possible this too

**Comment by kizitonwose** [comment]
> dotView.isVisible = events[day.date].orEmpty().isNotEmpty()
what is this line in java, sorry im still cant really understand kotlin language

```Java
List<Event> e = events.get(day.getDate());
dotView.setVisibility(e == null || e.isEmpty() ? View.GONE : View.VISIBLE);
```
---
> val events = mutableListOf<Event>()

```Java
List<Event> events = new ArrayList<>();
```
---
> init {
> }

This block of code is called after the constructor in Kotlin so in Java, you can just have this piece of code within the constructor itself.

---

> exThreeCalendar.monthScrollListener

To set the MonthScrollListener in a Java project see [this](https://github.com/kizitonwose/CalendarView/issues/74).

**Comment by Bikjeun** [comment]
private val eventsAdapter = Example3EventsAdapter {
        AlertDialog.Builder(requireContext())
            .setMessage(R.string.example_3_dialog_delete_confirmation)
            .setPositiveButton(R.string.delete) { _, _ ->
                deleteEvent(it)
            }
            .setNegativeButton(R.string.close, null)
            .show()
    }

    private val inputDialog by lazy {
        val editText = AppCompatEditText(requireContext())
        val layout = FrameLayout(requireContext()).apply {
            // Setting the padding on the EditText only pads the input area
            // not the entire EditText so we wrap it in a FrameLayout.
            val padding = dpToPx(20, requireContext())
            setPadding(padding, padding, padding, padding)
            addView(editText, FrameLayout.LayoutParams(MATCH_PARENT, WRAP_CONTENT))
        }
        AlertDialog.Builder(requireContext())
            .setTitle(getString(R.string.example_3_input_dialog_title))
            .setView(layout)
            .setPositiveButton(R.string.save) { _, _ ->
                saveEvent(editText.text.toString())
                // Prepare EditText for reuse.
                editText.setText("")
            }
            .setNegativeButton(R.string.close, null)
            .create()
            .apply {
                setOnShowListener {
                    // Show the keyboard
                    editText.requestFocus()
                    context.inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0)
                }
                setOnDismissListener {
                    // Hide the keyboard
                    context.inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0)
                }
            }
    }

this too please... i am so sorry for the trouble

**Comment by Bikjeun** [comment]
1) private val eventsAdapter = Example3EventsAdapter {
        AlertDialog.Builder(requireContext()).......

2)   private val inputDialog by lazy {
        val editText = AppCompatEditText(requireContext())
        val layout = FrameLayout(requireContext()).apply {


these too please.. so sorry for the trouble

**Comment by kizitonwose** [comment]
> private val eventsAdapter = Example3EventsAdapter {}

```Java
private Example3EventsAdapter adapter = new Example3EventsAdapter();
```
---
> private val inputDialog by lazy { }

The lazy keyword does not exist in Java but you can just delegate the task to a method and then call it where needed.

**Comment by Bikjeun** [comment]
exThreeCalendar.monthScrollListener = {
            requireActivity().homeToolbar.title = if (it.year == today.year) {
                titleSameYearFormatter.format(it.yearMonth)
            } else {
                titleFormatter.format(it.yearMonth)
            }

            // Select the first day of the month when
            // we scroll to a new month.
            selectDate(it.yearMonth.atDay(1))
        }

how do i translate this to java?

**Comment by Bikjeun** [comment]
> > private val eventsAdapter = Example3EventsAdapter {}
> 
> ```java
> private Example3EventsAdapter adapter = new Example3EventsAdapter();

^ for your kotlin file you included a anonymous method in this initial initialisation... so in java how do i do the same?

**Comment by kizitonwose** [comment]
> exThreeCalendar.monthScrollListener = {
> requireActivity().homeToolbar.title = if (it.year == today.year) {
> titleSameYearFormatter.format(it.yearMonth)
> } else {
> titleFormatter.format(it.yearMonth)
> }
> 
> ```
>         // Select the first day of the month when
>         // we scroll to a new month.
>         selectDate(it.yearMonth.atDay(1))
>     }
> ```
> 
> how do i translate this to java?

To set the MonthScrollListener in a Java project see [this](https://github.com/kizitonwose/CalendarView/issues/74).

**Comment by kizitonwose** [comment]
> > > private val eventsAdapter = Example3EventsAdapter {}
> > 
> > 
> > ```java
> > private Example3EventsAdapter adapter = new Example3EventsAdapter();
> > ```
> 
> ^ for your kotlin file you included a anonymous method in this initial initialisation... so in java how do i do the same?

The same way you create anonymous classes in Java. Nothing special with this one.

**Comment by kizitonwose** [comment]
Guess I can close this.

**Comment by Bikjeun** [comment]
> > > > private val eventsAdapter = Example3EventsAdapter {}
> > > 
> > > 
> > > ```java
> > > private Example3EventsAdapter adapter = new Example3EventsAdapter();
> > > ```
> > 
> > 
> > ^ for your kotlin file you included a anonymous method in this initial initialisation... so in java how do i do the same?
> 
> The same way you create anonymous classes in Java. Nothing special with this one.

hi im sorry but how did you do it as your adapter class when converted to java will take in constructors but how do you create this anonymous class

**Comment by kizitonwose** [comment]
Not everything in Kotlin is directly convertible to Java and vice versa. I don't fully understand what you want to achieve but just do it in any way that makes sense in Java. Direct Kotlin -> Java conversion usually isn't what you want.
