### ISSUE TITLE
Error on Null Object reference

### ISSUE THREAD

**Issue by Bikjeun** [kizitonwose/CalendarView#164]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kizitonwose.calendarview.CalendarView.setup(org.threeten.bp.YearMonth, org.threeten.bp.YearMonth, org.threeten.bp.DayOfWeek)' on a null object reference

hi i am getting this error but i do not know how to fix it.. i have initialised it but it still states null during the setup...

``public class CalenderFragment extends Fragment {

    private LocalDate selectedDate;
    private LocalDate today = LocalDate.now();

    private DateTimeFormatter titleSameYearFormatter = DateTimeFormatter.ofPattern("MMMM");
    private DateTimeFormatter titleFormatter = DateTimeFormatter.ofPattern("MMM yyyy");
    private DateTimeFormatter selectionFormatter = DateTimeFormatter.ofPattern("d MMM yyyy");

    private HashMap<LocalDate, ArrayList<CalenderEventModel>> events = new HashMap<>();
    private CalenderAdapter calenderAdapter;
    CalendarView calendarView;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_calender, container, false);
        calendarView = view.findViewById(R.id.Calendar);

        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.CalenderRv);
        calenderAdapter = new CalenderAdapter(getContext(), events);
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext(), RecyclerView.VERTICAL, false));
        recyclerView.addItemDecoration(new DividerItemDecoration(getContext(), RecyclerView.VERTICAL));
        recyclerView.setAdapter(calenderAdapter);

        return view;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LocalDate localDate = LocalDate.now();

        YearMonth currentMonth = YearMonth.now();
        calendarView.setup(currentMonth.minusMonths(10), currentMonth.plusMonths(10), localDate.with(ChronoField.DAY_OF_WEEK, 1).getDayOfWeek()); //calendarView is null here
        calendarView.scrollToMonth(currentMonth);

        if (savedInstanceState == null) {
            selectDate(today);
        }

**Comment by kizitonwose** [comment]
This is happening because the field `CalendarView calendarView;` is not initialized. 

Judging by this line: `calendarView = view.findViewById(R.id.Calendar);` I would guess that `R.id.Calendar` does not exist inside the layout `R.layout.fragment_calender`.

**Comment by Bikjeun** [comment]
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@android:color/white"
    android:clickable="true"
    android:focusable="true"
    tools:context=".CalenderFragment">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <com.kizitonwose.calendarview.CalendarView
                android:id="@+id/Calendar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/calender_day"
                app:cv_monthHeaderResource="@layout/calender_header"
                app:cv_orientation="horizontal"
                app:cv_scrollMode="paged" />

            <TextView
                android:id="@+id/SelectedDateText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:background="#EEEEEE"
                android:fontFamily="sans-serif-medium"
                android:paddingStart="20dp"
                android:paddingTop="12dp"
                android:paddingEnd="20dp"
                android:paddingBottom="12dp"
                android:textAllCaps="true"
                android:textColor="@color/black"
                android:textSize="14sp"
                tools:text="4 June 2020" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/CalenderRv"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:nestedScrollingEnabled="false" />

        </LinearLayout>

    </androidx.core.widget.NestedScrollView>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/AddButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="20dp"
        app:tint="@color/white"
        app:backgroundTint="@color/colorAccent"
        app:srcCompat="@drawable/ic_add_circle_black_24dp"
        tools:ignore="VectorDrawableCompat" />

this is my fragment calender layout though... it is inside though

**Comment by kizitonwose** [comment]
Oh. Sorry. I just saw the other part of the code. The crash is happening because `onCreate()` is called before `onCreateView()` in a fragment. So when you access `calendarView ` on `onCreate()`, it is not initialized yet. You can either do the setup in `onCreateView() or override `onViewCreated() and do it there.
