### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Bikjeun** [kizitonwose/CalendarView#165]
error:
 java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
        at com.example.serenity.CalenderAdapter.updateAdapterForDate(CalenderAdapter.java:57)
        at com.example.serenity.CalenderFragment.selectDate(CalenderFragment.java:198)
        at com.example.serenity.CalenderFragment.onViewCreated(CalenderFragment.java:88)

``
public class CalenderAdapter extends RecyclerView.Adapter<CalenderAdapter.ViewHolder> {
    private Context context;
    private HashMap<LocalDate, ArrayList<CalenderEventModel>> events;

    public CalenderAdapter(Context context, HashMap<LocalDate, ArrayList<CalenderEventModel>> list) {
        this.context = context;
        events = list;
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new ViewHolder(LayoutInflater.from(context).inflate(R.layout.calender_items_view, parent, false));
    }

    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        ArrayList<CalenderEventModel> event = events.get(position);
        holder.item.setText(event.get(position).getText());
    }

    @Override
    public int getItemCount() {
        return events.size();
    }

    class ViewHolder extends RecyclerView.ViewHolder{
        TextView item;

        public ViewHolder(@NonNull View itemView) {
            super(itemView);

            item = itemView.findViewById(R.id.calenderItems);
        }
    }

    public void updateAdapterForDate(HashMap<LocalDate, ArrayList<CalenderEventModel>> events, LocalDate date) {
        events.get(date).clear(); // this line giving error
        events.get(date).addAll((this.events.get(date).isEmpty()) ? null :this.events.get(date));
        notifyDataSetChanged();

    }
}

**Comment by kizitonwose** [comment]
#160, #164, and now this? We can both agree I have tried as much to help. Unfortunately, I cannot assist you beyond this point. Issues are meant to be related to the library, please do not abuse it.
