### ISSUE TITLE
Show only selected range of dates.

### ISSUE THREAD

**Issue by rahulshah0891** [kizitonwose/CalendarView#166]
This library works really great but I have a specific requirement in which I need to show dates between last 4 weeks only. Is there any way to achieve this using Month header view? 

Any help would be really appreciated.

**Comment by kizitonwose** [comment]
It's hard to create a mental picture of what you are trying to achieve. Could you provide a rough sketch?

**Comment by rahulshah0891** [comment]
![Calendar_4weeks](https://user-images.githubusercontent.com/8446240/84116115-dd953100-aa4c-11ea-920d-12232c9b7fc0.png)

What I'm trying to achieve is shown in image.

**Comment by rahulshah0891** [comment]
So far I'm able to achieve this by making the visibility of textview as GONE. But it still occupies the space in the calendar view.
![calendarview](https://user-images.githubusercontent.com/8446240/84116774-1386e500-aa4e-11ea-9415-a41c7de90389.png)

**Comment by kizitonwose** [comment]
Hey, looks like you're close.

I recreated this using example 2 in the sample project.

<img src="https://user-images.githubusercontent.com/15170090/84362668-e3665000-abcd-11ea-9aa6-349ccdbc72ec.png" alt="Ex 2" width="250">


**Here's how I arrived at this:**

First, The XML:
```xml
<com.kizitonwose.calendarview.CalendarView
    android:id="@+id/exTwoCalendar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:cv_outDateStyle="none"
    app:cv_dayViewResource="@layout/example_2_calendar_day"
    app:cv_monthHeaderResource="@layout/example_2_calendar_header"
    app:cv_orientation="vertical" />
```
Note: `app:cv_outDateStyle="none"` as we don't want to worry about out dates in the logic, also `android:layout_height="wrap_content"`.

Next, we figure out the valid weeks we want to show on the calendar.

```Kotlin
val today = LocalDate.now()
val fourWeeksAgo = today.minusWeeks(3)
binding.exTwoCalendar.setup(fourWeeksAgo.yearMonth, today.yearMonth, daysOfWeek.first())

val weekOfYear = WeekFields.of(Locale.getDefault()).weekOfWeekBasedYear()
val validRange = (fourWeeksAgo.get(weekOfYear) rangeTo today.get(weekOfYear))
```

Note the `yearMonth` extension function we used here:

```Kotlin
val LocalDate.yearMonth: YearMonth
    get() = YearMonth.of(year, month)
```

Now, the binding logic:

```Kotlin
binding.exTwoCalendar.dayBinder = object : DayBinder<DayViewContainer> {
    override fun create(view: View) = DayViewContainer(view)
    override fun bind(container: DayViewContainer, day: CalendarDay) {
        container.day = day
        val textView = container.textView
        val parent = textView.parent as View
        textView.text = day.date.dayOfMonth.toString()

        if (day.owner == DayOwner.THIS_MONTH) {
            parent.visibility = when {
                day.date.get(weekOfYear) !in validRange -> View.GONE // Set 'gone' to remove every date not in the last four weeks.
                day.date > today -> View.INVISIBLE // Set 'invicible' to keep the space for future dates in the same week.
                else -> View.VISIBLE
            }
            when (day.date) {
                selectedDate -> {
                    textView.setTextColorRes(R.color.example_2_white)
                    textView.setBackgroundResource(R.drawable.example_2_selected_bg)
                }
                else -> {
                    textView.setTextColorRes(R.color.example_2_black)
                    textView.background = null
                }
            }
        } else {
            parent.visibility = when {
                day.date.get(weekOfYear) in validRange -> View.INVISIBLE // Set 'invicible' to keep the space for indates.
                else -> View.GONE
            }
        }
    }
}
```
The key here is that we hide/show the parent view as needed. The parent view has its width and height set internally so just hiding the view provided using `app:cv_dayViewResource` will not remove the space.

I guess this will be simplified when I add the ability to setup the calendar with start/end dates instead of just months. But until then, this gives the desired result.

I have included all the logic you need in this post but if you still want the full working project, let me know and I will push it to a branch for you.

Cheers!

**Comment by rahulshah0891** [comment]
Dude you are awesome!! The image solution you shown looks exactly same to what I'm trying to achieve. I'll definitely give it a try. Also it would be really really great if you provide an option to display selected date range in your library project so that it could help others like me.

Thanks again! 👍💯

**Comment by kizitonwose** [comment]
> Also it would be really really great if you provide an option to display selected date range in your library project so that it could help others like me.
> 

Yes, this is planned for the future. I just have other things going on right now.

Also, while looking at the logic again, I realized that if four weeks ago and this week are in different years(e.g: December/January), then `val validRange = (fourWeeksAgo.get(weekOfYear) rangeTo today.get(weekOfYear))` will be incorrect across years.

So I made some changes to handle this.

```Kotlin
val today = LocalDate.now()
val fourWeeksAgo = today.minusWeeks(3)
binding.exTwoCalendar.setup(fourWeeksAgo.yearMonth, today.yearMonth, daysOfWeek.first())

val weekOfYear = WeekFields.of(Locale.getDefault()).weekOfWeekBasedYear()
// Introduced this function so we now check both the weekOfYear and year.
fun getPair(date: LocalDate) = Pair(date.year, date.get(weekOfYear))
val validRange = (0..3).map {
    getPair(today.minusWeeks(it.toLong())) // Use getPair() to generate the needed range.
}
```

When binding, we also use the `getPair()` function:

```Kotlin
if (day.owner == DayOwner.THIS_MONTH) {
    parent.visibility = when {
        getPair(day.date) !in validRange -> View.GONE
        day.date > today -> View.INVISIBLE
        else -> View.VISIBLE
    }
    when (day.date) {
        // Removed for simplicity
    }
} else {
    parent.visibility = when {
        getPair(day.date) in validRange -> View.INVISIBLE
        else -> View.GONE
    }
}
```

**Comment by kizitonwose** [comment]
I guess I can close this for now. If you need further assistance, let me know!
