### ISSUE TITLE
Min and max range for range calender

### ISSUE THREAD

**Issue by sandeep7644** [kizitonwose/CalendarView#17]
how can i set values for minimum and maximum values.
there is a method "setup" in which i can set minimum date but what about maximum date ?
Please help.

**Comment by kizitonwose** [comment]
The setup method allows you to set values for start and end months. Is that what you mean?

**Comment by kizitonwose** [comment]
The described feature is supported by the library so I'll have to close this issue. Feel free to create a new issue if you need further assistance.
