### ISSUE TITLE
Infinite scrollview

### ISSUE THREAD

**Issue by hiteshsarsava** [kizitonwose/CalendarView#172]
Hello Brother,

You have done a fantastic job by making this library. Here i have one situation in this library. Well what if do not know exact value of the first month and last month when i am doing the setup calender. In other words, I want to make calender view is in infinite scroll.
When user scroll, the next month and year will be added automatically in the list of calender. So i don't have to worry about the set up of first month and last month in calender. The next month logic would depends on the current month and previous month. I think you get what i am trying to  suggesting.

Thank you.

**Comment by kizitonwose** [comment]
This issue was raised in #67 which led to the introduction of `updateRange()` method. You can add a scroll listener to the calendarView and when it gets to top/bottom, you update the start/end month and this gives the infinite scroll effect.

**Comment by kizitonwose** [comment]
Guess I can close this. Feel free to comment if you need anything else.
