### ISSUE TITLE
App crash when changing view from month to week and week to month

### ISSUE THREAD

**Issue by hiteshsarsava** [kizitonwose/CalendarView#174]
Here log :

2020-07-02 17:32:06.927 19476-19476/com.example.calenderview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.calenderview, PID: 19476
    java.lang.IndexOutOfBoundsException: Index: 521, Size: 241
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.notifyMonthScrollListenerIfNeeded(CalendarAdapter.kt:187)
        at com.kizitonwose.calendarview.ui.CalendarAdapter$notifyMonthScrollListenerIfNeeded$1.onAnimationsFinished(CalendarAdapter.kt:181)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationsFinished(RecyclerView.java:13342)
        at androidx.recyclerview.widget.DefaultItemAnimator.dispatchFinishedWhenDone(DefaultItemAnimator.java:551)
        at androidx.recyclerview.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:249)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:793)
        at android.view.Choreographer.doFrame(Choreographer.java:724)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7509)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

====================================================
My Code ::

void init(CalendarView calendarView) {

        YearMonth currentMonth = YearMonth.now();

        DayOfWeek firstDayOfWeek = WeekFields.of(Locale.getDefault()).getFirstDayOfWeek();
        calendarView.setOrientation(RecyclerView.HORIZONTAL);
        calendarView.setScrollMode(ScrollMode.PAGED);
        calendarView.setHasBoundaries(true);
        calendarView.setMaxRowCount(6);
        calendarView.setInDateStyle(InDateStyle.ALL_MONTHS);

        endMonth = currentMonth.plusMonths(10);
        calendarView.setup(currentMonth.minusYears(10), currentMonth.plusYears(10), firstDayOfWeek);
        calendarView.scrollToMonth(currentMonth);
    }

void monthToWeek(CalendarView calendarView, boolean monthToWeek) {

        LocalDate firstDate = Objects.requireNonNull(calendarView.findFirstVisibleDay()).getDate();
        LocalDate lastDate = Objects.requireNonNull(calendarView.findLastVisibleDay()).getDate();

        int oneWeekHeight = calendarView.getDayHeight();
        int oneMonthHeight = oneWeekHeight * 6;

        int oldHeight = monthToWeek ? oneMonthHeight : oneWeekHeight;
        int newHeight = monthToWeek ? oneWeekHeight : oneMonthHeight;

        // Animate calendar height changes.
        ValueAnimator animator = ValueAnimator.ofInt(oldHeight, newHeight);
        animator.addUpdateListener(animation -> calendarView.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, (Integer) animation.getAnimatedValue())));

        // When changing from month to week mode, we change the calendar's
        // config at the end of the animation(doOnEnd) but when changing
        // from week to month mode, we change the calendar's config at
        // the start of the animation(doOnStart). This is so that the change
        // in height is visible. You can do this whichever way you prefer.

        animator.addListener(new AnimatorListenerAdapter() {
            @Override
            public void onAnimationStart(Animator animation) {
                super.onAnimationStart(animation);

                if (!monthToWeek) {
                    calendarView.setInDateStyle(InDateStyle.ALL_MONTHS);
                    calendarView.setMaxRowCount(6);
                    calendarView.setHasBoundaries(true);
                }
            }

            @Override
            public void onAnimationEnd(Animator animation) {
                super.onAnimationEnd(animation);

                if (monthToWeek) {
                    calendarView.setInDateStyle(InDateStyle.FIRST_MONTH);
                    calendarView.setMaxRowCount(1);
                    calendarView.setHasBoundaries(false);
                }
                if (monthToWeek) {
                    // We want the first visible day to remain
                    // visible when we change to week mode.
                    calendarView.scrollToDate(firstDate);
                } else {
                    // When changing to month mode, we choose current
                    // month if it is the only one in the current frame.
                    // if we have multiple months in one frame, we prefer
                    // the second one unless it's an outDate in the last index.
                    if (YearMonth.from(firstDate).equals(YearMonth.from(lastDate))) {
                        calendarView.scrollToMonth(YearMonth.from(firstDate));
                    } else {
                        // We compare the next with the last month on the calendar so we don't go over.
                        YearMonth scrollMonth;
                        if (YearMonth.from(firstDate).plusMonths(1).getMonthValue() > lastDate.getMonthValue()) {
                            scrollMonth = endMonth;
                        } else {
                            scrollMonth = YearMonth.from(firstDate);
                        }
                        calendarView.scrollToMonth(scrollMonth);
                    }
                }
            }
        });

        animator.setDuration(0);
        animator.start();
    }

class DayViewContainer extends ViewContainer {
            TextView textView;
            CalendarDay day;
            View dotView;
            LinearLayout linDay;
            AppCompatImageView dateBg;

            public DayViewContainer(@NotNull View view) {
                super(view);
                textView = view.findViewById(R.id.calendarDayText);
                dotView = view.findViewById(R.id.exThreeDotView);
                linDay = view.findViewById(R.id.linDay);
                dateBg = view.findViewById(R.id.dateBg);
                linDay.setOnClickListener(v -> {
                    if (day.getOwner() == DayOwner.THIS_MONTH) {
                        selectDate(day.getDate());
                    }
                    binding.calendarView.notifyDayChanged(day);
                });
            }
        }

        binding.calendarView.setDayBinder(new DayBinder<DayViewContainer>() {
            @Override
            public void bind(@NotNull DayViewContainer container, @NotNull CalendarDay calendarDay) {
                TextView tvDate = container.textView;
                View dotView = container.dotView;
//                LinearLayout linDay = container.linDay;
                container.day = calendarDay;
                tvDate.setText(String.format(Locale.ENGLISH, "%d", calendarDay.getDate().getDayOfMonth()));

                if (calendarDay.getOwner() == DayOwner.THIS_MONTH) {

                    if (today.equals(calendarDay.getDate())) {
                        container.dateBg.setBackgroundDrawable(getResources().getDrawable(R.drawable.drw_today_bg));
                        tvDate.setTextColor(Color.BLACK);
                        dotView.setVisibility(View.INVISIBLE);
                    } else if (selectedDate.equals(calendarDay.getDate())) {
                        container.dateBg.setBackgroundDrawable(getResources().getDrawable(R.drawable.drw_selected_bg));
                        tvDate.setTextColor(Color.WHITE);
                        dotView.setVisibility(View.INVISIBLE);
                    } else {
                        container.dateBg.setBackgroundDrawable(null);
                        tvDate.setTextColor(Color.WHITE);
                        dotView.setVisibility(events.get(calendarDay.getDate()) != null && events.get(calendarDay.getDate()).size() > 0 ? View.VISIBLE : View.INVISIBLE);
                    }
                } else {
                    container.dateBg.setBackgroundDrawable(null);
                    tvDate.setTextColor(ResourcesCompat.getColor(getResources(), R.color.colorDisableDate, null));
                    dotView.setVisibility(View.INVISIBLE);
                }
            }

            @NotNull
            @Override
            public DayViewContainer create(@NotNull View view) {

                return new DayViewContainer(view);
            }
        });

        binding.calendarView.setMonthScrollListener(calendarMonth -> {

            if (binding.calendarView.getMaxRowCount() == 6) {
                binding.tvYear.setText(String.format(Locale.ENGLISH, "%d", calendarMonth.getYear()));
                binding.tvMonth.setText(String.format(Locale.ENGLISH, "%s", monthTitleFormatter.format(calendarMonth.getYearMonth())));
            } else {
                // In week mode, we show the header a bit differently.
                // We show indices with dates from different months since
                // dates overflow and cells in one index can belong to different
                // months/years.
                LocalDate firstDate = calendarMonth.getWeekDays().get(0).get(0).getDate();
                List<List<CalendarDay>> calenderList = calendarMonth.getWeekDays();
                List<CalendarDay> lastItem = calenderList.get(calenderList.size() - 1);
                CalendarDay lastDay = lastItem.get(lastItem.size() - 1);
                LocalDate lastDate = lastDay.getDate();

                if (YearMonth.from(firstDate).equals(YearMonth.from(lastDate))) {
                    binding.tvYear.setText(String.format(Locale.ENGLISH, "%d", YearMonth.from(firstDate).getYear()));
                    binding.tvMonth.setText(String.format(Locale.ENGLISH, "%s", monthTitleFormatter.format(YearMonth.from(firstDate))));
                } else {
                    binding.tvMonth.setText(String.format(Locale.ENGLISH, "%s - %s", monthTitleFormatter.format(YearMonth.from(firstDate)), monthTitleFormatter.format(YearMonth.from(lastDate))));

                    if (YearMonth.from(firstDate).getYear() == YearMonth.from(lastDate).getYear()) {
                        binding.tvYear.setText(String.format(Locale.ENGLISH, "%d", YearMonth.from(firstDate).getYear()));
                    } else {
                        binding.tvYear.setText(String.format(Locale.ENGLISH, "%d - %d", YearMonth.from(firstDate).getYear(), YearMonth.from(lastDate).getYear()));
                    }
                }
            }
//            // Select the first day of the month when
//            // we scroll to a new month.
//            selectDate(calendarMonth.getYearMonth().atDay(selectedDate.getDayOfMonth()));
            return Unit.INSTANCE;
        });

**Comment by hemaidbizspice** [comment]
@hiteshsarsava  

add this 
  `          selectedDate?.let {
                // Clear selection if we scroll to a new month.
                selectedDate = null
                val calenderView = binding.exFiveCalendar
              // check if the calenderView which is a recycle view to see if it computing or not
                if (!calenderView.isComputingLayout && calenderView.scrollState == SCROLL_STATE_IDLE) {
                    calenderView.notifyDateChanged(it)
                    updateAdapterForDate(null)
                }
            }`

**Comment by kizitonwose** [comment]
@hemaidbizspice has a good point but if that does not fix your issue, I see the package name in the crash log is `com.example.calenderview` so I assume this is a small test project. You can share it here and I am happy to take a look at the crash directly.
