### ISSUE TITLE
Change when to fire monthScrollListener

### ISSUE THREAD

**Issue by DantheCodingGui** [kizitonwose/CalendarView#175]
Hi,

Minor thing but, for styling inspiration I've been looking at the android default calendar app and I've noticed that it's month header changes as soon as the new month is taking up most of the calendar's width (rather than once the new month has fully settled and is taking up the full width of the calendar).

Is there any way that CalendarView could be changed to work the same way, such that the `monthScrollListener` can be fired halfway through a swipe instead of at the end.

**Comment by kizitonwose** [comment]
I can see how that can be useful in some cases, especially aesthetically. But maybe not everyone wants it that way? It'll be nice if users can choose which one they want. I'll add it to a list of features that can be added in the future and we'll see how that goes.

**Comment by kizitonwose** [comment]
Closing this for now as there's no timeline for it at the moment but will definitely revisit when ready.
