### ISSUE TITLE
Unable to disable scroll

### ISSUE THREAD

**Issue by VladimirVasic994** [kizitonwose/CalendarView#176]
I am unable to disable the scrolling of calendar view. I have a case where I need to disable scrolling of my weekly calendar view when the monthly calendar view is being shown.

**Comment by kizitonwose** [comment]
Did you try the suggestions in #38? [See here](https://github.com/kizitonwose/CalendarView/issues/38#issuecomment-525786644)

**Comment by kizitonwose** [comment]
Guess I can close this. Let me know if the suggestions don't work for you.

**Comment by VladimirVasic994** [comment]
@kizitonwose Hey, sorry. It worked out perfectly. Thank you for the quick response and sorry for waiting soo long for my response.
