### ISSUE TITLE
Dotview add calendar

### ISSUE THREAD

**Issue by rafaelkowal** [kizitonwose/CalendarView#177]
I need to add dotview to the calendar as and where I need to enter a list of dates to add dotview?

**Comment by kizitonwose** [comment]
See example 5 in the sample app. Just like the lines but use dots instead.

**Comment by rafaelkowal** [comment]
I need to add the dotviews after the return of the database with the list of dates, would there be any function that I could call later to add the dotviews?

**Comment by kizitonwose** [comment]
`notifyCalendarChanged()`
