### ISSUE TITLE
Support for Hijri Calendar

### ISSUE THREAD

**Issue by suyashdixit** [kizitonwose/CalendarView#178]
Hello, 
Great lib. But I want to change it to Hijri Calendar (Arabic calendar) format. How can I do that?
Something like this: https://github.com/sahaab/HijriCalendar-master

**Comment by kizitonwose** [comment]
There's a fork of this library with this feature [here](https://github.com/sma6871/CalendarView).

**Comment by suyashdixit** [comment]
Outstanding. Thank you for the help. Also do you know about the fork for Farsi - Persian/Iranian Calendar?

**Comment by kizitonwose** [comment]
> Outstanding. Thank you for the help. Also do you know about the fork for Farsi - Persian/Iranian Calendar?

Unfortunately, I don't. Sorry.
