### ISSUE TITLE
Set dayHeight to "wrap_content"

### ISSUE THREAD

**Issue by unveloper** [kizitonwose/CalendarView#182]
Hi! Thanks for this awesome library.

I noticed the calendar will cut the day cells if the height is greater than "DAY_SIZE_SQUARE".
Is possible to have a way of telling the widget to set the day cells height to "wrap content" so everything inside will always be visible (without manually calculate the correct height)?

Thanks

**Comment by kizitonwose** [comment]
Could you explain this a bit more: `if the height is greater than "DAY_SIZE_SQUARE"`? 
I'm not sure if you mean the calendar height or the `dayHeight` value.

**Comment by unveloper** [comment]
I mean both. Basically I want a way of telling the calendar to make the cells as high as needed, making every view inside visible.
Therefore the calendar total height must adjust (like I was setting "wrap_content").

Now i have the cell with this layout:
![designer layout](https://user-images.githubusercontent.com/29709411/87910239-ffc99800-ca69-11ea-9c05-4c6bed0b3025.PNG)

And this is the result:
![Screenshot_1595229715](https://user-images.githubusercontent.com/29709411/87910579-84b4b180-ca6a-11ea-91f3-8d9416150df6.png)

As you can see the blue view and the three dots are cut.

This is the fragment xml layout:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:id="@+id/calendarFragment">

	<data>

		<!--<import type="com.yyy.app.XXX.R" />-->

		<variable
			name="viewModel"
			type="com.yyy.app.XXX.presentation.calendar.CalendarViewModel" />
	</data>

	<androidx.constraintlayout.widget.ConstraintLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:padding="@dimen/dimen_16dp">

		<androidx.constraintlayout.widget.Guideline
			android:id="@+id/guideline"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:orientation="vertical"
			app:layout_constraintGuide_percent="0.50" />

		<TextView
			android:id="@+id/currentMonthTextView"
			style="@style/TextAppearance.MaterialComponents.Headline5"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:text="@{viewModel.currentMonthTitle}"
			app:layout_constraintEnd_toEndOf="@id/guideline"
			app:layout_constraintStart_toStartOf="@id/guideline"
			app:layout_constraintTop_toTopOf="parent"
			tools:text="NOV 19" />

		<androidx.appcompat.widget.AppCompatImageView
			android:id="@+id/previousMonthImageView"
			android:layout_width="@dimen/dimen_50dp"
			android:layout_height="@dimen/dimen_50dp"
			android:layout_marginEnd="@dimen/dimen_15dp"
			android:background="?attr/selectableItemBackgroundBorderless"
			android:src="@drawable/chevron2_left_grey_500_24dp"
			app:layout_constraintBottom_toBottomOf="@id/currentMonthTextView"
			app:layout_constraintEnd_toStartOf="@id/currentMonthTextView"
			app:layout_constraintTop_toTopOf="@id/currentMonthTextView" />

		<androidx.appcompat.widget.AppCompatImageView
			android:id="@+id/nextMonthImageView"
			android:layout_width="@dimen/dimen_50dp"
			android:layout_height="@dimen/dimen_50dp"
			android:layout_marginStart="@dimen/dimen_15dp"
			android:background="?attr/selectableItemBackgroundBorderless"
			android:src="@drawable/chevron2_right_grey_500_24dp"
			app:layout_constraintBottom_toBottomOf="@id/currentMonthTextView"
			app:layout_constraintStart_toEndOf="@id/currentMonthTextView"
			app:layout_constraintTop_toTopOf="@id/currentMonthTextView" />

		<com.kizitonwose.calendarview.CalendarView
			android:id="@+id/calendarView"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:layout_marginTop="@dimen/dimen_5dp"
			android:layout_marginBottom="5dp"
			app:cv_dayViewResource="@layout/layout_calendar_day"
			app:cv_monthHeaderResource="@layout/calendar_header"
			app:cv_orientation="horizontal"
			app:cv_outDateStyle="endOfGrid"
			app:cv_scrollMode="paged"
			app:layout_constraintEnd_toEndOf="parent"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/currentMonthTextView" />

	</androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```

And this is the layout_calendar_day.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:background="@color/grey">

	<androidx.constraintlayout.widget.ConstraintLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:layout_margin="@dimen/dimen_1dp"
		android:background="@color/white">

		<TextView
			android:id="@+id/dayTextView"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_marginStart="2dp"
			android:layout_marginTop="2dp"
			android:padding="@dimen/dimen_5dp"
			android:textSize="12sp"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toTopOf="parent"
			tools:background="@drawable/calendar_day_selected_background"
			tools:text="22" />

		<androidx.cardview.widget.CardView
			android:id="@+id/event1Container"
			style="@style/CalendarEventPlaceHolder"
			app:layout_constraintEnd_toEndOf="parent"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/dayTextView"
			app:cardBackgroundColor="@color/expense" />

		<androidx.cardview.widget.CardView
			android:id="@+id/event2Container"
			style="@style/CalendarEventPlaceHolder"
			app:layout_constraintEnd_toEndOf="parent"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/event1Container"
			app:cardBackgroundColor="@color/income" />

		<androidx.cardview.widget.CardView
			android:id="@+id/event3Container"
			style="@style/CalendarEventPlaceHolder"
			app:layout_constraintEnd_toEndOf="parent"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/event2Container"
			app:cardBackgroundColor="@color/debt" />

		<androidx.cardview.widget.CardView
			android:id="@+id/event4Container"
			style="@style/CalendarEventPlaceHolder"
			app:layout_constraintEnd_toEndOf="parent"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/event3Container"
			app:cardBackgroundColor="@color/credit" />

		<View
			android:id="@+id/dot1Container"
			style="@style/CalendarEventDot"
			android:layout_marginStart="@dimen/dimen_2dp"
			android:layout_marginTop="@dimen/dimen_2dp"
			app:layout_constraintStart_toStartOf="parent"
			app:layout_constraintTop_toBottomOf="@id/event4Container" />

		<View
			android:id="@+id/dot2Container"
			style="@style/CalendarEventDot"
			android:layout_marginStart="@dimen/dimen_2dp"
			app:layout_constraintBottom_toBottomOf="@id/dot1Container"
			app:layout_constraintStart_toEndOf="@id/dot1Container"
			app:layout_constraintTop_toTopOf="@id/dot1Container" />

		<View
			android:id="@+id/dot3Container"
			style="@style/CalendarEventDot"
			android:layout_marginStart="@dimen/dimen_2dp"
			app:layout_constraintBottom_toBottomOf="@id/dot1Container"
			app:layout_constraintStart_toEndOf="@id/dot2Container"
			app:layout_constraintTop_toTopOf="@id/dot1Container" />

	</androidx.constraintlayout.widget.ConstraintLayout>

</FrameLayout>
```

**Comment by kizitonwose** [comment]
Okay, so this would mean one of two possible things. Do you want all cells to become the size of the biggest cell? Or you want each cell to just wrap its content meaning they would all possibly vary in size.

**Comment by unveloper** [comment]
All cells to become the size of the biggest cell :)

**Comment by kizitonwose** [comment]
Unfortunately, that is not possible. The library depends on you to make the calculations and provide the desired size.

**Comment by unveloper** [comment]
That's a bummer...
Can you at least post an example of how to make the calculation?

Thanks

**Comment by TadDancer** [comment]
Hey there, if I may add to this:

I'm trying to do a similar thing - I have a calendar, that is set up with scrollMode=paged and hasBoundaries=true - so basically just a per month calendar.
Now of course the row number changes between different months, between 4 and 6. In a basic Recyclerview I'd just chain all the views together and make it match the parent - unfortunately I think this library does not provide that functionality. Am I right?

In addition to that, I want single rows to stretch larger if there's more content in them than in others. I can kind of accomplish this within the dayviewcontainer with this: (Sorry, still very new to Android and Kotlin, this might be ugly)

`view.setOnClickListener {

            val grid= view.parent.parent as ViewGroup

            val remHeight=2*fullHeight/3/(grid.childCount-2)
            val selHeight=fullHeight-(grid.childCount-2)*remHeight


            for (rowPos in 0 until grid.childCount) {
                val subRow=grid.getChildAt(rowPos) as ViewGroup
                for (celPos in 0 until subRow.childCount) {
                    val cousinView = subRow.getChildAt(celPos)
                    if (cousinView.id==R.id.dayLayout) {
                        val params = cousinView.layoutParams
                        val animator = ValueAnimator.ofInt(params.height, remHeight)
                        animator.addUpdateListener {

                            cousinView.updateLayoutParams {
                                height = it.animatedValue as Int
                            }
                        }
                        animator.duration = 250
                        animator.start()

                    }

                }
            }


            val siblingRow = view.parent as ViewGroup
            for (itemPos in 0 until siblingRow.childCount) {
                val subview = siblingRow.getChildAt(itemPos)
                val params = subview.layoutParams
                val animator = ValueAnimator.ofInt(params.height, selHeight)
                animator.addUpdateListener {
                    subview.updateLayoutParams {
                        height = it.animatedValue as Int
                    }
                }

                animator.duration = 250
                animator.start()
            }

        }`

The first part changes all the cells to the size of the smaller rows (Which is 2 thirds of the fullHeight - which is a value I calculated somewhere else - divided between them).
The second part changes all the cells in the same row as the one I just clicked to one third of the fullHeight.

Now of course I could build on that and change certain rows depending on their content and so on and so forth, but I'm feeling like this can't be the most elegant way...

Maybe someone can push me into the right direction? Maybe I'm missing something entirely.

**Comment by TadDancer** [comment]
Alright, just so noone has to Deal with my ugly yesterday's code, I've now figured it out - I think. This is how I'm doing it now:

In daybinder, I do this:

`
 override fun bind(container: DayViewContainer, day: CalendarDay) {

                val heightYearMonth =
                if (day.owner==DayOwner.THIS_MONTH) day.date.yearMonth
                else if (day.owner==DayOwner.NEXT_MONTH) day.date.yearMonth.minusMonths(1)
                else day.date.yearMonth.plusMonths(1)

                val weekCount=heightYearMonth.atEndOfMonth().get(
                    WeekFields.ISO.weekOfMonth()
                )+(1-heightYearMonth.atDay(1).get(
                    WeekFields.ISO.weekOfMonth()
                ))

                container.textView.text = day.date.dayOfMonth.toString()
                container.day = day
                container.setHeight((fullHeight-94)/weekCount)

            }
`

And I've added this funtion to the dayViewContainer class:

`
fun setHeight(cellHeight: Int) {

        val params = view.layoutParams
        params.height=cellHeight
        view.layoutParams=params

    }
`

Now you can also add more dependencies in the binder, that would for instance calculate how high you need certain columns or rows to be - I'd advise to use the weekOfYear to determine it, then you can decrease the other rows of the same month accordingly (in a page setup) - if you have a scrolling setup the other rows don't matter, but you should probably still increase the height of all the cells of the same week, so that row is even.

**Comment by kizitonwose** [comment]
Hopefully, @TadDancer's logic works for anyone who needs to do this. Closing this for now.
