### ISSUE TITLE
Setting of day width/height 

### ISSUE THREAD

**Issue by luis-cortes** [kizitonwose/CalendarView#184]
It seems like it's impossible to change the width and height of the day cells independent of one another. From what I can tell, setting either the height or width turns off `autoSize`. I feel like the API mislead me into thinking I could reduce the space between rows (while keeping the width the same) by simply changing the height because they are separate properties. 

Perhaps it should be one method that accepts width and height instead? 

While a single function would be a step in the right direction, I think this way of setting the cell size is a bit confusing. I expected the library to respect the height and width set on the `dayViewRes`, but instead it ignores it, sets it to `match_parent`, and uses `dayWidth` and `dayHeight` from `CalendarView` as the sources of truth.

I think this is a bit of a gotcha and it would be helpful to have this behavior documented. Ideally, the user's layout determines the cell size.

For anyone wondering how to reduce the space between rows, here's how I did it:

```
// View.doOnPreDraw is found in core-ktx
doOnPreDraw {
  dayWidth = calendarView.width / 7
  dayHeight = (dayWidth * .666).toInt()
}
```

**Comment by kizitonwose** [comment]
What are the spaces between rows that you're referring to? Could you share an annotated screenshot maybe from the sample app to clarify?

**Comment by luis-cortes** [comment]
![row-example](https://user-images.githubusercontent.com/16602090/88000686-494acf00-cacc-11ea-938d-f4130fc0f0bb.png)


This is the space that I'm referring to. I dug into this a little more and it seems like what I'm seeing is a timing issue. The calendar only get messed up if you don't make height/width adjustments inside the `doOnPreDraw` block. 

If we add `binding.exOneCalendar.dayHeight = 120` to `Example1Fragment` without wrapping it in `doOnPreDraw` the calendar looks like this.

![example2](https://user-images.githubusercontent.com/16602090/88001049-28cf4480-cacd-11ea-8f7a-60015a841a68.png)


Using `doOnPreDraw I get exactly what I would have expected. 

![example3](https://user-images.githubusercontent.com/16602090/88001147-6c29b300-cacd-11ea-8ad2-7561eae7c390.png)

**Comment by kizitonwose** [comment]
Yep, setting either width or height does disable auto-size. I think the `dayHeight` and `dayWidth` properties should be properly documented to include this. We do something similar in example 6 but using `DisplayMetrics` instead.

**Comment by luis-cortes** [comment]
Can we make it a function instead so it's more clear that they need to be set together? This would also avoid an extra call to `invalidateViewHolders()`.

In fact, there are a few other properties that would benefit from this treatment (padding, margin, maxRowCount, etc).

**Comment by kizitonwose** [comment]
I was going to add something like an `update` block, which would not trigger the `invalidateViewHolders()`, `updateApapterMonthConfig()` or `updateAdapterViewConfig()` methods if properties are updated inside it. This way we avoid creating setter methods for all the properties of CalendarView.

Something like this:

```kotlin
open class CalendarView : RecyclerView {
	....
    private var isUpdating = false
    private var pendingAdapterMonthConfigUpdate = false
    private var pendingAdapterViewConfigUpdate = false
    private var pendingViewHolderInvalidation = false
    fun update(block: CalendarView.() -> Unit) {
        isUpdating = true
        this.block()
        isUpdating = false
        if (pendingAdapterMonthConfigUpdate) updateAdapterMonthConfig()
        if (pendingAdapterViewConfigUpdate) updateAdapterViewConfig()
        if (pendingViewHolderInvalidation) invalidateViewHolders()
		pendingAdapterMonthConfigUpdate = false
        pendingAdapterViewConfigUpdate = false
        pendingViewHolderInvalidation = false
    }
	....
}
```
Then the update methods will look like:

```kotlin
private fun updateAdapterMonthConfig() {
    if (isUpdating) {
        pendingAdapterMonthConfigUpdate = true
        return
    }
    ....
}

private fun invalidateViewHolders() {
    if (isUpdating) {
        pendingViewHolderInvalidation = true
        return
    }
    ....
}

private fun updateAdapterViewConfig() {
    if (isUpdating) {
        pendingAdapterViewConfigUpdate = true
        return
    }
    ....
}
```

Now using example 1 where we update a lot of configs, we can write:

```kotlin
animator.doOnStart {
    if (!monthToWeek) {
        binding.exOneCalendar.update { // No more => exOneCalendar.apply{}
            inDateStyle = InDateStyle.ALL_MONTHS
            maxRowCount = 6
            hasBoundaries = true
        }
    }
}
```

What do you think?

**Comment by kizitonwose** [comment]
Of course, this is a solution to the second problem(multiple calls to the methods) not the one regarding the confusing `dayHeight/Width` properties. A solution to that would be to use the `Size` class available in the framework and have it as an optional so setting it to null would imply that you want automatic sizing.

**Comment by luis-cortes** [comment]
Would you mind if we moved [this discussion](https://github.com/kizitonwose/CalendarView/issues/184#issuecomment-662649844) to a new issue? It'll keep me from getting confused and keep the issues focused.

**Comment by kizitonwose** [comment]
> Would you mind if we moved [this discussion](https://github.com/kizitonwose/CalendarView/issues/184#issuecomment-662649844) to a new issue? It'll keep me from getting confused and keep the issues focused.

Created #187

**Comment by luis-cortes** [comment]
So I've actually been playing around with a different way of laying out all the day views on a separate branch. This approach uses a `GridLayout`. Remember the `monthBodyLayout` I removed? This `GridLayout` replaces that and eliminates the need for `WeekHolders` entirely. More importantly, this approach allows the user to control the size of the day view from the day view layout file like they might expect. This means there's no longer a need for the `dayView`/`dayWidth` properties since the user can make a square view by simply setting width dp == height dp. 

I think I'm pretty close to making the calendars look identical with a few exceptions, but sadly, I don't have any more time to keep looking into it. I left a pretty lengthy and detailed commit message on it if you want to take a look. Here's [the branch](https://github.com/luis-cortes/CalendarView/tree/replacing_linear_and_frame_layouts_with_grid_layout)

**Comment by luis-cortes** [comment]
Btw, if we can get the above approach to work and change `rootLayout` to be `GridLayout`, we can get rid of even _more_ views since the headers can be the first and last rows on the `GridLayout` 😂

**Comment by kizitonwose** [comment]
> I left a pretty lengthy and detailed commit message on it if you want to take a look.

Yes, I'll definitely take a look sometime. Removing the inner framelayout is already a huge win as there would be approx 30 of those in a single month. The inner layouts would only be about 4 per month but would still be great if we can get rid of them.
