### ISSUE TITLE
Multiple method calls during property updates.

### ISSUE THREAD

**Issue by kizitonwose** [kizitonwose/CalendarView#187]
**Problem:**

`invalidateViewHolders()`, `updateApapterMonthConfig()` and `updateAdapterViewConfig()` methods are called multiple times if related properties are set in the CalendarView class.

**Proposed solution:**

Add an `update` method which will not trigger any of the above methods if properties are updated inside it. This way we avoid creating setter methods for all related properties of CalendarView.

Something like this:

```kotlin
open class CalendarView : RecyclerView {
	....
    private var isUpdating = false
    private var pendingAdapterMonthConfigUpdate = false
    private var pendingAdapterViewConfigUpdate = false
    private var pendingViewHolderInvalidation = false
    fun update(block: CalendarView.() -> Unit) {
        isUpdating = true
        this.block()
        isUpdating = false
        if (pendingAdapterMonthConfigUpdate) updateAdapterMonthConfig()
        if (pendingAdapterViewConfigUpdate) updateAdapterViewConfig()
        if (pendingViewHolderInvalidation) invalidateViewHolders()
		pendingAdapterMonthConfigUpdate = false
        pendingAdapterViewConfigUpdate = false
        pendingViewHolderInvalidation = false
    }
	....
}
```
Then the update methods will look like:

```kotlin
private fun updateAdapterMonthConfig() {
    if (isUpdating) {
        pendingAdapterMonthConfigUpdate = true
        return
    }
    ....
}

private fun invalidateViewHolders() {
    if (isUpdating) {
        pendingViewHolderInvalidation = true
        return
    }
    ....
}

private fun updateAdapterViewConfig() {
    if (isUpdating) {
        pendingAdapterViewConfigUpdate = true
        return
    }
    ....
}
```

Now using example 1 where we update a lot of configs, we can write:

```kotlin
animator.doOnStart {
    if (!monthToWeek) {
        binding.exOneCalendar.update { // No more => exOneCalendar.apply{}
            inDateStyle = InDateStyle.ALL_MONTHS
            maxRowCount = 6
            hasBoundaries = true
        }
    }
}
```

Continued from #184

**Comment by luis-cortes** [comment]
Thanks for making a new issue. 

I don't understand why we need to check if there's already an update in progress. Would you mind explaining that?

Outside of that, looking at this solution makes me think separating the configuration might be helpful.

What if instead of grouping everything together under a single `update` method we provided separate update methods with default (or null) values so users have the ability to update only what they need? 

```
animator.doOnStart {
    if (!monthToWeek) {
        binding.exOneCalendar.updateMonthConfig( 
            inDateStyle = InDateStyle.ALL_MONTHS,
            maxRowCount = 6,
            hasBoundaries = true
        )
    }
}
```
```
open class CalendarView : RecyclerView {
	....
    fun updateMonthConfig(all month config fields) {
        calendarAdapter?.monthConfig =  calendarAdapter?.monthConfig.copy(any month config fields that changed)
        calendarAdapter?.notifyDataSetChanged()
        post { calendarAdapter?.notifyMonthScrollListenerIfNeeded() }
     }

    fun updateViewConfig(viewConfig: viewConfig) {
       calendarAdapter?.viewConfig = viewConfig
       invalidateViewHolders()
     }
}
```

This approach greatly reduces the number or properties on `CalendarView` and cuts all the mutability way down.

**Comment by kizitonwose** [comment]
> I don't understand why we need to check if there's already an update in progress. Would you mind explaining that?

`isUpdating` is a flag that just keeps track of the fact that properties are being set inside the `block()`, you can see that it is reset to false after the `block()` functions returns, to allow `updateAdapterViewConfig()` etc to proceed with updates afterward.

---

> `updateViewConfig(viewConfig: viewConfig)`

I want to avoid exposing the configs to users because these can change often(your last two PRs for example) and would lead to constant breaking changes in the library. Exposing the configs also mean that users now have to know which property belongs to which config instead of just looking at what's directly available in the `CalendarView` class.

**Comment by luis-cortes** [comment]
> `isUpdating` is a flag that just keeps track of the fact that properties are being set inside the `block()`, you can see that it is reset to false after the `block()` functions returns, to allow `updateAdapterViewConfig()` etc to proceed with updates afterward.

So if I understand correctly, breaking things apart and eliminating the properties would eliminate the need for the flags altogether no? I think this would really simplify the code and make it safer.

> I want to avoid exposing the configs to users because these can change often(your last two PRs for example) 
I don't think my last two PRs changed anything in the API. Did they?
Regardless of whether the configuration is accessed via a property of or as a parameter of a function, outright removal would be a breaking change. So I don't think there's any value in keeping them as properties for the sake of API stability.

>would lead to constant breaking changes in the library.
Even if things do need to change, you can always keep the old way of doing things and annotate with `@Deprecated`. 
Moreover, the library hasn't hit 1.0 yet. I think there's an implicit assumption that the API surface is somewhat unstable and no one is forced to update. 

>Exposing the configs also mean that users now have to know which property belongs to which config instead of just looking at what's directly available in the `CalendarView` class.

I don't think having some of these grouped into methods affects discoverability at all. They would exist on `CalendarView` at the same level as the properties. In fact, if you're like me and like to pull up the autocomplete menu on a symbol, if might _help_ because the api is more concise/focused.

Thanks again for taking the time to go through these issues with me I know I've made a bunch recently lol.

**Comment by luis-cortes** [comment]
One more thing, there's an established convention of setting properties like `margin` and `padding` via a single function and the current implementation of `CalendarView` goes against that.

**Comment by kizitonwose** [comment]
> So if I understand correctly, breaking things apart and eliminating the properties would eliminate the need for the flags altogether no? 

Yep, but then if you want to change a single property in a group, you have to provide other members of the group. Imagine if we had, for example, `dayBinder`, `monthHeaderBinder` and `monthFooterBinder` in one group, so for you to change the `dayBinder`, you have to provide both `monthHeaderBinder` and `monthFooterBinder`. Of course, we may still provide default method args in this case but still, it would be someone unintuitive for this case. I do agree that some properties like day height and width can definitely be grouped.

> Regardless of whether the configuration is accessed via a property of or as a parameter of a function, outright removal would be a breaking change. So I don't think there's any value in keeping them as properties for the sake of API stability.

Fair, I guess I just need to find the balance on what could be properly grouped. Maybe I'll provide the suggested `update` API and then rethink the grouping.

> One more thing, there's an established convention of setting properties like margin and padding via a single function and the current implementation of CalendarView goes against that.

Really? Because I have never found that to be the case from a usage standpoint. I mostly see the pattern where margins can be set independently but also there's a `setMargin()` method that sets everything to a single value if needed(this is missing from in CalendarView though).

**Comment by luis-cortes** [comment]
>Imagine if we had, for example, dayBinder, monthHeaderBinder and monthFooterBinder in one group, so for you to change the dayBinder, you have to provide both monthHeaderBinder and monthFooterBinder

Not if we use the approach from above 🙂
`monthConfig.copy(any month config fields that changed)` 
This will take an existing `MonthConfig` and create a copy changing _only_ the properties the user supplied and leaving the rest unchanged.

>there's a setMargin() method that sets everything to a single value if needed(this is missing from in CalendarView though)

`MarginLayoutParams` has:
* `setMargins(int left, int top, int right, int bottom)` 
* `setMarginsRelative(int start, int top, int end, int bottom)` 
* Individual setters and getters for each 

`View` has: 
* `setPadding(int left, int top, int right, int bottom)` 
* `setPaddingRelative(int left, int top, int right, int bottom)` 

I think I have seen a method that allows you to set all of the margins to a single value but these exist as well.

**Comment by kizitonwose** [comment]
Okay, so I want to start with grouping the methods that directly cause a creating of `MonthConfig` since I want to allow generating the dates in the background.

This is what it looks like presently:

```kotlin
fun updateMonthConfiguration(
    inDateStyle: InDateStyle = this.inDateStyle,
    outDateStyle: OutDateStyle = this.outDateStyle,
    maxRowCount: Int = this.maxRowCount,
    hasBoundaries: Boolean = this.hasBoundaries
) {

}
```

Does the method look like what you had in mind? Or were you thinking more in the direction of something like:

```kotlin
fun updateMonthConfiguration(config: MonthConfig) {

}
```

**Comment by luis-cortes** [comment]
The first one is what I had in mind. However, I think maybe we should start with some of the props that have more obvious groupings like padding, margin, and height/width.

Even doing just those would be a big win I think.
