### ISSUE TITLE
Problem with two calendars scrolling each other

### ISSUE THREAD

**Issue by VladimirVasic994** [kizitonwose/CalendarView#188]
Hello,

I have two calendars, one in week mode on fully expanded. When I try to scroll expanded one to the next month, week stays on the same month. How can I fix this?

This is XML code for week mode:
```
<com.kizitonwose.calendarview.CalendarView
                android:id="@+id/calendar_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/viewholder__day"
                app:cv_inDateStyle="firstMonth"
                app:cv_maxRowCount="1"
                app:cv_orientation="horizontal"
                app:cv_outDateStyle="endOfRow"
                app:cv_scrollMode="paged"
                app:cv_hasBoundaries="false"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/legend_layout" />
```

This is xml code for expanded:

```
<com.kizitonwose.calendarview.CalendarView
                android:id="@+id/calendar_view_expandable"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/viewholder__day"
                app:cv_inDateStyle="allMonths"
                app:cv_orientation="horizontal"
                app:cv_outDateStyle="endOfRow"
                app:cv_scrollMode="paged"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/legend_expandable_layout" />
```

**Comment by VladimirVasic994** [comment]
Also when I scroll the month view and check month scroll listeners, for week scroll listener I these values.

<img width="897" alt="Screen Shot 2020-07-23 at 8 56 45 AM" src="https://user-images.githubusercontent.com/45670840/88259481-ac05bb80-ccc2-11ea-8e48-43e66c600fc3.png">

**Comment by kizitonwose** [comment]
> When I try to scroll expanded one to the next month, week stays on the same month. How can I fix this?

The two calendars don't know about each other so can't scroll together. It's up to you to manually trigger a scroll. Also, a visual representation of this issue would be nice so I can further understand what's going on.

---

> Also when I scroll the month view and check month scroll listeners, for week scroll listener I these values.

This is because you have `app:cv_hasBoundaries="false"`, please see the comment on the README about this.

**Comment by VladimirVasic994** [comment]
@kizitonwose 

I did manually set scroll listeners to work together, now the only problem I have is that I want when I scroll to next month, my week calendar to follow, but I also need to have no boundaries since I don't want my outDates and first dates of next month to repeat.

I did and I get it, but when I set it to true, I get first dates in the wrong place, and secondly, when scrolling to next date in scroll view I see outDates and then those same dates for the next week but in the wrong place

**Comment by kizitonwose** [comment]
Are you trying to sync the month view with the week view or the other way round? Can I see a sketch?

**Comment by VladimirVasic994** [comment]
I'm trying to sync my week view to month view. My week view was first looking like this. 
```
<com.kizitonwose.calendarview.CalendarView
                android:id="@+id/calendar_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/viewholder__day"
                app:cv_inDateStyle="allMonths"
                app:cv_maxRowCount="1"
                app:cv_orientation="horizontal"
                app:cv_outDateStyle="endOfRow"
                app:cv_scrollMode="paged"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/legend_layout" />
```
But then I had this problem with my week view. It showed double of the same week.
<img width="286" alt="Screen Shot 2020-07-23 at 9 28 57 AM" src="https://user-images.githubusercontent.com/45670840/88262232-13723a00-ccc8-11ea-81a1-23680e0bfef5.png">

<img width="284" alt="Screen Shot 2020-07-23 at 9 29 11 AM" src="https://user-images.githubusercontent.com/45670840/88262234-14a36700-ccc8-11ea-8c04-cc30ad843d3d.png">

But then I changed it to match your example one and then I started having this problem with scrolling sync with month view, because my yearMonth doesn't change.

**Comment by VladimirVasic994** [comment]
@kizitonwose 

So actually if there is a way for me to handle situations where week repeats itself in week mode that would solve my problem.

**Comment by kizitonwose** [comment]
If you need to use the `YearMonth` value with no boundaries set, you can get it from any of the `calendarDay` values in the `CalendarMonth` class.

```kotlin
calendarView.monthScrollListener = {
    val month = it.weekDays.first().first().date.yearMonth
}
```

**Comment by kizitonwose** [comment]
Closing this now, let me know if you still need help.
