### ISSUE TITLE
CalendarView entity in layout file not being processed properly

### ISSUE THREAD

**Issue by acutetech** [kizitonwose/CalendarView#19]
I have this Java code (in an AppCompatActivity class) and a layout file which works fine in a simple example, but fails when I try to add the CalendarView to a larger existing app:

        CalendarView cv;
        cv = findViewById(R.id.calendarView);
        // then initialise the CalendarView 

and a layout file with this:

    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/calendarView"
        ... />

I have an error in the java file "Type parameter T has incompatible upper bounds : View and CalendarView"

Explicitly casting: CalendarView calendarView = (CalendarView) findViewById(R.id.calendarView);
the error becomes "Inconvertable types: cannot cast 'android.view.View' to  'com.kizitonwose.calendarview.CalendarView'

It seems that somehow the CalendarView entity in the layout file is being treated as something else.

Interestingly, I cannot refactor/rename "@+id/calendarView" as the Refactor operation is greyed out. (I can refactor it if I change the XML to <CalendarView...) - is this a clue? Does it imply that the layout file is not being properly processed? 

If I right-click on R.id.calendarView and click "Go to Declaration" I am correctly taken to the layout file. I appear to have added the library dependency correctly to build.gradle. No amount of cleaning or invalidating of caches have effects. I deleted the .gradle, build and app/build directories - no change.

What is happening and how do I fix it?

**Comment by kizitonwose** [comment]
Have you migrated to AndroidX yet?

**Comment by acutetech** [comment]
Yes, refactored to AndroidX, latest Gradle etc, AFAIK

**Comment by kizitonwose** [comment]
Okay, try explicitly adding a dependency for recyclerview to your app level `build.gradle` and see if that fixes it.
`implementation 'androidx.recyclerview:recyclerview:1.1.0-alpha06'`

**Comment by kizitonwose** [comment]
Also, are you on the latest version [0.2.0](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.0) which has some fixes?

**Comment by acutetech** [comment]
Hi Kizito. Thanks for this. I tried both of your suggestions: the addition of the recyclerview dependency fixed the problem. (I had been using 0.1.2 but change to 0.2.0 did not fix the problem).

I guess you will update the readme.MD to include this advice.

**Comment by kizitonwose** [comment]
I have figured this out. If you clean your Gradle cache now and resync version `0.2.0` you'll see that this is now resolved. You can continue using your workaround if you don't want to clean your Gradle cache. I guess this issue was not raised earlier because many projects already have RecyclerView dependency, including the sample project.

Will close this issue now.
