### ISSUE TITLE
Calendar sometimes scrolls to first month, on visibility change.

### ISSUE THREAD

**Issue by slobodanantonijevic** [kizitonwose/CalendarView#190]
Pretty basic setup, and when I toggle calendar visibility, the calendar sometimes scrolls to first month. It is just random. At first I thought it was some action on my end, and I've debugged it thoroughly, and followed the flow, nothing special apart from visibility change from gone to visible, and calendar just jumps to the first month set instead of staying at currently set month.

**Comment by kizitonwose** [comment]
Kindly try reproducing this with one of the examples so I can look into it.

**Comment by hikkidev** [comment]
@kizitonwose 
I see a similar problem since version 0.3.4, only when switching calendar modes from month to week and back.

In your example, switching is also reproduced, just try to quickly and for a long time switch calendar modes.
As a result, `binding.exOneCalendar.monthScrollListener` returns the month of the beginning of the calendar `binding.exOneCalendar.setup (startMonth)`.

**Comment by hikkidev** [comment]
In my application, the delay between clicks is 650 ms, and the duration of animation (folding/unfolding) the calendar is 200 ms, so this is not due to the incorrect cancellation of the animation.

**Comment by hikkidev** [comment]
I looked around the library code a bit and the method `findVisibleMonthPosition` sometimes returns 0.
```

private fun findVisibleMonthPosition(isFirst: Boolean): Int {
        val visibleItemPos = if (isFirst) layoutManager.findFirstVisibleItemPosition() else layoutManager.findLastVisibleItemPosition()
        println("findVisibleMonthPosition = $visibleItemPos")
       ...
}

6 - Month mode
26 - Week mode

calendarviewsample I/System.out: findVisibleMonthPosition = 6
calendarviewsample I/System.out: findVisibleMonthPosition = 26
calendarviewsample I/System.out: findVisibleMonthPosition = 0
calendarviewsample I/System.out: findVisibleMonthPosition = 26
calendarviewsample I/System.out: findVisibleMonthPosition = 6
calendarviewsample I/System.out: findVisibleMonthPosition = 26
```

**Comment by kizitonwose** [comment]
@hikkidev I think I see how this could happen. Could you try using the new `updateMonthConfiguration()` method to update all configs at the same time and see if this still happens? 

Something like this:

```kotlin
val monthToWeek = monthViewCheckBox.isChecked
if (monthToWeek) { 
    // One row calendar for week mode
    calendarView.updateMonthConfiguration(
        inDateStyle = InDateStyle.ALL_MONTHS,
        maxRowCount = 1,
        hasBoundaries = false
    )
} else {
    // Six row calendar for month mode
    calendarView.updateMonthConfiguration(
        inDateStyle = InDateStyle.FIRST_MONTH,
        maxRowCount = 6,
        hasBoundaries = true
    )
}
```

**Comment by hikkidev** [comment]
@kizitonwose i already use it.
```kotlin
    private fun CalendarView.applyWeekMode() {
        updateMonthConfiguration(
                inDateStyle = InDateStyle.FIRST_MONTH,
                maxRowCount = 1,
                hasBoundaries = false
        )
    }

    private fun CalendarView.applyMonthMode() {
        updateMonthConfiguration(
                inDateStyle = InDateStyle.ALL_MONTHS,
                maxRowCount = maxWeekPerPage,
                hasBoundaries = true
        )
    }
```

**Comment by kizitonwose** [comment]
Interesting, I'll investigate this when I find some time and will report back.

**Comment by hikkidev** [comment]
@kizitonwose thanks

**Comment by kizitonwose** [comment]
I tried toggling the checkbox in Example 1 repeatedly and the best I could get was an animation-related crash. I think an easy workaround for this would be to disable the checkbox before starting the animation and enabling it afterward.

```Kotlin
binding.weekModeCheckBox.setOnCheckedChangeListener { checkBox, monthToWeek ->
    animator.doOnStart {
        checkBox.isEnabled = false
        // Other logic
    }
    animator.doOnEnd {
        checkBox.isEnabled = true 
        // Other logic
    }
}
```
