### ISSUE TITLE
Java Doc

### ISSUE THREAD

**Issue by liming8964** [kizitonwose/CalendarView#195]
I am using this library in Java android application.
I want Java manual documents for using this library.
Can you help me?
Best regards.

**Comment by kizitonwose** [comment]
Have you tried this plugin: https://plugins.jetbrains.com/plugin/7157-javadoc

**Comment by liming8964** [comment]
Create your view container which acts as a view holder for each date cell. The view passed in here is the inflated day view resource which you provided.

class DayViewContainer(view: View) : ViewContainer(view) {    
    val textView = view.findViewById<TextView>(R.id.calendarDayText)

    // With ViewBinding
    // val textView = CalendarDayLayoutBinding.bind(view).calendarDayText
}
Provide a DayBinder for the CalendarView using your DayViewContainer type.

calendarView.dayBinder = object : DayBinder<DayViewContainer> {
    // Called only when a new container is needed.
    override fun create(view: View) = DayViewContainer(view)
    
    // Called every time we need to reuse a container.
    override fun bind(container: DayViewContainer, day: CalendarDay) {
        container.textView.text = day.date.dayOfMonth.toString()
    }
}

Can you give me the java code of this kotlin part?

**Comment by kizitonwose** [comment]
```Java
class DayViewContainer extends ViewContainer {
    final TextView textView;

    public DayViewContainer(@NotNull View view) {
        super(view);
        textView = view.findViewById(R.id.calendarDayText);
    }
}

class ExampleFragment extends Fragment {
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        
        final CalendarView calendarView = view.findViewById(R.id.calendarView);
        calendarView.setDayBinder(new DayBinder<DayViewContainer>() {
            @NotNull
            @Override
            public DayViewContainer create(@NotNull View view) {
                return new DayViewContainer(view);
            }

            @Override
            public void bind(@NotNull DayViewContainer container, @NotNull CalendarDay day) {
                container.textView.setText(String.valueOf(day.getDate().getDayOfMonth()));
            }
        });
    }
}
```

**Comment by sherwin14** [comment]
> ```java
> setDayBinder
> ```

Hi @kizitonwose, the setDayBinder() in version 1.0.4 seems removed..

Here is the screenshot.
![image](https://user-images.githubusercontent.com/6423143/126443597-a3b0c803-df4e-415d-b9b6-958bea5aa3d8.png)
