### ISSUE TITLE
Support gestures

### ISSUE THREAD

**Issue by hikkidev** [kizitonwose/CalendarView#196]
Hey i am using horizontal expandable calendar.  I want to add the action to collapse / expand the calendar vertically via fling. How can I best implement this?  Inherit from your calendar and override touch handling methods, or there is another option?

**Comment by kizitonwose** [comment]
Actually, RecyclerView has a method `setOnFlingListener()` which may be useful here. Otherwise, there's another method `addOnItemTouchListener()` which lets you handle touch events in a cleaner way. If you don't get your desired result from these, then, of course, you can extend the class.

**Comment by kizitonwose** [comment]
I assume you found what worked best for your use case 🤞
