### ISSUE TITLE
Scroll back to 6 rows month

### ISSUE THREAD

**Issue by Simone90** [kizitonwose/CalendarView#197]
Hi.
I have a problem when I scroll back to a full 6 rows month, for example from September 2020 to August 2020.
Inside the monthScrollListener calling findLastVisibleDay() I get the 30th of August, instead of 6th of September.
This is the parameters of the CalendarView
            app:cv_outDateStyle="endOfRow"
            app:cv_inDateStyle="allMonths"
            app:cv_scrollMode="paged"
            app:cv_maxRowCount="6"

Am I missing something?
Thanks a lot!

**Comment by kizitonwose** [comment]
I think you're getting an `inDate`, which is correct. Please check `owner` property of the returned `CalendarDay` before using it.

<img src="https://raw.githubusercontent.com/kizitonwose/CalendarView/master/images/screenshot_in_out_dates.png" alt="inDate and outDates" width="300">

Using the above image as an example, if you query the calendar for the first visible date, you'll get 29th of the previous month.
