### ISSUE TITLE
When calling monthScrollListener , and I update a textView in  my layout , the calanderView Reload 

### ISSUE THREAD

**Issue by yosrabrahem07** [kizitonwose/CalendarView#198]
Here how I'm using the scroll Listner

        weekMonthCalendar.monthScrollListener = {
                monthDateTv.text =    it.yearMonth.toString() // if I comment this line , the calendar don't reload
        }

**Comment by jmuseyibli** [comment]
I also have this exact problem. @yosrabrahem07 did you find any workarounds?

**Comment by kizitonwose** [comment]
Please, could you further explain the phrase `the calanderView Reloads`? Does it blink? How do you know it reloads? I don't see how this is possible.

**Comment by jmuseyibli** [comment]
@kizitonwose Yes, it blinks. I found a workaround by setting itemAnimator to null.

**Comment by kizitonwose** [comment]
We've had issues with the item animator in the past, I'm beginning to think we should have it disabled by default. I assume not a lot of people use custom animators for a calendar.

**Comment by kizitonwose** [comment]
I'll close this for now and consider what the next steps would be regarding the animator thing.
