### ISSUE TITLE
Toggling between Week mode and Month mode does not redraw days

### ISSUE THREAD

**Issue by thirstycoda** [kizitonwose/CalendarView#199]
Thanks for creating this library. It is exactly what I need!

Whilst using it, I have noticed an issue which I was hoping you could help with.

Using Example1 of the samples, change line 52 of Example1Fragment.kt to: 
`val startMonth = YearMonth.of(2020, 8)`

Run the example, enable week mode then disable week mode. The title is renamed to reflect the change in mode but the calendar is not redrawn to show all dates in the month. Instead it remains as it did when week mode was enabled

**Comment by kizitonwose** [comment]
This is now fixed in [0.4.3](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.3)

**Comment by thirstycoda** [comment]
Works perfectly! Thanks for your help
