### ISSUE TITLE
How to show single date selection?

### ISSUE THREAD

**Issue by rohitsinglailluminz** [kizitonwose/CalendarView#204]
Hi @kizitonwose , i want single date selection.
Previous selected date should also be updated to unselected.
Could you suggest me how to do it ?

**Comment by kizitonwose** [comment]
See [Example 2](https://github.com/kizitonwose/CalendarView/blob/master/sample/src/main/java/com/kizitonwose/calendarviewsample/Example2Fragment.kt)
