### ISSUE TITLE
Margin's trap

### ISSUE THREAD

**Issue by CeH9** [kizitonwose/CalendarView#213]
Hi, thx for awesome lib. I spent few hours in "profiling perfomance adventure" until reliazed that problem is in **android:margins** which cause invalidating.
Imho, in readme should be warning that users should prefer special API (**setMonthPadding**, **setMonthMargins**) instead of default ones.

**Comment by kizitonwose** [comment]
`android:margins` are applied on the entire view but month margins are applied on each item view. These are two different things.
