### ISSUE TITLE
Build problem 

### ISSUE THREAD

**Issue by ExileExodus** [kizitonwose/CalendarView#214]
@kizitonwose 
I followed the provided steps but I keep getting this error:
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.kizitonwose:CalendarView
Screenshots may make it more clear.
![error](https://user-images.githubusercontent.com/29422808/93030944-a9bf3e00-f62f-11ea-9bc6-3845c85f8023.PNG)
![error2](https://user-images.githubusercontent.com/29422808/93030965-c78ca300-f62f-11ea-9b05-ef849da32dc2.PNG)
I clicked the link in the second screenshot(https://jitpack.io/com/github/kizitonwose/CalendarView/%3Clatest-version%3E/CalendarView-%3Clatest-version%3E.pom)
Yet it leads to a blank page with Invalid version: %3Clatest-version%3E

**Comment by kizitonwose** [comment]
Could you try this again now?

**Comment by kizitonwose** [comment]
Seems like an issue with Jitpack at the time.

**Comment by ExileExodus** [comment]
I tried again but its the same error.

**Comment by ExileExodus** [comment]
Okay I solved it had to replace implementation 'com.github.kizitonwose:CalendarView:<latest-version>' with
implementation 'com.github.kizitonwose:CalendarView:0.4.3'
Thanks anyway.
