### ISSUE TITLE
android.view.InflateException: Error inflating class com.kizitonwose.calendarview.CalendarView

### ISSUE THREAD

**Issue by ruhamadavid** [kizitonwose/CalendarView#215]
I have tried to use Calendar view library in my application but I’m getting following exception. I’m unable to bind my layout : 
android.view.InflateException: Binary XML file line #62: Binary XML file line #62: Error inflating class com.kizitonwose.calendarview.CalendarView

Here is my java code:

package com.vlogic.VLScheduler;

import android.app.Activity;
import android.os.Bundle;

public class CalendarView extends Activity {

    com.kizitonwose.calendarview.CalendarView calendarView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_calendar_view);
        calendarView = findViewById(R.id.calendarView );
    }
}

And my xml looks like:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/example_5_page_bg_color"
    android:clickable="true"
    android:focusable="true"
    android:orientation="vertical">

        <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/calendarView "
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
</LinearLayout>

**Comment by kizitonwose** [comment]
Please share the actual exception.

**Comment by kizitonwose** [comment]
Also: Device name and Android version may be useful.
