### ISSUE TITLE
Feature request: 31x1 calendar view

### ISSUE THREAD

**Issue by acutetech** [kizitonwose/CalendarView#22]
Thank you very much for this library. It is very useful.This is a request for a further development, and/or suggestions for how I might try to make the development myself.

My application monitors medication adherence. I issue reminders to take medication and I record when the user takes their medication. I display information about when medication is taken, or missed. So your calendar is useful for this. But a different view would be good.

Adherence is best displayed graphically, so stakeholders can see at a glance when and whether the user took their medication, over (say) a month. Figure 5 at this paper shows the idea: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3403197/pdf/bcp0073-0691.pdf - a version of my own app looks like this: https://www.dropbox.com/s/dyvdxjozmh3jwdb/Screenshot_20190625-220402_Medication%20Monitor.jpg?dl=0

So the ideal would be a CalendarView that has days of the month (1...31) on the X axis and time of the day (00:00- 23:59) on the Y axis. The actual time that medication was taken would be displayed as a dot at the correct X/Y position. Colour-coding can show status (e.g. taken on time, taken at the wrong time, not taken etc).

I would think that the existing library could be adapted reasonably well:

- days would be displayed as cells arranged in a 31x1 array instead of a 7x6 array.

- the calendar views (one per month) can scroll left and right as happens at present.

- The day of week legend (MON, TUE, WED...) might need to be replaced by days (1...31) or perhaps week numbers (across 7 days).

- each day cell (narrow and long) needs to be painted with data: background colour to indicate status and small shapes (circles, squares) rendered to indicate the actual data point. One approach might be to divide each day cell into 24, 48 or 96 divisions that correspond to 60, 30 or 15 minute time slots. Each sub-cell could have different background colours and different drawable shapes painted to indicate data points. Or perhaps horizontal bands of colour and drawable items could be placed programmatically: looking at the sample app Example 5, I see the  "@+id/exFiveDayFlightTop" and "@+id/exFiveDayFlightBottom" views might be positioned differently by changing the layout_marginBottom parameter.

- There might need to be a provision to add vertical (1 pixel) dividers to divide each week (7 days).

- Perhaps the horizontal scale could be for 1 week rather than one month.

What do you think? What might need to be changed? Does the "week view" facility already provide this facility, if we can display 31 days instead of 7?

**Comment by acutetech** [comment]
I have made reasonable progress on this, and the output of an example can be seen here:

https://www.dropbox.com/s/2bzzxpvuepld8oy/Screenshot_20190627-184904_CalendarView%20Sample.jpg?dl=0

Most of the required behaviour seems to already be available in the library. I have pushed the week view mode to display 31 days rather than 7, then extended the height of the day container. The example simulates three time events for each day. For each data point I programmatically create one new TextView, and place a drawable image (a dot) inside the TextView and a position it a distance from the bottom which represents the time (in minutes) that the event occurred. Then I add the TextView into a FrameView which is superimposed on the day container.

I can provide the Java source on request, and would be honoured if you would like to add it to the sample app: it is structured as an 8th Example.

TODO: check the day-of-week text (M, T, W, T, F, S, S) which may be wrongly positioned.
Check and correct the calendar scrolling: not sure we get the callbacks at the right time.
Improve display - e.g. borders between weeks and/or months.
Add a vertical axis on the left of the screen to indicate the hours of the day (00 - 23/24)
Dynamically adjust the size of the text for the day of the month and day of the week.
Improve efficiency?
Add the option to draw horizontal bands and/or line across the chart (in my application these are target times for the events to occur).

**Comment by kizitonwose** [comment]
This seems out of scope for what the library is meant to do. Btw, why would you want to fit 31 days horizontally? How would that look on small-screen devices? Also, note that not all months have 31 days, how do you handle that? 
I'm not sure I understand the requested feature. Maybe you can clarify.

**Comment by kizitonwose** [comment]
Guess I can close this as it's out of scope.

**Comment by acutetech** [comment]
Hi Kizito
Sorry - I have been so busy and did not respond to your request for clarification. I do accept that it seems probably out of scope. However I do have a real application which I need to solve somehow - either with a variation of your library or else (perhaps more logically) with a charting library.

My application is monitoring when people take their medication. Typically a user should take their medication within a certain time band each day, so the time of day is significant as well as the day itself. I have developed two views on the data set. The first one uses your calendar in a mainstream way. I can add decoration to each day in the calendar to show whether the user took their medication correctly on that day, or not. In the second case I can drill down into the data to show the time(s) during the day at which the medication was taken. This second view uses the "31x1" view, with the X axis being the date and the Y axis being the time of the day at which the event occurred. You could think of the "31x1" view as being a time-series chart, or a calendar which shows time of day data as well as just days.

Theses two screen shots show the two views. As you see I have achieved most of what I need in view 2. Further enhancements would include adding a scale on the LHS etc. You can argue that a charting library would be more appropriate, rather than pressing the calendar library to extremes. But maybe you think there is something useful here...

View 1: https://www.dropbox.com/s/eiuwf4zl4cqrjhb/view_1.jpg?dl=0
View 2: https://www.dropbox.com/s/5l1re8kst6nyt6j/view_2.jpg?dl=0
