### ISSUE TITLE
findFirstVisibleMonth().month returns startMonth value when hasBoundaries==false.

### ISSUE THREAD

**Issue by Jeevuz** [kizitonwose/CalendarView#221]
Hi @kizitonwose,
I have an issue that findFirstVisibleMonth() in unbounded mode (1 week style) is always returns CalendarMonth with yearMonth set to the first month in all months range. 
I found the source of this at https://github.com/kizitonwose/CalendarView/blob/38983c8d30d1245e4af44cec22316235f9c2c541/library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt#L168

Could you please tell me is it intentionally or I can create PR with the following change?: 
```kotlin
CalendarMonth(
  monthWeeks.first().first().date.yearMonth, // First day found in weeks determines the month. 
  monthWeeks, 
  calendarMonths.size, 
  calMonthsCount
) 
```
It will be much more convenient for use I think. And findFirstVisibleMonth().month will return the closer possible result to what it name says.

What you think?

**Comment by kizitonwose** [comment]
This is intentional and mentioned in the [Readme](https://github.com/kizitonwose/CalendarView#faq). The reason is that while the first day could determine the month in some cases, there could be multiple months sometimes so a more correct implementation when `hasBoundaries = false` would be an array of months.

**Comment by Jeevuz** [comment]
Ok I got it, thanks! But it was really painful to discover it in the hard way. I think I'm not the one not reading the readme in front :) 
I think it would be great to add this explanation in the doc of the findFirstVisibleMont() and the MonthScrollListener.

**Comment by Jeevuz** [comment]
I even think maybe CalendarMonth can be a CalendarPeriod with isFullMonth method. It will be closer to the truth because in many cases we don't have full month in CalendarMonth so it is rather period than month. 
Thinking out loud. I know how hard to maintain the library is ;)
