### ISSUE TITLE
Set specific date range

### ISSUE THREAD

**Issue by shihabmi7** [kizitonwose/CalendarView#222]
I want to set a specific date range like from today, 27-09-2020 to 30 days later  27-10-2020. So, the User will not capable to select the rest of the days in these two months. 

I can set the month range as below.

```        
val currentMonth = YearMonth.now()
val endMonth = currentMonth.plusMonths(0)
val dayOfWeek = daysOfWeek.first()
kizitoneCalander.exFourCalendar.setup(currentMonth, endMonth, dayOfWeek)`
```

**Comment by kizitonwose** [comment]
You can't set specific dates, but you can disable those dates so they are not selectable.

**Comment by mohmdlabeeb** [comment]
how do i disable those dates?

**Comment by kizitonwose** [comment]
@mohmdlabeeb See the sample projects.
