### ISSUE TITLE
Show only specific number of weeks within months

### ISSUE THREAD

**Issue by OneEarthling** [kizitonwose/CalendarView#223]
Hi! I followed your instructions in issue #166 and it works nice within month range. However when date are between month (for example 30 September - 9 November) it looks not so good like on the image below. So I want only show weeks with range of dates in it with no spaces. Do you have any ideas how to do so?

![image](https://user-images.githubusercontent.com/48918578/94562180-aeaa0180-026d-11eb-8afb-e744c6b3362a.png)

    fun configureCalendar(startMonth: Date, endMonth: Date) {
        // calculating week's diff
        val calendar1 = Calendar.getInstance()
        val calendar2 = Calendar.getInstance()
        calendar1.firstDayOfWeek = Calendar.MONDAY
        calendar2.firstDayOfWeek = Calendar.MONDAY
        calendar1.time = startMonth
        calendar2.time = endMonth
        selectedDate = startMonth.toLocalDate()
        val currentMonthShow = YearMonth.of(startMonth.dateYear(), startMonth.dateMonth() + 1)
        val endMonthShow = YearMonth.of(endMonth.dateYear(), endMonth.dateMonth() + 1)
        programmCalendar.setup(currentMonthShow, endMonthShow, DayOfWeek.MONDAY)
        // finding range of weeks to show
        val weekOfYear = WeekFields.of(Locale("ru")).weekOfWeekBasedYear()
        val validRange = (startMonth.toLocalDate().get(weekOfYear).rangeTo(endMonth.toLocalDate().get(weekOfYear)))

        class DayViewContainer(view: View) : ViewContainer(view) {
            lateinit var day: CalendarDay
            val textView = view.findViewById<TextView>(R.id.dayText)
            val dotView = view.findViewById<View>(R.id.dotView)
            init {
                view.setOnClickListener {
                    if (day.owner == DayOwner.THIS_MONTH) {
                        selectDate(day.date)
                    }
                }
            }
        }

        programmCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) {
                container.day = day
                val compareDate = Calendar.getInstance()
                compareDate.set(day.date.year, day.date.monthValue - 1, day.date.dayOfMonth)
                val textView = container.textView
                val dotView = container.dotView
                val parent = textView.parent as View
                textView.text = day.date.dayOfMonth.toString()
                if (day.owner == DayOwner.THIS_MONTH) {
                    parent.visibility = when {
                        day.date.get(weekOfYear) !in validRange -> View.GONE
                        else -> View.VISIBLE
                    }
                    when (day.date) {
                        selectedDate -> {
                            textView.setTextColorRes(R.color.ks_white)
                            textView.setBackgroundResource(R.drawable.selected_day)
                        }
                        else -> {
                            if (calendar1.time.getZeroTimeDate() <= compareDate.time.getZeroTimeDate() && calendar2.time.getZeroTimeDate() >= compareDate.time.getZeroTimeDate()) {
                                dotView.visibility = View.VISIBLE
                            } else {
                                dotView.visibility = View.INVISIBLE
                            }
                            textView.background = null
                            textView.setTextColorRes(R.color.ks_font_title_chat)
                        }
                    }
                } else {
                    parent.visibility = when {
                        day.date.get(weekOfYear) in validRange -> View.INVISIBLE
                        else -> View.GONE
                    }
                    textView.visibility = View.INVISIBLE
                    dotView.visibility = View.INVISIBLE
                }
            }
        }

**Comment by OneEarthling** [comment]
I am trying to use horizontal orientation now; it looks good sometimes but there is another problem. When dividing weeks into the numbers of weeks that I want it devides whole month into parts I guess and calendar looks like this
I'm sure I miss something
![image](https://user-images.githubusercontent.com/48918578/94659305-bec4ee00-030c-11eb-93c7-d3b6d02cc4e6.png)
Need to scroll to see the rest
![image](https://user-images.githubusercontent.com/48918578/94659328-c71d2900-030c-11eb-9212-bc588a866884.png)

        fun configureCalendar(startMonth: Date, endMonth: Date) {
        // calculating week's diff
        val calendar1 = Calendar.getInstance()
        val calendar2 = Calendar.getInstance()
        calendar1.firstDayOfWeek = Calendar.MONDAY
        calendar2.firstDayOfWeek = Calendar.MONDAY
        calendar1.time = startMonth
        calendar2.time = endMonth
        selectedDate = startMonth.toLocalDate()
        val calendarWeekDifference = abs(calendar2.get(Calendar.WEEK_OF_YEAR) - calendar1.get(Calendar.WEEK_OF_YEAR))+1

        val currentMonthShow = YearMonth.of(startMonth.dateYear(), startMonth.dateMonth() + 1)
        val endMonthShow = YearMonth.of(endMonth.dateYear(), endMonth.dateMonth() + 1)
        programmCalendar.updateMonthConfiguration(
            maxRowCount = calendarWeekDifference,
            hasBoundaries = false)
        programmCalendar.setup(currentMonthShow, endMonthShow, DayOfWeek.MONDAY)
        // finding range of weeks to show
        val weekOfYear = WeekFields.of(Locale("ru")).weekOfWeekBasedYear()
        val validRange = (startMonth.toLocalDate().get(weekOfYear).rangeTo(
            endMonth.toLocalDate().get(
                weekOfYear
            )
        ))

        class DayViewContainer(view: View) : ViewContainer(view) {
            lateinit var day: CalendarDay
            val textView = view.findViewById<TextView>(R.id.dayText)
            val dotView = view.findViewById<View>(R.id.dotView)
            init {
                view.setOnClickListener {
                    if (day.owner == DayOwner.THIS_MONTH) {
                        selectDate(day.date)
                    }
                }
            }
        }

        programmCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) {
                container.day = day
                val compareDate = Calendar.getInstance()
                compareDate.set(day.date.year, day.date.monthValue - 1, day.date.dayOfMonth)
                val textView = container.textView
                val dotView = container.dotView
                val parent = textView.parent as View
                textView.text = day.date.dayOfMonth.toString()

                if (day.owner == DayOwner.THIS_MONTH) {
                    parent.visibility = when {
                        day.date.get(weekOfYear) !in validRange -> View.GONE // Set 'gone' to remove every date not in the last four weeks.
                        else -> View.VISIBLE
                    }
                    when (day.date) {
                        selectedDate -> {
                            textView.setTextColorRes(R.color.ks_white)
                            textView.setBackgroundResource(R.drawable.selected_day)
                        }
                        else -> {
                            if (calendar1.time.getZeroTimeDate() <= compareDate.time.getZeroTimeDate() && calendar2.time.getZeroTimeDate() >= compareDate.time.getZeroTimeDate()) {
                                dotView.visibility = View.VISIBLE
                            } else {
                                dotView.visibility = View.INVISIBLE
                            }
                            textView.background = null
                            textView.setTextColorRes(R.color.ks_font_title_chat)
                        }
                    }
                } else {
                    parent.visibility = when {
                        day.date.get(weekOfYear) in validRange -> View.GONE // Set 'invicible' to keep the space for indates.
                        else -> View.GONE
                    }
                }

            }
        }
    }
        

<com.kizitonwose.calendarview.CalendarView
                android:id="@+id/programmCalendar"
                android:background="@color/ks_calendar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_orientation="horizontal"
                app:cv_outDateStyle="endOfRow"
                app:cv_inDateStyle="allMonths"
                app:cv_scrollMode="paged"
                app:cv_dayViewResource="@layout/calendar_day_layout"/>

**Comment by kizitonwose** [comment]
Sorry for the late response but this feature is not officially supported by the library and I don't want to put in a lot of time into "hacking" it.

**Comment by kizitonwose** [comment]
I'll close this.
