### ISSUE TITLE
The position of the day text is not precise after updating to version 0.4.4

### ISSUE THREAD

**Issue by nurrahmat** [kizitonwose/CalendarView#224]
Hi 
This calendarview library is great because it is highly customizable. but i found a bug after update to 0.4.4. calendar day text not precision in dialog mode.

In version 0.4.3 day text in calendarview dialog looks good as below :
![image](https://user-images.githubusercontent.com/25714507/94675835-8fca6e80-0344-11eb-8a5f-6a6bd4169193.png)

but in version 0.4.4 day text in calendarview dialog looks not precision :
![image](https://user-images.githubusercontent.com/25714507/94675498-074bce00-0344-11eb-81f1-1acaf6271ef8.png)

Here is my calendarview dialog in Activity:

        val mDialogView = LayoutInflater.from(this)
            .inflate(R.layout.dialog_calendar, findViewById(android.R.id.content), false)
        val mBuilder = AlertDialog.Builder(this)
            .setView(mDialogView)
        mAlertDialogDate = mBuilder.show()
        mAlertDialogDate.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
        mDialogView.dialog_tv_ok.setOnClickListener {
            var oldDate = selectedDate

            /** Setup new Yearmonth into calendar_view **/
            if (selectedDateDialog != null) {
                val selectYearMonth =
                    YearMonth.of(selectedDateDialog?.year!!, selectedDateDialog?.month)
                exFiveCalendar.setup(
                    selectYearMonth.minusMonths(12),
                    selectYearMonth.plusMonths(12),
                    daysOfWeekFromLocale().first()
                )
                exFiveCalendar.scrollToMonth(selectYearMonth)

                /** Clear previous old date selected in calendar_view **/
                oldDate?.let {
                    oldDate = null
                    exFiveCalendar.notifyDateChanged(it)
                }

                /** Clear current date selected from dialog_calendar_view into calendar_view **/
                selectedDateDialog.let {
                    selectedDate = it
                    exFiveCalendar.notifyDateChanged(it!!)
                }

            }

            mAlertDialogDate.dismiss()
        }

        mDialogView.dialog_tv_cancel.setOnClickListener {
            mAlertDialogDate.dismiss()
        }

        /** Setup calendar **/
        mAlertDialogDate.dialog_calendar_view.setup(
            YearMonth.now().minusMonths(12),
            YearMonth.now().plusMonths(12),
            daysOfWeekFromLocale().first()
        )
        mAlertDialogDate.dialog_calendar_view.scrollToMonth(YearMonth.now())

        /** Binding day into TextView **/
        mAlertDialogDate.dialog_calendar_view.dayBinder =
            object : DayBinder<DialogDayViewContainer> {
                override fun create(view: View) = DialogDayViewContainer(view)
                override fun bind(container: DialogDayViewContainer, day: CalendarDay) {
                    container.day = day
                    val textView = container.binding.exFiveDayText
                    textView.text = day.date.dayOfMonth.toString()

                    if (day.owner == DayOwner.THIS_MONTH) {
                        if (selectedDateDialog == day.date)
                            textView.setTextColor(Color.WHITE)
                        else
                            textView.setTextColor(Color.BLACK)
                        textView.setBackgroundResource(
                            if (selectedDateDialog == day.date) {
                                R.drawable.example_4_single_selected_bg
                            } else 0
                        )
                    } else {
                        textView.setTextColor(Color.GRAY)
                        textView.background = null
                    }
                }
            }

        /** Binding day_name_item_layout **/
        class MonthViewContainer(view: View) : ViewContainer(view) {
            val legendLayout = CalendarHeaderBinding.bind(view).legendLayout.root
        }

        /** Binding dayName into layout **/
        mAlertDialogDate.dialog_calendar_view.monthHeaderBinder = object :
            MonthHeaderFooterBinder<MonthViewContainer> {
            override fun create(view: View) = MonthViewContainer(view)
            override fun bind(container: MonthViewContainer, month: CalendarMonth) {
                /** Setup each header day text if we have not done that already. **/
                if (container.legendLayout.tag == null) {
                    container.legendLayout.tag = month.yearMonth
                    container.legendLayout.children.map { it as TextView }
                        .forEachIndexed { index, tv ->
                            tv.text = daysOfWeekFromLocale()[index].getDisplayName(
                                TextStyle.SHORT,
                                Locale("id", "ID")
                            ).toUpperCase(Locale("id", "ID"))
                            tv.setTextSize(TypedValue.COMPLEX_UNIT_SP, 12f)
                        }
                    month.yearMonth
                }
            }
        }
   
Here is my calendarview dialog in xml:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/dialog_background_inset_2"
    android:orientation="vertical"
    android:paddingStart="36dp"
    android:paddingTop="50dp"
    android:paddingEnd="36dp"
    android:paddingBottom="50dp">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="14dp">

        <ImageView
            android:id="@+id/btn_previous_date"
            android:layout_width="36dp"
            android:layout_height="36dp"
            android:background="?attr/selectableItemBackgroundBorderless"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/ic_chevron_left_primary" />

        <TextView
            android:id="@+id/tv_month_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:fontFamily="sans-serif-medium"
            android:textSize="22dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toStartOf="@id/btn_next_date"
            app:layout_constraintStart_toEndOf="@id/btn_previous_date"
            app:layout_constraintTop_toTopOf="parent"
            tools:text="April 2018" />

        <ImageView
            android:id="@+id/btn_next_date"
            android:layout_width="36dp"
            android:layout_height="36dp"
            android:layout_marginEnd="22dp"
            android:background="?attr/selectableItemBackgroundBorderless"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/ic_chevron_right_primary" />

    </androidx.constraintlayout.widget.ConstraintLayout>

    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/dialog_calendar_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginTop="10dp"
        android:layout_weight="1"
        app:cv_dayViewResource="@layout/calendar_day"
        app:cv_monthHeaderResource="@layout/calendar_header"
        app:cv_orientation="horizontal"
        app:cv_outDateStyle="endOfGrid"
        app:cv_scrollMode="paged" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="end"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/dialog_tv_cancel"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="?attr/selectableItemBackground"
            android:clickable="true"
            android:focusable="true"
            android:padding="10dp"
            android:text="Cancel"
            android:textSize="14dp" />

        <TextView
            android:id="@+id/dialog_tv_ok"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginEnd="20dp"
            android:background="?attr/selectableItemBackground"
            android:clickable="true"
            android:focusable="true"
            android:paddingStart="20dp"
            android:paddingTop="10dp"
            android:paddingEnd="20dp"
            android:paddingBottom="10dp"
            android:text="OK"
            android:textColor="@color/colorPrimary"
            android:textSize="14dp" />

    </LinearLayout>

</LinearLayout>

My sample project test:
[KizitonwoseCalendarView.zip](https://github.com/kizitonwose/CalendarView/files/5304887/KizitonwoseCalendarView.zip)

 Please can you help me?

**Comment by kizitonwose** [comment]
Fixed in [0.4.5](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.5)

**Comment by nurrahmat** [comment]
> Fixed in [0.4.5](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.5)

Thanks @kizitonwose that's working fine
