### ISSUE TITLE
When clicking on a new date the previous clicked date decorator is still remaining there

### ISSUE THREAD

**Issue by ABr751** [kizitonwose/CalendarView#227]
Thanks for this library.... Is there a way to remove the previous clicked date decorator ? When I am clicking a new date the previous dates background is not changing

**Comment by ABr751** [comment]
Can anyone please help???

**Comment by kizitonwose** [comment]
The library does not handle decoration. You have to call `notifyDateChanged()` on the previous date and remove the decoration yourself.

**Comment by ABr751** [comment]
ok
