### ISSUE TITLE
Java code for week days

### ISSUE THREAD

**Issue by pawandeepka** [kizitonwose/CalendarView#229]
Hey, Please help to write code for week customization. How can I use this code in Java for week? I already add code but still not working.

**Please correct me where im lacking** 
Thanks

        WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);
        final DisplayMetrics dm = new DisplayMetrics();
        wm.getDefaultDisplay().getMetrics(dm);
        int dayWidth = dm.widthPixels / 7;
        int dayHeight = (int) ((double) dayWidth * 1.25D);
        exSevenCalendar.setDaySize(new Size(dayWidth, dayHeight));

        exSevenCalendar.setOnClickListener(view -> {

        });
        exSevenCalendar.setDayBinder(new DayBinder<DayViewContainer>() {
            @NotNull
            @Override
            public DayViewContainer create(@NotNull View view) {
                return new DayViewContainer(view);
            }

            @Override
            public void bind(@NotNull DayViewContainer container, @NotNull CalendarDay day) {
                container.bind(container, day);
            }
        });

        YearMonth currentMonth = YearMonth.now();
        // Value for firstDayOfWeek does not matter since inDates and outDates are not generated.
        exSevenCalendar.setup(currentMonth, currentMonth.plusMonths(3), DayOfWeek.MONDAY);
        exSevenCalendar.scrollToDate(LocalDate.now());

class DayViewContainer extends ViewContainer {

        private final View vView;
        public CalendarDay day;

        private DayViewContainer(@NotNull View view) {
            super(view);
            LayoutInflater inflater = (LayoutInflater) getApplicationContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            vView = inflater.inflate(R.layout.example_7_calendar_day, null);
            vView.setOnClickListener(view1 -> {
                CalendarDay firstDay = exSevenCalendar.findFirstVisibleDay();
                CalendarDay lastDay = exSevenCalendar.findLastVisibleDay();

                if (Intrinsics.areEqual(firstDay, day.getDay())) {
                    exSevenCalendar.smoothScrollToDate(day.getDate());
                } else if (Intrinsics.areEqual(lastDay, day.getDay())) {
                    exSevenCalendar.smoothScrollToDate(day.getDate().minusDays(4));
                }

                if (!Intrinsics.areEqual(selectedDate, day.getDate())) {
                    LocalDate oldDate = selectedDate;
                    selectedDate = day.getDate();
                    if (oldDate != null) {
                        exSevenCalendar.notifyCalendarChanged();
                    }
                }
            });
        }

        public void bind(DayViewContainer container, CalendarDay day) {
            this.day = day;

            TextView exSevenDateText = vView.findViewById(R.id.exSevenDateText);
            TextView exSevenDayText = vView.findViewById(R.id.exSevenDayText);
            TextView exSevenMonthText = vView.findViewById(R.id.exSevenMonthText);
            View exSevenSelectedView = vView.findViewById(R.id.exSevenSelectedView);

            exSevenDateText.setText(dateFormatter.format(day.getDate()));
            exSevenDayText.setText(dayFormatter.format(day.getDate()));
            exSevenMonthText.setText(monthFormatter.format(day.getDate()));

            exSevenDateText.setTextColor(getResources().getColor((day.getDate() == selectedDate) ? R.color.example_7_yellow : R.color.example_7_white));
            exSevenSelectedView.setVisibility(day.getDate().compareTo(selectedDate));
        }
    }

**Comment by kizitonwose** [comment]
I unfortunately don't know what you're doing wrong. Compare what you have done with the example code, maybe you'll find something.
