### ISSUE TITLE
Adding more padding on use custom monthHeaderResource

### ISSUE THREAD

**Issue by quocthinh212** [kizitonwose/CalendarView#235]
I use custom header. But we got some padding at bottom.
If use english header it work normal.

<img width="374" alt="Screen Shot 2020-10-31 at 14 06 57" src="https://user-images.githubusercontent.com/14103334/97773470-8c641600-1b82-11eb-85c5-b0181df384ba.png">

**Comment by kizitonwose** [comment]
What do you mean by "english header"?

**Comment by quocthinh212** [comment]
> What do you mean by "english header"?

The name of weeks too long but this padding not show. 
I want to remove padding if use short custom header (T2 T3 T4 T5...)
Please help me.

![image](https://user-images.githubusercontent.com/14103334/97793048-152d9100-1c19-11eb-91d8-0a5c8bd0e820.png)

**Comment by kizitonwose** [comment]
Can I see where/how this padding is added to the view?

**Comment by quocthinh212** [comment]
This padding automatic added to view when i use custom month header resource. With my custom dayofweek name. T2 T3 T4 T5 T6
But when i use sample code with default monthheader name (in above screenshoot) the padding not showing.

**Comment by asthagarg2428** [comment]
@quocthinh212 : How did you change the space below month header?
