### ISSUE TITLE
dayViewResource can't support custom

### ISSUE THREAD

**Issue by byron-xie** [kizitonwose/CalendarView#240]
Sorry, I describe the error. By the way, why does the dataBinding of the sample package come from? I did not find its location.

> Custom what?

Sorry, I describe the error. By the way, why does the dataBinding of the sample package come from? I did not find its location.

**Comment by kizitonwose** [comment]
Custom what?

**Comment by byron-xie** [comment]
are you there

**Comment by kizitonwose** [comment]
We discussed and resolved this outside of GitHub. So closing this issue.
