### ISSUE TITLE
issue while populating calendar in different devices of different manufacturer

### ISSUE THREAD

**Issue by Nildevelope** [kizitonwose/CalendarView#241]
While populating calendar data in different device models, there is discrepancy in calendarview populating.
1) For same user with device model - oppo f11(Android 10) :
    Calendar days are getting shifted one day before. As in india weekend falls on sat and sun but in oppo f11 it appears on fri & sat.
    Weekend data is coming from backend it is not hardcoded as "weekend1 = DayOfWeek.SUNDAY;"
![Oppo F11](https://user-images.githubusercontent.com/68062476/99663927-63ea8000-2a8d-11eb-8c47-d0f0f203905c.png)

2) For same user in device model - POCO X2(Android 10) : 
   Data is getting populated correctly.

![Poco x2](https://user-images.githubusercontent.com/68062476/99663925-63ea8000-2a8d-11eb-951a-3c1f558ec8ce.png)

Please refer the screenshots attached.

I am not able to understand what could be the issue. why it is getting differed for different device model. Please help me in resolving the issue.

**Comment by kizitonwose** [comment]
The explanation for this is that the first device(oppo f11) returns the first day of the week as `Monday` while the second device(POCO X2) returns `Sunday`. You need to adjust your headers for this accordingly as I guess it's presently hardcoded such that `Sunday` always comes first. 

What value are you passing to the setup method as first day of the week?

**Comment by Nildevelope** [comment]
Yes, i got the solution instead of passing default firstdayofWeek i am now passing SUNDAY as firstdayofweek. By doing this my issue got resolved. Thanks for the hint.

Earlier code: ```
DayOfWeek firstDayOfWeek = WeekFields.of(Locale.getDefault()).getFirstDayOfWeek();
        calendarView.setup(YearMonth.of(firstYear, firstMonth), YearMonth.of(lastYear, lastMonth), firstDayOfWeek );
```

Changed code to fix the issue:
`calendarView.setup(YearMonth.of(firstYear, firstMonth), YearMonth.of(lastYear, lastMonth), DayOfWeek.SUNDAY);`
