### ISSUE TITLE
inside nested scroll view example 5 is not working at all

### ISSUE THREAD

**Issue by shaikfaizal** [kizitonwose/CalendarView#242]
inside nested scroll view example 5 is not working at all

calendar view goes hide, is there any solution, i have more than 20 to 30 records to show below calendar view.

**Comment by shaikfaizal** [comment]
I have found a solution to use a custom nested scroll. if there is any other option let me know

**Comment by kizitonwose** [comment]
Since the CalendarView is a RecyclerView, you need to disable nested scrolling when used in a ScrollView. I see you have a workaround already, so I'll close this.
