### ISSUE TITLE
If I modify the day layout and add a background to the linear layout inside, the interface will become abnormal

### ISSUE THREAD

**Issue by byron-xie** [kizitonwose/CalendarView#243]
If I modify the day layout and add a background to the linear layout inside, the interface will become abnormal

**Comment by byron-xie** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="52dp"

    android:layout_height="52dp"
    android:layout_marginTop="5dp"
    android:gravity="center_horizontal"
    android:clipChildren="false"
    android:orientation="vertical">

    

    <LinearLayout
        android:layout_width="@dimen/d40"
        android:orientation="vertical"
        android:id="@+id/ll_container"
        android:gravity="center_horizontal"
        android:background="@drawable/example_2_selected_bg"
        android:layout_height="@dimen/d40">
        <TextView
            android:id="@+id/exTwoDayText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:gravity="center"
            android:includeFontPadding="false"
            android:padding="0dp"
            android:textColor="#181818"
            android:textSize="18sp"
            tools:text="22" />

        <TextView
            android:id="@+id/chinese"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:includeFontPadding="false"
            android:padding="0dp"
            android:text="十八"
            android:textSize="9sp" />
    </LinearLayout>

    <TextView
        android:id="@+id/tv_hasData"
        android:layout_width="5dp"
        android:layout_height="5dp"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="2dp"
        android:background="@drawable/bg_shap_blue"
        android:includeFontPadding="false"
        android:padding="0dp"
        android:text="." />

</LinearLayout>

**Comment by byron-xie** [comment]
![image](https://user-images.githubusercontent.com/29298219/100341549-a4ab4180-3017-11eb-9b3c-e853109e0bbc.png)

**Comment by byron-xie** [comment]
![image](https://user-images.githubusercontent.com/29298219/100341598-b8ef3e80-3017-11eb-8ada-b69a75d23098.png)

**Comment by byron-xie** [comment]
The preview is normal, but the display is abnormal

**Comment by kizitonwose** [comment]
Try calling `calendarView.daySize = Size(52dp, 52dp)`

Do convert the dp values to px though. The issue happens because the specified sizes are not actually used to size the view internally.

**Comment by byron-xie** [comment]
It still doesn’t work, because the width of the ll_container layout is not measured correctly.

**Comment by byron-xie** [comment]
> Try calling `calendarView.daySize = Size(52dp, 52dp)`
> 
> Do convert the dp values to px though. The issue happens because the specified sizes are not actually used to size the view internally.
What I need is to add a background to a certain internal layout in the item, such as ll_container

**Comment by byron-xie** [comment]
> Try calling `calendarView.daySize = Size(52dp, 52dp)`
> 
> Do convert the dp values to px though. The issue happens because the specified sizes are not actually used to size the view internally.

![image](https://user-images.githubusercontent.com/29298219/100427327-40e35000-30cd-11eb-885b-19003eabe881.png)

**Comment by byron-xie** [comment]
> Try calling `calendarView.daySize = Size(52dp, 52dp)`
> 
> Do convert the dp values to px though. The issue happens because the specified sizes are not actually used to size the view internally.

But the width of ll_container is larger than the parent layout. I do not know how to solve this,

**Comment by byron-xie** [comment]
![image](https://user-images.githubusercontent.com/29298219/100427422-61aba580-30cd-11eb-9c4a-fe182dee3214.png)
![image](https://user-images.githubusercontent.com/29298219/100427439-6708f000-30cd-11eb-92d7-d3df7334a349.png)
![image](https://user-images.githubusercontent.com/29298219/100427453-6b350d80-30cd-11eb-9de2-2fc7d335a251.png)
![image](https://user-images.githubusercontent.com/29298219/100427465-738d4880-30cd-11eb-9832-1af8b60e5078.png)

**Comment by byron-xie** [comment]
I think you converted the dp value of ll_container to px and then converted it to px again. When I set the dp of ll_container to 13, his layout was enlarged by more than 2 times, the preview interface was abnormal, but the display was normal

**Comment by byron-xie** [comment]
<LinearLayout
        android:layout_width="@dimen/d14"
        android:orientation="vertical"
        android:id="@+id/ll_container"
        android:gravity="center_horizontal"
        android:background="@drawable/example_2_selected_bg"
        android:layout_height="@dimen/d14">
        <TextView
            android:id="@+id/exTwoDayText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:gravity="center"
            android:includeFontPadding="false"
            android:padding="0dp"
            android:textColor="#181818"
            android:textSize="18sp"
            tools:text="22" />

        <TextView
            android:id="@+id/chinese"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:includeFontPadding="false"
            android:padding="0dp"
            android:text="十八"
            android:textSize="9sp" />
    </LinearLayout>
![image](https://user-images.githubusercontent.com/29298219/100429167-e7c8eb80-30cf-11eb-961d-7d059aff2c4c.png)
![image](https://user-images.githubusercontent.com/29298219/100429222-fd3e1580-30cf-11eb-8873-2ebb635d13c1.png)

**Comment by byron-xie** [comment]
my bad
