### ISSUE TITLE
Outlook calendar style

### ISSUE THREAD

**Issue by missphyrgames** [kizitonwose/CalendarView#245]
Hi,

First of all thanks for this amazing library! This isn't an issue but I need help with how to implement a certain feature with your library. The outlook calendar provides a sort of tab that you as a user can drag down that would expand the calendar and show the rest of the days of the month. However, when closed, you can scroll horizontally each 7 days. I have checked out the sample 1 you have provided and sort of understand how to implement this but I'm not sure how to implement a pull down behavior without refreshing the whole calendar.

Here's an example of what I mean but it's only an image:
![outlook](https://user-images.githubusercontent.com/48319526/102016771-74bfa600-3d5a-11eb-9fd8-d126a5ad0b17.PNG)

Hope you can help! Thanks.

**Comment by kizitonwose** [comment]
Actually, the drag is on the bottomsheet. I think what's happening is that the calendar setting is not updated till you release the bottomsheet. At least, for collapse, just drag the bottomsheet over the calendar view, when the dragging is done, reset the calendar to week mode. The expansion would difficult though as the view is already reconfigured to one just row. I think maybe they likely have two calendar views in sync and just makes the collapse one visible when the calendar is "collapsed", so in reality, the expanded calender is never really collapsed.
