### ISSUE TITLE
Could not resolve com.android.tools:desugar_jdk_libs:<latest-version>

### ISSUE THREAD

**Issue by robson-work** [kizitonwose/CalendarView#247]
Getting this error, not sure what I did wrong in the Gradle file.

`Could not resolve all files for configuration ':app:coreLibraryDesugaring'.
Could not resolve com.android.tools:desugar_jdk_libs:<latest-version>.
Required by:
    project :app
Could not resolve com.android.tools:desugar_jdk_libs:<latest-version>.
Could not get resource 'https://jcenter.bintray.com/com/android/tools/desugar_jdk_libs/%3Clatest-version%3E/desugar_jdk_libs-%3Clatest-version%3E.pom'.
Could not GET 'https://jcenter.bintray.com/com/android/tools/desugar_jdk_libs/%3Clatest-version%3E/desugar_jdk_libs-%3Clatest-version%3E.pom'. Received status code 400 from server: Bad Request`

Gradle:
`//apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'io.fabric'

if (new File("./signing.gradle").exists()) {
    apply from: "../signing.gradle"
}

buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
}

repositories {
    google()
    jcenter()
    flatDir {
        dirs 'src/main/libs'
    }
    maven { url 'https://maven.google.com' }
    maven { url "https://jitpack.io" }
    maven { url "https://artifactory.appodeal.com/appodeal" }
    mavenCentral()
}

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"
    defaultConfig {
        applicationId "com.balysv.loop"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1293
        versionName "6.32"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        wearAppUnbundled true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildTypes {
        /*customDebugType {
            debuggable true
        }*/
        debug {
            minifyEnabled false
            zipAlignEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    android {
        lintOptions {
            abortOnError false
            disable 'MissingTranslation'
        }
        dexOptions {
            javaMaxHeapSize "14g"
        }
    }

    useLibrary 'org.apache.http.legacy'
}

dependencies {
//    implementation project(':SamsungIap3Helper')
    implementation fileTree(dir: 'src/main/libs', include: '*.jar')
    //classpath 'com.google.gms:google-services:4.3.4'
    implementation 'com.google.android.gms:play-services-ads:19.5.0'
    implementation 'com.google.android.gms:play-services-location:17.1.0'
    implementation 'com.google.android.gms:play-services-analytics:17.0.0'
    implementation 'com.google.android.gms:play-services-games:21.0.0'
    implementation 'com.google.android.gms:play-services-plus:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation 'com.google.android.gms:play-services-measurement-base:18.0.0'
    implementation 'com.google.firebase:firebase-ads:19.5.0'
    //implementation 'com.google.firebase:firebase-core:17.4.3'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'com.google.firebase:firebase-database:19.5.1'
    implementation 'com.google.firebase:firebase-auth:20.0.1'
    implementation 'com.google.firebase:firebase-storage:19.2.0'
    implementation 'com.google.firebase:firebase-config:20.0.1'

    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'
    implementation 'com.github.kenglxn.QRGen:android:2.2.0'
    implementation 'me.dm7.barcodescanner:zxing:1.9.13'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.android.volley:volley:1.1.1'

    implementation 'com.facebook.android:facebook-android-sdk:7.1.0'

    implementation 'com.appodeal.ads:sdk:2.7.4.+'

    compile 'com.github.prashantsolanki3:Secure-Pref-Manager:0.25'

    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.19'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.browser:browser:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    // Calendar
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:<latest-version>'

    implementation 'com.github.kizitonwose:CalendarView:<latest-version>'

}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

`

**Comment by go-ammar** [comment]
How did you resolve this crash? this crash is still coming for me

**Comment by blitz-cmd** [comment]
Any solution?
