### ISSUE TITLE
Week Calendar with Starting Day as "Sunday"

### ISSUE THREAD

**Issue by usmankhan1990** [kizitonwose/CalendarView#251]
I am working on app, where I need to show a Week Calendar with the starting Day of the Week Calendar as Sunday. I tried to use Sample code and also tried to figure it out, but didn't work. My code is given below, kindly guide me who I can show Weekly Calendar as "Sun, Mon, Tue, Wed, Thur, Fri, Sat". One more thing I am trying to put custom Drawable with Red Dot, that also not showing there. I followed Sample from the Library.

[class AppointmentWeekFragment : BaseFragment(R.layout.appointment_week_fragment), HasToolbar,
    HasBackButton {

    override val titleRes: Int = R.string.appointment_weekly

    override val toolbar: Toolbar?
        get() = binding.exSevenToolbar

    private var selectedDate = LocalDate.now()
    private val dateFormatter = DateTimeFormatter.ofPattern("dd")
    private val dayFormatter = DateTimeFormatter.ofPattern("EEE")
    private val monthFormatter = DateTimeFormatter.ofPattern("MMM")

    private lateinit var binding: Example7FragmentBinding

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding = Example7FragmentBinding.bind(view)

        val dm = DisplayMetrics()
        val wm = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
        wm.defaultDisplay.getMetrics(dm)
        binding.exSevenCalendar.apply {
            val dayWidth = dm.widthPixels / 7
            val dayHeight = (dayWidth * 2)
            daySize = Size(dayWidth, dayHeight)
        }

        class DayViewContainer(view: View) : ViewContainer(view) {
            val bind = AppointmentCalendarDayBinding.bind(view)
            lateinit var day: CalendarDay

            fun bind(day: CalendarDay) {
                this.day = day
                bind.exSevenDateText.text = dateFormatter.format(day.date)
                bind.exSevenDayText.text = dayFormatter.format(day.date)
                bind.exSevenMonthText.text = monthFormatter.format(day.date)
                bind.dotImg.visibility = View.VISIBLE

                bind.exSevenDateText.setTextColor(view.context.getColorCompat(if (day.date == selectedDate) R.color.example_4_grey else R.color.example_4_grey))
//                bind.exSevenSelectedView.isVisible = day.date == selectedDate
            }
        }

        binding.exSevenCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) = container.bind(day)
        }

        val currentMonth = YearMonth.now()
        binding.exSevenCalendar.setup(
            currentMonth,
            currentMonth.plusMonths(1),
            DayOfWeek.values().random()
        )
        binding.exSevenCalendar.scrollToDate(LocalDate.of(2021, 1, 23))

        // Showing exact Date as 23rd of Jan 2021.
        // Need to start my Weekly Calendar from Sun.

        binding.exSevenCalendar.suppressLayout(true)

    }
}
](url)

My Fragment XML:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:clickable="true"
    android:focusable="true"
    android:orientation="vertical"
    tools:context=".Example7Fragment">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/exSevenToolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:popupTheme="@color/white" />
    </com.google.android.material.appbar.AppBarLayout>

    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/exSevenCalendar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:cv_dayViewResource="@layout/appointment_calendar_day"
        app:cv_hasBoundaries="false"
        app:cv_inDateStyle="none"
        app:cv_outDateStyle="none"
        app:cv_maxRowCount="1"
        app:cv_orientation="horizontal" />

</LinearLayout>

<img width="472" alt="Screen Shot 2020-12-31 at 3 06 05 AM" src="https://user-images.githubusercontent.com/8194315/103385745-214ca680-4b15-11eb-814d-33a4d5c320d0.png">

<img width="61" alt="Screen Shot 2020-12-31 at 3 05 49 AM" src="https://user-images.githubusercontent.com/8194315/103385732-172aa800-4b15-11eb-81d6-4b5ec0948acc.png">

**Comment by kizitonwose** [comment]
If you need it to start at a specific day, then you must allow indate generation. You currently have `app:cv_inDateStyle="none"`. Change it to `first_month`

**Comment by usmankhan1990** [comment]
Thank you for your reply. Can you please tell me the value for first_month? Currently I put it like: app:cv_inDateStyle="first_month" and it is showing me "Cannot resolve symbol first_month"

**Comment by kizitonwose** [comment]
The value is `firstMonth` when set via xml.

**Comment by usmankhan1990** [comment]
Thank you for the message. I put it like this:

    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/exSevenCalendar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:cv_dayViewResource="@layout/appointment_calendar_day"
        app:cv_hasBoundaries="false"
        app:cv_inDateStyle="firstMonth"
        app:cv_outDateStyle="none"
        app:cv_maxRowCount="1"
        app:cv_orientation="horizontal" />

But still it is showing Tuesday as the first day of the Week.

**Comment by usmankhan1990** [comment]
class AppointmentWeekFragment : BaseFragment(R.layout.appointment_week_fragment), HasToolbar,
    HasBackButton {

    override val titleRes: Int = R.string.appointment_weekly

    override val toolbar: Toolbar?
        get() = binding.exSevenToolbar

    private var selectedDate = LocalDate.now()
    private val dateFormatter = DateTimeFormatter.ofPattern("dd")
    private val dayFormatter = DateTimeFormatter.ofPattern("EEE")
    private val monthFormatter = DateTimeFormatter.ofPattern("MMM")

    private lateinit var binding: Example7FragmentBinding

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding = Example7FragmentBinding.bind(view)

        val dm = DisplayMetrics()
        val wm = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
        wm.defaultDisplay.getMetrics(dm)
        binding.exSevenCalendar.apply {
            val dayWidth = dm.widthPixels / 7
            val dayHeight = (dayWidth * 2)
            daySize = Size(dayWidth, dayHeight)
        }

        class DayViewContainer(view: View) : ViewContainer(view) {
            val bind = AppointmentCalendarDayBinding.bind(view)
            lateinit var day: CalendarDay

            fun bind(day: CalendarDay) {
                this.day = day
                bind.exSevenDateText.text = dateFormatter.format(day.date)
                bind.exSevenDayText.text = dayFormatter.format(day.date)
                bind.exSevenMonthText.text = monthFormatter.format(day.date)
                bind.dotImg.visibility = View.VISIBLE

                bind.exSevenDateText.setTextColor(view.context.getColorCompat(if (day.date == selectedDate) R.color.example_4_grey else R.color.example_4_grey))
//                bind.exSevenSelectedView.isVisible = day.date == selectedDate
            }
        }

        binding.exSevenCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) = container.bind(day)
        }

        val currentMonth = YearMonth.now()
        binding.exSevenCalendar.setup(
            currentMonth,
            currentMonth.plusMonths(1),
            DayOfWeek.values().random()
        )
        binding.exSevenCalendar.scrollToDate(LocalDate.of(2021, 1, 23))

        // Showing exact Date as 23rd of Jan 2021.
        // Need to start my Weekly Calendar from Sun.

        binding.exSevenCalendar.suppressLayout(true)

    }

**Comment by usmankhan1990** [comment]
Please check my above fragment, there getting Day value from CalendarDay. I just need to start week with Sun.

**Comment by kizitonwose** [comment]
Of course, then you have to also call `setup()` with the desired day:

Replace this:

```kotlin
binding.exSevenCalendar.setup(
    currentMonth,
    currentMonth.plusMonths(1),
    DayOfWeek.values().random()
)
```

with:

```kotlin
binding.exSevenCalendar.setup(
    currentMonth,
    currentMonth.plusMonths(1),
    DayOfWeek.SUNDAY
)
```

**Comment by usmankhan1990** [comment]
Thank you @kizitonwose for this. It is working fine now. Really love your work and highly appreciate your response.
