### ISSUE TITLE
Selecting one date make all Unselected in Weekly Calendar

### ISSUE THREAD

**Issue by usmankhan1990** [kizitonwose/CalendarView#252]
In my weekly calendar I want to select and Unselect dates. Currently I am facing a problem and trying to figure it out, if I want to click on one date, I want to deselect all selected dates. In short I want to keep a track of my previous selected dates from weekly calendar so I can show SELECTED(Blue), DEFAULT(White) and UNSELECTED(Gray Bordered) drawables accordingly. Please guide me how can I make click functionality in Weekly Calendar for selection, if select one makes all Unselected or Default.

```
class AppointmentWeekFragment : BaseFragment(R.layout.appointment_week_fragment), HasToolbar,
    HasBackButton {

    override val titleRes: Int = R.string.appointment_weekly

    override val toolbar: Toolbar?
        get() = binding.exSevenToolbar

    private var selectedDate = LocalDate.now()
    private val dateFormatter = DateTimeFormatter.ofPattern("dd")
    private val dayFormatter = DateTimeFormatter.ofPattern("EEE")
    private val monthFormatter = DateTimeFormatter.ofPattern("MMMM YYYY")

    private lateinit var binding: AppointmentWeekFragmentBinding

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding = AppointmentWeekFragmentBinding.bind(view)

        val dm = DisplayMetrics()
        val wm = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
        wm.defaultDisplay.getMetrics(dm)
        binding.exSevenCalendar.apply {
            val dayWidth = dm.widthPixels / 7
            val dayHeight = (dayWidth * 2)
            daySize = Size(dayWidth, dayHeight)
        }

        class DayViewContainer(view: View) : ViewContainer(view) {
            val bind = AppointmentCalendarDayBinding.bind(view)
            lateinit var day: CalendarDay

            fun bind(day: CalendarDay) {
                this.day = day
                bind.exSevenDateText.text = dateFormatter.format(day.date)
                bind.exSevenDayText.text = dayFormatter.format(day.date)
                binding.exSevenMonthText.text = monthFormatter.format(day.date)
                bind.dotImg.visibility = View.VISIBLE

                bind.exSevenDateText.setTextColor(view.context.getColorCompat(if (day.date == selectedDate) R.color.example_4_grey else R.color.example_4_grey))

                bind.viewCurved.setOnClickListener {
                    bind.exSevenDateText.setTextColorRes(R.color.white)
                    bind.exSevenDayText.setTextColorRes(R.color.white)
                    
                    // Selected Drawable
                    bind.viewCurved.setBackgroundResource(R.drawable.example_4_single_selected_bg)

                    // I want to make Unselected Drawable for the rest of the Days
                    bind.viewCurved.setBackgroundResource(R.drawable.white_empty_box)
                    
                    // Also for specific 1 day let say 27 Jan 2021, it should be Selected with Gray Box.
                    bind.viewCurved.setBackgroundResource(R.drawable.example_4_today_bg)                    
                }
            }
        }

        binding.exSevenCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) = container.bind(day)
        }

        val currentMonth = YearMonth.now()
        binding.exSevenCalendar.setup(
            currentMonth,
            currentMonth.plusMonths(1),
            DayOfWeek.SUNDAY
        )
        binding.exSevenCalendar.scrollToDate(LocalDate.of(2021, 1, 29))
        binding.exSevenCalendar.suppressLayout(true)
    }
}
```

I want to deselect all other dates.
<img width="481" alt="Screen Shot 2020-12-31 at 1 20 22 PM" src="https://user-images.githubusercontent.com/8194315/103403821-f1c88900-4b6a-11eb-844a-521d4b081dd3.png">

I need to have something like this where some dates already selected with Gray box, for other I can click to select Specific date.
<img width="358" alt="Screen Shot 2020-12-31 at 1 21 31 PM" src="https://user-images.githubusercontent.com/8194315/103403861-1ae91980-4b6b-11eb-9372-38cd41276972.png">

Kindly guide me to get this, really appreciate your help.

**Comment by kizitonwose** [comment]
I unfortunately cannot help with this. You need to implement the binding logic to fit your needs.

**Comment by usmankhan1990** [comment]
Thank you for your response @kizitonwose . Actually from this line of code `binding.exSevenCalendar.suppressLayout(true)`, I disabled scrolling for RecyclerView In calendar. But it also disabled `notifyCalendarChanged` effect. After removing this, solves a problem. Really thank you

**Comment by asthagarg2428** [comment]
@usmankhan1990 : I want to implement single date selection calendarView, how can I achieve it? Is there any in-built way in the library to enable single selection? (Like if user selects 3rd Jan then he selects 10th jan, now 3rd jan should be deselected)

**Comment by usmankhan1990** [comment]
@asthagarg2428 you can check Example 2 from the samples. There you can understand Select/Deselect easily. You can achieve it with binding adapter logic what we usually doing in RecyclerViews.
