### ISSUE TITLE
How can i adjust the overall size of the calendar

### ISSUE THREAD

**Issue by Kim-DongGeun** [kizitonwose/CalendarView#255]
i want to resize from
![image](https://user-images.githubusercontent.com/12513110/103472504-c2678580-4dd1-11eb-9b3f-d70bcd70647f.png)
to
![image](https://user-images.githubusercontent.com/12513110/103472560-40c42780-4dd2-11eb-8c87-5a3b075e2c33.png)

**Comment by kizitonwose** [comment]
You do not want to show the last row?

**Comment by Kim-DongGeun** [comment]
@kizitonwose no i want just to adjust overall calendar size
I thought i could adjust the size of the framelayout surrounding the textview with the day on it, ut the overall size of the calendar hasn't changed. plz help me.

**Comment by kizitonwose** [comment]
You need to set the `daySize` property.

**Comment by Kim-DongGeun** [comment]
@kizitonwose  thank you so much!!  I'll try

**Comment by asthagarg2428** [comment]
In Addition to above doubt, how to handle date selection? Like if we select another date, previous one should be deselected. Is there any in-build way to achieve this?

**Comment by Kim-DongGeun** [comment]
@asthagarg2428 what kind of handle?? like add task to date?

**Comment by asthagarg2428** [comment]
I want to implement single selection type of CalendarView, how to do that?
Like if I go for adding click listener on each textView, then I will have to do many other handling. And as per the readMe doc of this library, there is an option to enable single date selection. 
Hope I'm able to clearly explain my question

**Comment by kizitonwose** [comment]
@asthagarg2428 I replied you in #258 so I can close this.
