### ISSUE TITLE
Set up the calendar from a specific date to another

### ISSUE THREAD

**Issue by mohmdlabeeb** [kizitonwose/CalendarView#257]
val currentMonth = YearMonth.now()
binding.mainSingleRowCalendar.setup(
            currentMonth,
            currentMonth.plusMonths(2),
            DayOfWeek.values().random()
 )

I'm using the horizontal orientation, here to set up with calendar, we use months, i need to use a specific date from start and end. is there any work around?
My actual requirement is to show past 30 days from the current date. Is it possible?

**Comment by usmankhan1990** [comment]
Very easy to achieve this. You can do something like this:

        ```
val daysOfWeek = daysOfWeekFromLocale()
        val currentMonth = YearMonth.now()
        val previousMonths = YearMonth.of(2020, 1)

        binding.calendar.setup(previousMonths, currentMonth.plusMonths(12), daysOfWeek.first())
        binding.calendar.scrollToMonth(currentMonth)
```

Currently it is showing Previous 12 months and Plus 12 months. So you can change it as per your requirement.

**Comment by kizitonwose** [comment]
Per my understanding @mohmdlabeeb wants to set up with `LocalDate` instead of `YearMonth` which is currently not possible and not in the short-term plans.
