### ISSUE TITLE
Converting to Arabic Language giving wrong Days in Calendar

### ISSUE THREAD

**Issue by usmankhan1990** [kizitonwose/CalendarView#261]
I am using Example # 2 from Sample, in English language it is giving me correct Days of the Calendar like 1st Jan 2021 is Friday, but if I am changing device Language to Arabic, it is giving me wrong Dates like: 1st Jan 2021 on Saturday. 
I am using `daysOfWeekFromLocale()` from Ext for week days and changing my Preferred start of week as Sunday also,

```
fun daysOfWeekFromLocale(): Array<DayOfWeek> {
    val firstDayOfWeek = WeekFields.of(Locale.getDefault()).firstDayOfWeek
    var daysOfWeek = DayOfWeek.values()
    // Order `daysOfWeek` array so that firstDayOfWeek is at index 0.
    // Only necessary if firstDayOfWeek != DayOfWeek.MONDAY which has ordinal 0.
    if (firstDayOfWeek != DayOfWeek.SUNDAY) {
        val rhs = daysOfWeek.sliceArray(firstDayOfWeek.ordinal..daysOfWeek.indices.last)
        val lhs = daysOfWeek.sliceArray(0 until firstDayOfWeek.ordinal)
        daysOfWeek = rhs + lhs
    }
    return daysOfWeek
}

```

For reference you can see screenshots from English Language and also from Arabic. Both are from Sample Code Example # 2.

ENGLISH ONE (1st Jan 2021 is Friday)
<img width="433" alt="Screen Shot 2021-01-16 at 2 51 42 PM" src="https://user-images.githubusercontent.com/8194315/104809915-5beb5a00-580a-11eb-9032-66ffc063ddf0.png">

ARABIC ONE (1st Jan 2021 on Saturday)
<img width="429" alt="Screen Shot 2021-01-16 at 2 52 24 PM" src="https://user-images.githubusercontent.com/8194315/104809926-74f40b00-580a-11eb-8fbd-a8ee85b472bd.png">

**Comment by kizitonwose** [comment]
If you are using the `daysOfWeekFromLocale()` function to set up the headers, you should use ` WeekFields.of(Locale.getDefault()).firstDayOfWeek` to setup the calendarView.

**Comment by usmankhan1990** [comment]
Thank you for your reply @kizitonwose. This I am already using in the same `daysOfWeekFromLocale()` function. Can you please specify where I have to put `WeekFields.of(Locale.getDefault()).firstDayOfWeek` to setup the calendarView? I mean in the fragment where I am doing it?

**Comment by usmankhan1990** [comment]
One more thing to add, same time I always wants to start my week from `Sunday` only in calendar.

**Comment by kizitonwose** [comment]
To ensure that the calendar always starts from Sunday, you need to do two things:

When setting up the headers, do NOT use this:

~`val daysOfWeek = daysOfWeekFromLocale()`~

Use this instead:
```kotlin
val daysOfWeek = arrayOf(
    DayOfWeek.SUNDAY,
    DayOfWeek.MONDAY,
    DayOfWeek.TUESDAY,
    DayOfWeek.WEDNESDAY,
    DayOfWeek.THURSDAY,
    DayOfWeek.FRIDAY,
    DayOfWeek.SATURDAY
)
```

Then setup the calendarView like this:
`calendarView.setup(startMonth, endMonth, DayOfWeek.SUNDAY)`

**Comment by usmankhan1990** [comment]
Really thank you @kizitonwose . This solution works like a charm. I also did same.
