### ISSUE TITLE
When compressed from month to week(Example 1)

### ISSUE THREAD

**Issue by khuranakaran** [kizitonwose/CalendarView#265]
When calendar is compressed to week from month, it doesn't come back to last selected date and shows to previous month's last week..

**Comment by khuranakaran** [comment]
When calendar is compressed to week from month, it doesn't come back to last selected date and shows to previous month's last week..

**Comment by khuranakaran** [comment]
https://user-images.githubusercontent.com/12525440/105226671-52ede600-5b86-11eb-9ed8-ff95e8496f23.mp4

**Comment by kizitonwose** [comment]
Could you share some code? Also, did you take a look at example 1?

**Comment by khuranakaran** [comment]
Yes I've taken the sample code from Example 1 itself.

**Comment by kizitonwose** [comment]
Oh, the calendar does not know which date is "selected" you can always scroll to the selected date after changing to week/month view.

**Comment by khuranakaran** [comment]
Yes, I've done that. But it creates unnecessary scroll to that date. There isn't anything subtle for that ?

**Comment by kizitonwose** [comment]
Are you using `scrollToDate` or `smoothScrollToDate` ?

**Comment by khuranakaran** [comment]
smoothScrollToDate

**Comment by kizitonwose** [comment]
Then I would suggest using `scrollToDate` instead.

**Comment by kizitonwose** [comment]
If you look at example 1, I used `scrollToMonth` instead of `smoothScrollToMonth`

**Comment by khuranakaran** [comment]
smoothScrollToDate this is better, even if it scrolls but still goes to selected or current date. 
scrollToDate doesn't scroll to selected date.

**Comment by kizitonwose** [comment]
But `scrollToDate` works in example 1. Maybe you need to post it as runnable on the CalendarView so that it is run after the calendar is laid out.

**Comment by kizitonwose** [comment]
I believe this can be closed.
