### ISSUE TITLE
outDateStyle="endOfRow" causes issue 

### ISSUE THREAD

**Issue by shervinkoushan** [kizitonwose/CalendarView#266]
Steps to reproduce:

1. Change line 100 in Example5Fragment to `        val daysOfWeek = DayOfWeek.values() // used to be = daysOfWeekFromLocale()
`

1. Change outDateStyle to "endOfRow" in example_5_fragment.xml

1. Scroll to April. The last week is missing the first time you scroll to April. Going to another month and then coming back again, it works as expected

**Comment by shervinkoushan** [comment]
Have you had a chance to look at this yet @kizitonwose?

**Comment by kizitonwose** [comment]
Yes, was able to reproduce it. I have not had the time to work on a fix though.

**Comment by shervinkoushan** [comment]
Okay, just let me know when you do 😄 Awesome library by the way!

**Comment by kizitonwose** [comment]
Now fixed in 1.0.2
