### ISSUE TITLE
Bug in MonthConfig initialization when boundaries disabled?

### ISSUE THREAD

**Issue by evjava** [kizitonwose/CalendarView#272]
Hi! I created CalendarView with attributes `cv_hasBoundaries="false"` and `cv_maxRowCount="1"` and encountered with strange behavior: `CalendarView#scrollToMonth` doesn't work (because `CalendarAdapter#getAdapterPosition` always returns -1)

I think it's due to the bug in the method `MonthConfig.Companion#generateUnboundedMonths`:

```
calendarMonths.add(
                    // numberOfSameMonth is the total number of all months and
                    // indexInSameMonth is basically this item's index in the entire month list.
                    CalendarMonth(startMonth, monthWeeks, calendarMonths.size, calMonthsCount)
                )
```

Probably `currentMonth` should be here instead of `startMonth`.

**Comment by kizitonwose** [comment]
Could you try `scrollToDate` with the first day of your target month?

**Comment by evjava** [comment]
Locally it helps but then logic of my app became inconsistent: `calendarView#monthScrollListener` reports incorrect CalendarMonth. (with wrong `yearMonth` field which I use)

**Comment by kizitonwose** [comment]
This is explained in the [FAQ](https://github.com/kizitonwose/CalendarView#faq) section of the README. You cannot use the `yearMonth` value with a boundaryless calendar as there could be more than one month in an index. Please read the FAQ

**Comment by kizitonwose** [comment]
You can get the month values from the dates. See example 1.
