### ISSUE TITLE
Limit scrolling in week mode

### ISSUE THREAD

**Issue by missphyrgames** [kizitonwose/CalendarView#275]
Hi @kizitonwose,

I initially wanted to have a min and max date from a specific day rather than the whole months, but after researching through your documentation and other various comments, I believe we can only set the min and max months. I have disabled the onclick for the dates I don't want to include and also greyed them out.

However, as I am in week mode (where the rowCount == 1), there's a lot of unnecessary scrolling that I don't want the user to do. Is there a way I can limit the scroll to certain days.

To illustrate this, say the start day I want is Thursday 28th Jan and I want the end date to be Thursday 11th Feb. This means I have to include the whole of January and February in the week mode calendar. What I want to do is not allow the user to scroll before Thursday 28th Jan or after Thursday 11th Feb (anything up until saturday will be greyed out, but will not be able to scroll past this point).

Here's an image of what I'm trying to accomplish using your sample 1 as an example. Hopefully it's clear what I'm trying to do!
![weekmode-help](https://user-images.githubusercontent.com/48319526/106882809-1918f580-66d7-11eb-90d9-89c17bf7a2d6.png)

Thank you!

**Comment by kizitonwose** [comment]
This is tricky but I think something like this should work:

```kotlin
calendarView.addOnItemTouchListener(object : RecyclerView.SimpleOnItemTouchListener() {
    override fun onInterceptTouchEvent(rv: RecyclerView, e: MotionEvent): Boolean {
        if (rv.scrollState == RecyclerView.SCROLL_STATE_DRAGGING) {
            val firstVisible = calendarView.findFirstVisibleDay() ?: return false
            val lastVisible = calendarView.findLastVisibleDay() ?: return false
            val firstValidDate: LocalDate /// Get date from VM or elsewhere
            val lastValidDate: LocalDate /// Get date from VM or elsewhere
            return firstVisible.date == firstValidDate || lastVisible.date == lastValidDate
        }
        return false
    }
})
```

**Comment by missphyrgames** [comment]
Thanks for the reply @kizitonwose! I test this piece of code and unfortunately, once firstVisible.date == firstScrollableDate or lastVisible.date == lastScrollableDate, you can't scroll anymore. It just stops allowing you two swipe in either direction.

**Comment by kizitonwose** [comment]
I guess you could use the motion event to detect the scroll direction, so the check would look like:
`return firstVisible.date == firstScrollableDate && isLeftScroll || lastVisible.date == lastScrollableDate && !isLeftScroll`

**Comment by missphyrgames** [comment]
I'll give that a go and let you know, thanks!

**Comment by kizitonwose** [comment]
I assume this is resolved now.
