### ISSUE TITLE
Updating month configuration to a single row during initialization interferes with scrollToMonth

### ISSUE THREAD

**Issue by dachev** [kizitonwose/CalendarView#276]
My code allows users to persist their calendar mode preference. This means that I have to set the number of rows programmatically during initialization. When the number of rows is 6, everything works as expected. However, if the number of rows is 1, `scrollToMonth(YearMonth.now())` doesn't seem to have any effect and the calendar ends up showing the start month. Here is my code:

```
if (StaticPrefs.getString("CalendarPerspective", "month").equals("month")) {
    InDateStyle inStyle = InDateStyle.ALL_MONTHS;
    OutDateStyle outStyle = calendarView.getOutDateStyle();
    calendarView.updateMonthConfiguration(inStyle, outStyle, 6, true);
}
else {
    InDateStyle inStyle = InDateStyle.FIRST_MONTH;
    OutDateStyle outStyle = calendarView.getOutDateStyle();
    calendarView.updateMonthConfiguration(inStyle, outStyle, 1, false);
}

firstMonth = YearMonth.of(2010, 1);
lastMonth = YearMonth.now().plusYears(10);

calendarView.setup(firstMonth, lastMonth, DayOfWeek.SUNDAY);
calendarView.scrollToMonth(YearMonth.now());

calendarView.setDayBinder(new DayBinder<DashboardDateCellView>() {
    @NotNull
    @Override
    public DashboardDateCellView create(@NotNull View view) {
        // this is irrelevant
    }

    @Override
    public void bind(@NotNull DashboardDateCellView container, @NotNull CalendarDay day) {
        // this is irrelevant
});

calendarView.setMonthScrollListener(new Function1<CalendarMonth, Unit>() {
    @Override
    public Unit invoke(CalendarMonth calendarMonth) {
        // this is irrelevant
        return null;
    }
});
```

I am doing something wrong?

**Comment by kizitonwose** [comment]
This is because the concept of a "Month" does not exist anymore when the calendar is boundaryless, you should scroll using day (`scrollToDate()`) instead. This is explained in the FAQ section of the readme.

To fix this, call: `calendarView.scrollToDate(YearMonth.now().atDay(1))`

Now that I think about it, we could do just scroll using date internally if the calendar is boundarless as many users seem to run into this issue.

**Comment by kizitonwose** [comment]
Just curious, do you have `hasBoundaries` set to `false` for the week mode? cause otherwise then `scrollToMonth()` should work.

**Comment by dachev** [comment]
Yep, I'm setting `hasBoundaries` to `false` in single-row mode. As you suggested, `scrollToDate` works as expected.  Thanks a lot for your help and this awesome project.
