### ISSUE TITLE
Calender View MonthScrollListener not working in Arabic localisation in android

### ISSUE THREAD

**Issue by sagarbhojaviya** [kizitonwose/CalendarView#279]
In English localization working fine but in Arabic first time call after not calling. Can you please let me know what is issue?

I am using kotlin method:

calendarView.monthScrollListener = {
            JLog.e("==>", "month ${it}")
        }

**Comment by kizitonwose** [comment]
What setup are you using with the calendar? How can I reproduce this?

**Comment by sagarbhojaviya** [comment]
Check below my code this is my design layouts:

  <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="280dp"
            android:layout_marginStart="@dimen/dimen_4dp"
            app:cv_dayViewResource="@layout/calendar_day_layout"
            app:cv_inDateStyle="allMonths"
            app:cv_monthHeaderResource="@layout/example_3_calendar_header"
            app:cv_orientation="horizontal"
            app:cv_outDateStyle="endOfRow"
            app:cv_scrollMode="paged"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/constraintLayout" />

-------------------------------------------------------------------------------------

calendar_day_layout.xml

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/llMain"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:gravity="center">

<androidx.appcompat.widget.AppCompatTextView
    android:id="@+id/calendarDayText"
    style="@style/Text.Medium.Medium"
    android:layout_width="38dp"
    android:layout_height="38dp"
    android:gravity="center"
    android:text="1"
    android:textAlignment="center"
    android:textColor="@color/commonText"
    android:textSize="@dimen/dimen_16sp">

</androidx.appcompat.widget.AppCompatTextView>

</LinearLayout>

--------------------------------------------------------------------

example_3_calendar_header.xml

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/legendLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center"
    android:orientation="horizontal"
    tools:ignore="HardcodedText">

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText1"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="SUN"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText2"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="MON"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText3"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="TUE"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText4"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="WED"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText5"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="THU"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText6"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="FRI"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/legendText7"
        style="@style/Text.Medium.SemiBold"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center"
        android:text="SAT"
        android:textColor="@color/colorBrown"
        android:textSize="14sp" />

</LinearLayout>

**Comment by sagarbhojaviya** [comment]
Check below my code for setup calenderView:

**Comment by sagarbhojaviya** [comment]
i have two language support in my application 1. English and 2. Arabic.

**Comment by kizitonwose** [comment]
I tested by changing the device language and everything seems to work.

https://user-images.githubusercontent.com/15170090/107877942-ba6e2b80-6ecf-11eb-9038-6021ef0568d3.mp4

**Comment by sagarbhojaviya** [comment]
I found where is the issue.

**Comment by kizitonwose** [comment]
<img width="513" alt="Screenshot 2021-03-01 at 09 55 25" src="https://user-images.githubusercontent.com/15170090/109475313-d815c600-7a75-11eb-9c85-f62e74b2d102.png">


https://user-images.githubusercontent.com/15170090/109475625-3b075d00-7a76-11eb-9da3-bac7f4bf329e.mp4


Tried setting the size with Example 1, the month header does change when I swipe.

**Comment by sagarbhojaviya** [comment]
ok thanks
