### ISSUE TITLE
java.lang.UnsupportedOperationException: Cannot calculate the values for day Width\/Height with the current configuration

### ISSUE THREAD

**Issue by reckos** [kizitonwose/CalendarView#282]
""java.lang.UnsupportedOperationException: Cannot calculate the values for day Width\/Height with the current configuration.\n\tat com.kizitonwose.calendarview.CalendarView.onMeasure(SourceFile:5)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:194)\n\tat androidx.cardview.widget.CardView.onMeasure(SourceFile:11)\n\tat com.google.android.material.card.MaterialCardView.onMeasure(SourceFile:1)\n\tat android.view.View.measure(View.java:26411)\n\tat android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1185)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:723)\n\tat android.view.View.measure(View.java:26411)\n\tat androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(SourceFile:62)\n\tat androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(SourceFile:15)\n\tat androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(SourceFile:71)\n\tat androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(SourceFile:3)\n\tat androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:16)\n\tat androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:28)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:842)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:721)\n\tat android.view.View.measure(View.java:26411)\n\tat androidx.core.widget.NestedScrollView.measureChildWithMargins(SourceFile:5)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:194)\n\tat androidx.core.widget.NestedScrollView.onMeasure(SourceFile:1)\n\tat android.view.View.measure(View.java:26411)\n\tat androidx.viewpager.widget.ViewPager.onMeasure(SourceFile:33)\n\tat android.view.View.measure(View.java:26411)\n\tat android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)\n\tat android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(SourceFile:1)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(SourceFile:35)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:194)\n\tat androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:21)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:842)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:721)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:194)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:842)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:721)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:194)\n\tat com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)\n\tat android.view.View.measure(View.java:26411)\n\tat android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3638)\n\tat android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2373)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2665)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:797)\n\tat android.view.Choreographer.doFrame(Choreographer.java:732)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)\n\tat android.os.Handler.handleCallback(Handler.java:883)\n\tat android.os.Handler.dispatchMessage(Handler.java:100)\n\tat android.os.Looper.loop(Looper.java:237)\n\tat android.app.ActivityThread.main(ActivityThread.java:8167)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)\"

**Samsung Device, model: SM-T865 Android 11.**

**Comment by kizitonwose** [comment]
Does it work on other devices? Also, do you have the calendar in a scroll view?

**Comment by reckos** [comment]
cant tell. I received this error today. Only on this device. I have no information about any other errors on other devices. If I receive more errors on more devices I will let you know.

**Comment by kizitonwose** [comment]
Then this is expected. If you enable auto-sizing, then the view needs to be able to determine its width. To prevent the crash, set the `daySize` value manually.

**Comment by JasonTheDynamite** [comment]
I did investigate and it turns out that you are wrong @kizitonwose. After the investigation I noticed that if calendarView is inside a linearlayout with weightSum property it crashes with this exception. If I placed it inside a constrainlayout and added autosizing using constraintlayout mechanisms - it works 🙂 strange. This should work everywhere.
