### ISSUE TITLE
Expand Calendar and then compress it, makes some dates invible

### ISSUE THREAD

**Issue by khuranakaran** [kizitonwose/CalendarView#283]
When I expand calendar and the compress it, then some dates goes invisible. Check attached video for reference. [Video]
(https://r4---sn-npoeenle.googlevideo.com/videoplayback?expire=1613158371&ei=w7smYLeTHZSowgOzlYfQBQ&ip=111.93.33.186&id=a54096a7fc3248f6&itag=18&source=picasa&begin=0&requiressl=yes&sc=yes&ttl=transient&susc=ph&app=fife&ic=473&eaua=3UB2Pr5yaTo&mime=video/mp4&vprv=1&prv=1&dur=18.088&lmt=1613151112671879&sparams=expire,ei,ip,id,itag,source,requiressl,ttl,susc,app,ic,eaua,mime,vprv,prv,dur,lmt&sig=AOq0QJ8wRgIhAJcoJQHV8viMkjFEzbTyoUkl2kwuE4Orn952ddUc1xDdAiEA48b7W2ULwl_yR4jkXkTIN5-7-by7gAos0Glk0SYxPc4=&redirect_counter=1&cm2rm=sn-qxar7z&req_id=e3e950f688bca3ee&cms_redirect=yes&mh=ov&mm=34&mn=sn-npoeenle&ms=ltu&mt=1613150981&mv=u&mvi=4&pl=24&lsparams=mh,mm,mn,ms,mv,mvi,pl,sc&lsig=AG3C_xAwRQIgWScfABX7kze5TlMbJsN9FF7Et_q25j1i7Cu1mtB-0OACIQDpaUPTj7LVEBV8jqc6bfsLAsPFd21Kch_7FsXWXJzxyA%3D%3D)

**Comment by kizitonwose** [comment]
Video URL gives me error 403
