### ISSUE TITLE
First week of the month always moved to the left

### ISSUE THREAD

**Issue by kightsonsanom** [kizitonwose/CalendarView#287]
Hello, as in the description, the first week is moved to the left of the first row. Here is how my calendar view looks like:

```
<com.kizitonwose.calendarview.CalendarView
        android:id="@+id/calendarView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="19dp"
        app:cv_dayViewResource="@layout/calendar_day"
        app:cv_monthHeaderResource="@layout/calendar_header"
        app:cv_orientation="horizontal"
        app:cv_scrollMode="paged" />
```

I have tried setting `hasBoundaries` together with all possible `inDates` configurations, none of them worked as expected. However, it worked fine on the previous versions of the library:

This is how it works on the version above 0.4.0:

![image](https://user-images.githubusercontent.com/24854180/108546487-758c2f80-72e9-11eb-9912-893718749c9e.png)

This is how it works on version 0.4.0

![image](https://user-images.githubusercontent.com/24854180/108546606-a66c6480-72e9-11eb-8a13-879e39220fbb.png)

**Comment by kizitonwose** [comment]
Would be nice to reproduce this using one of the examples so I can easily take a look.
