### ISSUE TITLE
Offscreen page limit support like ViewPager2

### ISSUE THREAD

**Issue by harshitshah4** [kizitonwose/CalendarView#288]
It could be helpful to have off-screen page limit support like ViewPager2 , where , off-screen page limit represents number of pages/views that are pre-fetched . This could be especially helpful when using Calendar in "paging" mode .

**Use case :**
Suppose that calendar does a lot of job in each month , like calling data from server or heavy computing , so it would be helpful to limit the number of months on which bind() is called , so that it does not loads month that are not yet in the view.

**Implementation :**
We could use `getExtraLayoutSpace()` method of `LinearLayoutManager` to restrict the number of pages to be pre-loaded.

**Comment by kizitonwose** [comment]
There's `setupAsync()` which moves the setup to a background thread and notifies you when done. After the initial setup, calling `notifyCalendarChanged()`, `notifyMonthChanged()` or `notifyDayChanged()` does not trigger another setup. The current config is used. 

Also since this is basically a `RecyclerView`, bind is not called on each month until its position is close to the screen so your dayBinder is also not called until needed. Introducing this would be an attempt to solve a problem that does not really exist.

**Comment by harshitshah4** [comment]
Yeah I am almost convinced with your comment , but I still have one use case where this would be useful , currently as I noticed `bind()` is called for nearby months.

Now , assume that I am doing a **lot** of computation inside `bind()` for each day in each month , so it would be helpful to have flexibility to only do the computation for the currently visible month , I tried to do this and my device went into ANR since it keeps calling bind for each day in nearby months as I scroll through months.

To fix this one alternative would be to do the computation outside of the `bind()` and then call `notifyMonthChanged()` whenever the data for the given month is available , this works fine but it still causes nearby months to call its `bind()` , which is unnecessary and waste of computation power.

**Comment by kizitonwose** [comment]
You are right, heavy work should not be done in `bind()` as it can be called multiple times. For your second issue, what you can do is check for the currently visible month and and only do the work for that month.

**Comment by harshitshah4** [comment]
Yeah thanks , you can close this, it is anyway not a mandatory improvement .

Also , really thank you for this library , saved my day!!

**Comment by kizitonwose** [comment]
Closing this. Thanks for the input.
