### ISSUE TITLE
First month displayed doesn't autosize

### ISSUE THREAD

**Issue by thirstycoda** [kizitonwose/CalendarView#289]
Hi,

Thanks for sharing this library and continuing to maintain it. 

I've noticed an issue where in a month like February 2021 that has 4 rows, when the calendar first displays with this month open, it's height is for more than 4 rows.

This can be easily reproduced using example 1 of the sample. If you make the following 2 minor changes:

1. change the frame layout to a linear layout with a vertical orientation in example_1_fragment.xml
2. if the current month is not February 2021, change line 55 of Example1Fragment.kt to scroll to February 2021.

The result is the check box does not appear immediately underneath the calendar. If you swipe to March then swipe back to February, the issue does not occur

**Comment by BinarySimple17** [comment]
Hello,
Are there any plans to add this fix to the release?

**Comment by kizitonwose** [comment]
Sorry for the delay. Released in 1.0.4
