### ISSUE TITLE
setMonthPadding not working

### ISSUE THREAD

**Issue by darkkolos** [kizitonwose/CalendarView#294]
It is setting the padding but shrinking the month to it's size - padding.

**Comment by darkkolos** [comment]
![image](https://user-images.githubusercontent.com/68760374/110458128-4d5f4780-80c3-11eb-986d-3649d992553b.png)

**Comment by darkkolos** [comment]
As you can see by the image, the month got the padding but shrinked all its components to its maximum size minus the padding.

**Comment by kizitonwose** [comment]
This is working as expected since the padding is applied to the main view holder. Do you have a visual representation of your expectation? Maybe it's achievable in some other way.

**Comment by darkkolos** [comment]
yes, I would like the border to have full width of the screen and the content inside be centered with the margins 
![Capturar](https://user-images.githubusercontent.com/68760374/111450390-3c888480-8708-11eb-819f-1581dc1c8b92.png)

**Comment by kizitonwose** [comment]
Set `cv_monthViewClass` property on the CalendarView and set start and end padding on the provided view.

**Comment by kizitonwose** [comment]
You can look at example 6 to see how to add an extra view to the month root.
