### ISSUE TITLE
Trouble implementing it in Java.

### ISSUE THREAD

**Issue by manjitsaha** [kizitonwose/CalendarView#295]
I am not able to implement this in java. So, can anyone please provide documentation for this in java ?

**Comment by grzegorzpnk** [comment]
+1. Could you please provide any examples in java?

**Comment by manjitsaha** [comment]
> +1. Could you please provide any examples in java?

Actually, I don't kotlin at all. I have no idea how to start implementing it.

**Comment by grzegorzpnk** [comment]
@kizitonwose are you able to help?

**Comment by kizitonwose** [comment]
Hi, I am unable to help with this right now as I have a lot going on at the moment. But if there's a specific method in the examples that you're unable to convert to Java, I am happy to help out. What I unfortunately cannot do is rewrite the entire sample project and documentation in Java.

**Comment by grzegorzpnk** [comment]
okay, seems that we need simpliest example how to start deal with lib using java code. Currently I cannot find solution for that.

**Comment by kizitonwose** [comment]
This is basically still asking me to rewrite the documentation. I'm sorry but I'll have to close this issue. 

Just a hint though, for a basic setup, you just need to add the desired configurations in xml, then create and set a DayBinder class.
