### ISSUE TITLE
Feature Like Week number

### ISSUE THREAD

**Issue by meetr-spaceo** [kizitonwose/CalendarView#297]
Can we have a feature like show week number on every row of the month.

**Comment by kizitonwose** [comment]
Can I see an image of what you mean?

**Comment by meetr-spaceo** [comment]
![sample_formate](https://user-images.githubusercontent.com/34338588/111581591-86906980-87df-11eb-96d1-023bda0bef85.png)

Here is the sample

**Comment by kizitonwose** [comment]
That is not supported at the moment unless you would just add a view in the same layout as the calendarview where you'd set the values manually, then you need to listen for month scroll and update the texts.

**Comment by meetr-spaceo** [comment]
@kizitonwose 
As per your suggestion, I have made a changes
[Calendar Week Issue.pdf](https://github.com/kizitonwose/CalendarView/files/6210067/Calender.Week.Issue.pdf)
You can look into it in the month of Jan every year-end date is missing.

**Comment by kizitonwose** [comment]
Can you check if the dev branch snapshot fixes this? I made some changes there a while ago but have not published it yet.

**Comment by meetr-spaceo** [comment]
@kizitonwose 
Can you specify to check in which class and method I have implemented it as a module in the project.

**Comment by kizitonwose** [comment]
Use `implementation 'com.github.kizitonwose:CalendarView:dev-SNAPSHOT'` and see if you still have this problem.

**Comment by meetr-spaceo** [comment]
@kizitonwose
I have import the dev module still the same result.

**Comment by kizitonwose** [comment]
Sorry for the late reply but I'm not sure how to fix this since it's not a part of the library and the library works well without it. If you have suggestions on what you think is the problem, please let me know. 
The only other advice that comes to mind now is to ensure that the height of the added view follows the CalendarView's height, not the other way round.
