### ISSUE TITLE
How can i switch between week and month mode on swipe event ?

### ISSUE THREAD

**Issue by BenLscr** [kizitonwose/CalendarView#299]
Hi , 

I would like to achieve the same animation than the "Example 1" but on vertical scroll / swipe event perform on the calendar view.
My calendar is set on a toolbar. I have tried to set an onTouchListener on the calendar but it cancel the navigation (I mean the native horizontal scroll of the calendar).

```
calendar.setOnTouchListener { v , event -> 

    when (event.action) {

                MotionEvent.ACTION_DOWN -> {
                    x1 = event.x
                    y1 = event.y
                }

                MotionEvent.ACTION_UP -> {
                     // My logic ...
                }

            }

            return@setOnTouchListener true
}
```

Any solutions ?

Thank's. :)

**Comment by kizitonwose** [comment]
You would need:

```kotlin
calendarView.addOnItemTouchListener(object : RecyclerView.SimpleOnItemTouchListener() {
    override fun onInterceptTouchEvent(rv: RecyclerView, e: MotionEvent): Boolean {
        // Logic goes here
    }
})
```

Alternatively, you can extend `CalendarView` and override the touch methods (dispatchTouchEvent etc) for full control.

**Comment by BenLscr** [comment]
Thank's for your answer. :)
I will test it in few days and come back here to give you some news.

Thank's for your amazing work !

**Comment by BenLscr** [comment]
Some news : 

I have achieve this : 

```
binding.exOneCalendar.addOnItemTouchListener(object : RecyclerView.SimpleOnItemTouchListener() {
            override fun onInterceptTouchEvent(rv: RecyclerView, event: MotionEvent): Boolean {

                val MIN_DISTANCE = 200

                when (event.action) {

                    MotionEvent.ACTION_DOWN -> {
                        y1 = event.y
                    }

                    MotionEvent.ACTION_UP -> {

                        y2 = event.y
                        val deltaY = y2 - y1
                        if (abs(deltaY) > MIN_DISTANCE) {

                            if (y1 < y2) {
                                monthToWeek(false)
                            } else if (y1 > y2) {
                                monthToWeek(true)
                            }

                            return true
                        }

                    }

                }

                return false
            }
        })
    }
```

But I in some case the app crash :

> 2021-04-12 10:05:21.382 6349-6349/com.kizitonwose.calendarviewsample E/InputEventReceiver: Exception dispatching input event.
> 2021-04-12 10:05:21.382 6349-6349/com.kizitonwose.calendarviewsample E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
> 2021-04-12 10:05:21.385 6349-6349/com.kizitonwose.calendarviewsample E/MessageQueue-JNI: java.lang.IndexOutOfBoundsException: Index: 42, Size: 21
>         at java.util.ArrayList.get(ArrayList.java:437)
>         at com.kizitonwose.calendarview.ui.CalendarAdapter.notifyMonthScrollListenerIfNeeded(CalendarAdapter.kt:196)
>         at com.kizitonwose.calendarview.CalendarView$scrollListenerInternal$1.onScrollStateChanged(CalendarView.kt:649)
>         at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5355)
>         at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1586)
>         at androidx.recyclerview.widget.RecyclerView.cancelScroll(RecyclerView.java:3556)
>         at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3390)
>         at android.view.View.dispatchTouchEvent(View.java:14309)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
>         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
>         at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
>         at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
>         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
>         at android.view.View.dispatchPointerEvent(View.java:14568)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
>         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
>         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
>         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
> 2021-04-12 10:05:21.385 6349-6349/com.kizitonwose.calendarviewsample E/MessageQueue-JNI:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:335)
>         at android.os.Looper.loop(Looper.java:183)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> 2021-04-12 10:05:21.390 6349-6349/com.kizitonwose.calendarviewsample E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.kizitonwose.calendarviewsample, PID: 6349
>     java.lang.IndexOutOfBoundsException: Index: 42, Size: 21
>         at java.util.ArrayList.get(ArrayList.java:437)
>         at com.kizitonwose.calendarview.ui.CalendarAdapter.notifyMonthScrollListenerIfNeeded(CalendarAdapter.kt:196)
>         at com.kizitonwose.calendarview.CalendarView$scrollListenerInternal$1.onScrollStateChanged(CalendarView.kt:649)
>         at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5355)
>         at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1586)
>         at androidx.recyclerview.widget.RecyclerView.cancelScroll(RecyclerView.java:3556)
>         at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3390)
>         at android.view.View.dispatchTouchEvent(View.java:14309)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
>         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
>         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
>         at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
>         at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
>         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
>         at android.view.View.dispatchPointerEvent(View.java:14568)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
>         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
>         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
> 2021-04-12 10:05:21.391 6349-6349/com.kizitonwose.calendarviewsample E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
>         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:335)
>         at android.os.Looper.loop(Looper.java:183)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Happen when a scroll is not perfectly vertical so the calendar start to scroll horizontally too.

I think i have to disable a scroll when an other start.
I mean disable the horizontal scroll when the detection of a vertical scroll start.

**Comment by BenLscr** [comment]
![2021-04-12_12-14-31](https://user-images.githubusercontent.com/42968570/114379168-c2bdac80-9b88-11eb-8450-59f4714c0260.gif)

The logic i'm trying to achieve is exactly like this. 
The menu know which scroll to do.

**Comment by kizitonwose** [comment]
Not sure how I'll be able to further help with this. But if there's something specific I can do in the library to ease your implementation, please let me know.

**Comment by kizitonwose** [comment]
Guess I can close this.
