### ISSUE TITLE
How can I stay on the current view after updateMonthRange() ?

### ISSUE THREAD

**Issue by BenLscr** [kizitonwose/CalendarView#300]
Hello,

How can i stay on the current view, the current row, after using updateMonthRange() (async or not).

I have attempt to use updateMonthRangeAsync() and set a scrollToDate on the completion but this cause a little clipping.

```
 lastMonth = lastMonth.plusMonths(1)

 binding.calendarLayout.calendar.updateMonthRangeAsync(firstMonth, lastMonth) {
     binding.calendarLayout.calendar.scrollToDate(it.weekDays.first().first().date)
 }
```

Thank your for your help.

**Comment by kizitonwose** [comment]
The library only dispatches updates to the changed indices on the calendar. So scroll position should generally not change. Or maybe I don't understand you fully?
