### ISSUE TITLE
how to use monthScrollListener's calendarMonth parameter?

### ISSUE THREAD

**Issue by taehee28** [kizitonwose/CalendarView#301]
Hi.
I'm trying to set the monthScrollListener on `CalendarView` and don't get it how to use `calendarMonth` properly.
`calendarMonth.getYearMonth()` always returns first year and month of calendar range I set (I'm using java)
So I checked the codes in your sample project and it seems returning correct year and month that calendar shows

here's my code
```java
YearMonth current = YearMonth.from(today);
binder.weeklyCalendar.setup(current.minusYears(1), current.plusYears(1), DayOfWeek.SUNDAY);

// skip the codes

binder.weeklyCalendar.setMonthScrollListener(calendarMonth -> {
    Log.d(TAG, "scrolled : " + calendarMonth.getYearMonth());
    return Unit.INSTANCE
});
```
No matter what calendar shows, logs are always `scrolled : 2020-04` which is first yearMonth of calendar

Is there any specific way not written on docs?

**Comment by BenLscr** [comment]
Hi,
I think your calendar have hasBoundaries = false at this moment.
It's writed in the FAQ of the README.

>  Q: Why am I getting the same YearMonth value in the CalendarMonth passed into the MonthScrollListener?
> 
> A: This is because you have set app:cv_hasBoundaries to false in XML or have called calendarView.hasBoundaries = false in code. When this is set, the underlying YearMonth is undefined on all indices as each index could have multiple months depending on your maxRowCount value. If you need the month value with the hasBoundaries = false setting, you can get it from any of the CalendarDay values in the CalendarMonth class. You can always check if the first and last dates are from different months and act accordingly.

**Comment by taehee28** [comment]
I'd read the doc but not FAQ... sorry for my faults.
Thanks for the answer!
