### ISSUE TITLE
Is there a way I can move row item 3 at the top

### ISSUE THREAD

**Issue by raymondbarrinuevo** [kizitonwose/CalendarView#308]
![image](https://user-images.githubusercontent.com/8297619/117109074-ac38f880-adb6-11eb-8013-089c3edebc1b.png)

I want to move the last row at the top and the show Dates from 16 up to the end of month.

**Comment by kizitonwose** [comment]
This is not possible at the moment. I have plans to add this but have not found the time to do it yet. If this is a vertical calendar, a possible workaround would be to scroll to one of the days in the week so the week will be at the top of the screen.
