### ISSUE TITLE
Ability to show recent month at top.

### ISSUE THREAD

**Issue by sudansh** [kizitonwose/CalendarView#311]
Right now the recent month is at the bottom of the list. Is it possible to recent month at top

Currently: 
May
June
July

Can we do in recent order:
July
June
May

**Comment by sudansh** [comment]
I achieved this by reversing the recyclerview layoutmanger. 
```
(layoutManager as? LinearLayoutManager)?.run {
                reverseLayout = true
                stackFromEnd = true
            }
```
However it would be nice to have a method to set this property in library like `calenderView.isReverseLayout = true`

**Comment by kizitonwose** [comment]
I think only `reverseLayout = true` should be sufficient?
If this is needed in the library, a PR would be appreciated.
