### ISSUE TITLE
bugs Calendar divide page is error when max row count is 5 

### ISSUE THREAD

**Issue by bachdv-hust** [kizitonwose/CalendarView#312]
app:cv_maxRowCount="5"
                   app:cv_hasBoundaries="true"
                
                   app:cv_orientation="horizontal"
                   app:cv_outDateStyle="endOfGrid"
                   app:cv_scrollMode="paged"

-===============================================
I think there are bugs in this code in fun generateWeekDays in MonthConfig.kt

  // Add more rows to form a 6 x 7 grid //// 6 is fixed ?? 
                if (outDateStyle == OutDateStyle.END_OF_GRID) {
                    while (weekDaysGroup.size < 6) {
                        val lastDay = weekDaysGroup.last().last()
                        val nextRowDates = (1..7).map {
                            CalendarDay(lastDay.date.plusDays(it.toLong()), DayOwner.NEXT_MONTH)
                        }
                        weekDaysGroup.add(nextRowDates)
                    }
                }

**Comment by kizitonwose** [comment]
Could you explain the current vs expected behavior? A screenshot would also help.

**Comment by Y2JChamp** [comment]
is there a solution? i see last week half cut off on my calendar
