### ISSUE TITLE
How can i use month scroll with week mode feature.

### ISSUE THREAD

**Issue by sagarbhojaviya** [kizitonwose/CalendarView#313]
![Capture](https://user-images.githubusercontent.com/53989478/120337348-db3c7e80-c310-11eb-83bf-ca3f1eecdce4.PNG)

**Comment by kizitonwose** [comment]
Use scrollToDate() instead.

**Comment by sagarbhojaviya** [comment]
when i scrolling that time two time week days coming when two month combine come.

**Comment by sagarbhojaviya** [comment]
Here is my code:


  calendarView.updateMonthConfiguration(
            inDateStyle = InDateStyle.ALL_MONTHS,
            maxRowCount = 1,
            hasBoundaries = true
        )
    
        calendarView.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view, calendarView)

            // Called every time we need to reuse a container.
            override fun bind(container: DayViewContainer, day: CalendarDay) {
                container.day = day
                val textView = container.textView
                textView.text = day.date.dayOfMonth.toString()
                if (day.owner == DayOwner.THIS_MONTH) {
                    if (day.date.isBefore(today)) {
                        textView.setTextColor(
                            ContextCompat.getColor(
                                this@MainActivityy,
                                R.color.colorAccent
                            )
                        )
                    } else {
                        when (day.date) {
                            selectedDate -> {
                                textView.setTextColor(
                                    ContextCompat.getColor(
                                        this@MainActivityy,
                                        R.color.colorBrown
                                    )
                                )
                                textView.setBackgroundResource(R.drawable.shape_date_selected)
                            }
                            else -> {
                                textView.setTextColor(
                                    ContextCompat.getColor(
                                        this@MainActivityy,
                                        android.R.color.black
                                    )
                                )
                                textView.background = null
                            }
                        }
                    }
                } else {
                    textView.setTextColor(
                        ContextCompat.getColor(
                            this@MainActivityy,
                            R.color.colorPrimaryDark
                        )
                    )
                    textView.background = null
                }
            }
        }
        --------------------------------------------------------------------------
        
        val daysOfWeek = daysOfWeekFromLocale()
        calendarView.monthHeaderBinder = object :
            MonthHeaderFooterBinder<MonthViewContainer> {
            override fun create(view: View) = MonthViewContainer(view)
            override fun bind(container: MonthViewContainer, month: CalendarMonth) {
                // Setup each header day text if we have not done that already.
                if (container.legendLayout.tag == null) {
                    container.legendLayout.tag = month.yearMonth
                    container.legendLayout.children.map { it as TextView }
                        .forEachIndexed { index, tv ->
                            tv.text = daysOfWeek[index].name.first().toString()
                            tv.setTextColor(
                                ContextCompat.getColor(
                                    this@MainActivityy,
                                    R.color.colorBrown
                                )
                            )
                        }
                }
            }
        }
        
        ------------------------------------------------------------------------
        
         val currentMonth = YearMonth.now()
        calendarView.setup(currentMonth, currentMonth.plusMonths(12), daysOfWeek.first())
        calendarView.scrollToMonth(currentMonth)

        exFiveNextMonthImage.setOnClickListener {
            calendarView.findFirstVisibleMonth()?.let {
                if (currentMonth.plusMonths(12) != it.yearMonth.next) {
                    calendarView.smoothScrollToMonth(it.yearMonth.next)
                }
            }
        }

        exFivePreviousMonthImage.setOnClickListener {
            calendarView.findFirstVisibleMonth()?.let {
                calendarView.smoothScrollToMonth(it.yearMonth.previous)
            }
        }
        
        -----------------------------------------------------------------------
        
        
        calendarView.monthScrollListener = { month ->
         
            val firstDate = month.weekDays.first().first().date
            val lastDate = month.weekDays.last().last().date
            Log.e("==>","First date ${firstDate} ${lastDate}")

            if (firstDate.yearMonth == lastDate.yearMonth) {
            
                exFiveMonthYearText.text = monthTitleFormatter.format(firstDate) +" "+ firstDate.yearMonth.year.toString()
            } else {
               if (firstDate.year == lastDate.year) {
                   exFiveMonthYearText.text =
                       "${monthTitleFormatter.format(firstDate)} - ${monthTitleFormatter.format(lastDate)} " + firstDate.yearMonth.year.toString()
                } else {
                    exFiveMonthYearText.text =  "${monthTitleFormatter.format(firstDate)} - ${monthTitleFormatter.format(lastDate)}" + " ${firstDate.yearMonth.year} - ${lastDate.yearMonth.year}"
                }
            }
        }
        
        ------------------------------------------------------------------------------
        inner class DayViewContainer(view: View, calendarView: CalendarView) : ViewContainer(view) {
        lateinit var day: CalendarDay
        val textView = view.findViewById<TextView>(R.id.calendarDayText)

        init {
            view.setOnClickListener {
                if (day.owner == DayOwner.THIS_MONTH) {
                    if (selectedDate != day.date) {
                        val oldDate = selectedDate
                        selectedDate = day.date
                        calendarView.notifyDateChanged(day.date)
                        oldDate?.let { calendarView.notifyDateChanged(oldDate) }
                    }
                }
            }
        }
    }

    inner class MonthViewContainer(view: View) : ViewContainer(view) {
        val legendLayout = view.findViewById<LinearLayout>(R.id.legendLayout)
    }

**Comment by kizitonwose** [comment]
If I understand you correctly, you have two months visible, these are likely in and out dates. You need to set `inDateStyle` to `InDateStyle.NONE`
