### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by MoustafaElsaghier** [kizitonwose/CalendarView#316]
JFrog just announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:

February 28th: No more submissions will be accepted to Bintray, JCenter
May 1st: Bintray, JCenter services will no longer be available
Hence CalendarView should also be migrated to another maven repository like [Maven Central](https://central.sonatype.org/).

**Comment by kizitonwose** [comment]
The library is hosted with JitPack, therefore the JCenter shutdown does not affect it.
