### ISSUE TITLE
Detect State of scrolling

### ISSUE THREAD

**Issue by Zy-Dev07** [kizitonwose/CalendarView#318]
Thanks for this awesome library!, but one of the things I've noticed and hopefully gets addressed is the scrolling state of the calendar, there are use-cases where state of other components need to be updated upon month-scroll (i.e Monthscrollistener),
but with intensive fast scrolling other components are not being updated,

My workaround is to implement Recyclerview's addOnScrollListener, and detect the 3 state

I hope this functionality is added within the library

Sample code

`binding.entryBottomDialogCalendar.monthScrollListener = { it ->

            if (!calendarActionIsNotScroll) {
                CoroutineScope(Dispatchers.Main).launch {
                    dateChangedOnScroll(LocalDate.of(it.year, it.month, 1))
                }
            }

            calendarActionIsNotScroll = false
        }

        binding.entryBottomDialogCalendar.addOnScrollListener(object: RecyclerView.OnScrollListener() {
            override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
                when (newState) {
                    RecyclerView.SCROLL_STATE_IDLE -> {
                        // this even will trigger the same way when the calendar is finished scrolling
                        blockOtherActions(false)
                    }
                    RecyclerView.SCROLL_STATE_DRAGGING -> {
                        blockOtherActions(true)
                    }
                    RecyclerView.SCROLL_STATE_SETTLING -> {
                        blockOtherActions(true)
                    }
                }
            }
        })`

**Comment by kizitonwose** [comment]
The scroll state is dispatched when the calendar is settled (IDLE), and as you noticed, it's basically a recyclerview so you can always add your scroll listeners with more behaviors as you want. I'll close this but feel free to comment if you have more thoughts on the matter and we can discuss them.
