### ISSUE TITLE
Please provide example using Coordinatorlayout collapse Calendarview

### ISSUE THREAD

**Issue by HuuNguyen312** [kizitonwose/CalendarView#32]
Dear @kizitonwose 

Your library is great which is very easy to custom.

Please help me provide an example using Coordinatorlayout collapse Calendarview

For example:
https://camo.githubusercontent.com/b609928ccdc65c98c1b6f2ab00cf6c46a12e8c81/687474703a2f2f6f736e6674736961652e626b742e636c6f7564646e2e636f6d2f737570657263616c656e6461726578616d706c652e676966

Thank you!

**Comment by kizitonwose** [comment]
It seems the link in your issue is broken.

**Comment by HuuNguyen312** [comment]
https://github.com/MagicMashRoom/SuperCalendar

It is a gif image in that library

Thanks

**Comment by kizitonwose** [comment]
Don't know if it's a location-related problem but all the image links in that project's REAMDE are not working on my end. You can see the screenshot:
 
<img width="750" alt="Screenshot 2019-07-21 at 8 37 27 PM" src="https://user-images.githubusercontent.com/15170090/61596134-9e24e280-abf7-11e9-8c0a-4fb628874b68.png">

You should download the gifs and attach them directly with your comment here or upload them to another provider(e.g Gfycat) and share the links here.

**Comment by HuuNguyen312** [comment]
> You should download the gifs and attach them directly with your comment here or upload them to another provider(e.g Gfycat) and share the links here.

https://gfycat.com/focusedhonorableiguana

![687474703a2f2f6f736e6674736961652e626b742e636c6f7564646e2e636f6d2f737570657263616c656e6461726578616d706c652e676966](https://user-images.githubusercontent.com/9895294/61600767-90ee0f00-ac5c-11e9-968c-cd69a3da02f9.gif)

Thanks for your responsing

**Comment by kizitonwose** [comment]
I believe you have to do something similar to what I did in Example 1, except you don't need a `ValueAnimator` in this case. You just need to change the necessary configuration, then add an offset change listener to your AppBar(`AppBarLayout.OnOffsetChangedListener`) and use the offset value passed into your listener to update the CalendarView's height accordingly.

**Comment by kizitonwose** [comment]
I consider this solved and will now close this issue.
