### ISSUE TITLE
how can i change weekends color

### ISSUE THREAD

**Issue by AliUzunoglan0** [kizitonwose/CalendarView#323]
can u help me how can i change the color of weekend days

**Comment by danielcerezodev** [comment]
Inside your calendar view dayBinder you could get you day.date, change the format to "dddd" and change your colors accordingly. 

It will look something like this:

when(ChangeDayFormat(day.date) {
"Saturday" -> { // Change to whatever color you need }
"Sunday" -> { // Change to whatever color you need}
else -> { // Set to the normal color}
}

Disclaimer: There might be a better approach that I don't know, but this is how I would do it with my limited knowledge on the library.

**Comment by kizitonwose** [comment]
@danielcerezodev Thanks a lot for helping out with many issues in the repo.

**Comment by kizitonwose** [comment]
@AliUzunoglan0 The suggested answer is right and can be simplified as:

```kotlin
when (day.date.dayOfWeek) {
    DayOfWeek.SATURDAY, DayOfWeek.SUNDAY -> { // Change to whatever color you need }
    else -> { // Change to whatever color you need }
}
```
