### ISSUE TITLE
Is it possible to change calendar day layout textview font family?

### ISSUE THREAD

**Issue by ashleymorris2** [kizitonwose/CalendarView#325]
Hey great calendar. I've created a layout for `calendar_day_layout.xml` as per the docs, problem is that it won't accept my custom style and in particular it won't apply a font family that I've set. Is this possible?

What I've done:

```xml
  <TextView
        android:gravity="center"
        android:id="@+id/calendarDayText"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:textSize="16sp"
        android:text="33"
        style="@style/RegularTextLight"
        tools:text="31" />
```

**Comment by kizitonwose** [comment]
The Library does not modify the provided views. So it's very likely that this is not an issue with the library.

**Comment by ashleymorris2** [comment]
It allows me to apply any style to the text view except changing the font family. So I can change the font size and colour, but not the font family.

**Comment by kizitonwose** [comment]
Can you reproduce this with the sample app?
