### ISSUE TITLE
some days are invisible

### ISSUE THREAD

**Issue by AliUzunoglan0** [kizitonwose/CalendarView#328]
![Ekran Görüntüsü (88)](https://user-images.githubusercontent.com/81925290/127860010-22ba0827-bcae-4e4e-bba8-e7613ac93f7f.png)
![Ekran Görüntüsü (89)](https://user-images.githubusercontent.com/81925290/127860016-68e53b52-d8df-4e51-b27d-2de10a997f5b.png)

some days are behave like another months day and being invisible

**Comment by AliUzunoglan0** [comment]
![Ekran Görüntüsü (90)](https://user-images.githubusercontent.com/81925290/127862270-bc8974cf-d767-44ff-b861-11d0e9084879.png)

**Comment by kizitonwose** [comment]
Could you try to reproduce this with the sample project?

**Comment by AliUzunoglan0** [comment]
I tried but there is no change. it still goes on.

**Comment by AliUzunoglan0** [comment]
> Could you try to reproduce this with the sample project?

I tried but there is no change. it still goes on.

**Comment by AliUzunoglan0** [comment]
okey ı did it my bad
