### ISSUE TITLE
Having a multiple days event 

### ISSUE THREAD

**Issue by h8h** [kizitonwose/CalendarView#330]
Hi

I really like this CalendarView. Thank you for such a great work.

I would like to extend Example3 to have multiple days events.

As far as I understand, the `DayBinder` is called day by day.

So how can I have an efficient way to query multiple days events? 

I'll start with the data class:

```
data class Event(val id: String, val text: String, val startDate: LocalDate, , val endDate: LocalDate)
```

```
        binding.exThreeCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) {
...
                if (day.owner == DayOwner.THIS_MONTH) {
                    textView.makeVisible()
                    when (day.date) {
....
                        else -> {
                            textView.setTextColorRes(R.color.example_3_black)
                            textView.background = null
                            dotView.isVisible = events[day.date].orEmpty().isNotEmpty()
                        }
                    }
                } else {
...
                }
            }
        }
```

For events[day.date], I need to query both the startDate and the endDate and also have a reference to the event to know if it is an event of multiple days. This seems very strange to me and not very efficient. Is there any other solution? I don't have much experience in Android / Kotlin coding.

Thank you.

**Comment by kizitonwose** [comment]
I don't fully understand what you want to achieve but I think the efficiency depends on your logic. I, unfortunately, can't help with this from the little code you shared. I need more information. Feel free to open this issue again, if you have more information.
