### ISSUE TITLE
Calendar YearView available?

### ISSUE THREAD

**Issue by Devdbsdngml** [kizitonwose/CalendarView#333]
hello calendar :)
Thanks to you, the calendar is useful!
But I have a problem, I have to show users 6 months on one screen Like #70 
I tried adjusting the daySize and changing the layoutManager to GridLayout, but an error occurred.
Do you have any way? If there is a way, I would be very grateful if you let me know 👍

**Comment by kizitonwose** [comment]
Unfortunately, this is not supported, as stated in #70

**Comment by kizitonwose** [comment]
Update https://github.com/kizitonwose/Calendar/issues/535#issuecomment-2241054447
