### ISSUE TITLE
Incorrect date showing on Incorrect Week day on some devices 

### ISSUE THREAD

**Issue by dharamveer-roundr** [kizitonwose/CalendarView#336]
The first one is an Incorrect result and the 2nd one is expected.
1. ![image](https://user-images.githubusercontent.com/68960344/132223584-d322ae4c-0113-43eb-b92b-9828b5f8645c.png)

The correct one should be as below - 

2. ![image](https://user-images.githubusercontent.com/68960344/132223846-954bab20-84e7-46bb-9250-4fb9707c1b50.png)

Any Idea/Solution to why it is happening. I have referred to Example 5

**Comment by kizitonwose** [comment]
You're using the wrong first day of week somewhere. Either the calendar initialisation or the day header texts.

**Comment by dharamveer-roundr** [comment]
> You're using the wrong first day of week somewhere. Either the calendar initialisation or the day header texts.

I see, should I make it dynamic as in example 1

**Comment by kizitonwose** [comment]
Yes, you must use the same value to set up the calendar view and header texts.

**Comment by dharamveer-roundr** [comment]
It is working fine now 👍

**Comment by gpattani-aapna** [comment]
I have same problem. Only use reported the mentioned issued. User is using samsung t590. It works well as expected on all other device. 


Below is on calendar initialisation
 binding.cvCalendar.setup(
                currentMonth,
                today.plusDays(180).yearMonth,
                daysOfWeek.first()
            )
            
            Any suggestion ?
