### ISSUE TITLE
CalendarView#setupAsync uses GlobalScope

### ISSUE THREAD

**Issue by TemMax** [kizitonwose/CalendarView#337]
Hello. It's wrong way to use GlobalScope. Better way is pass CoroutineScope as parameter to CalendarView#setupAsync.
For example:
`fun setupAsync(startMonth: YearMonth, endMonth: YearMonth, firstDayOfWeek: DayOfWeek, coroutineScope: CoroutineScope, completion: Completion? = null)...`

**Comment by kizitonwose** [comment]
Makes sense, and would also allow the user to cancel the job early if needed. It's not critical, I'll add it when I have the time but a PR would also be nice.

**Comment by kizitonwose** [comment]
On second thought, I realized it would be better to make the method a suspend function. I am not sure how that would be called from Java, but I know it's going to get ugly for Java users. Also, that would be a breaking change even for Kotlin users.

**Comment by jeffako56** [comment]
is it implemented already?

**Comment by kizitonwose** [comment]
@jeffako56  not yet.

**Comment by kizitonwose** [comment]
In version 1.1.0, a cancellation block is provided to cancel the job. This way Java and Kotlin users can benefit.
