### ISSUE TITLE
Vertical Calendar Scroll Problem.

### ISSUE THREAD

**Issue by mehmetniyazi** [kizitonwose/CalendarView#338]
Hello Kizito,
I used your calendarview in my project. I am trying to scroll specific month position after vertical calendar created.

When I checked your project, I saw that if it is set to vertical, the scroll process does not complete.
I changed Exaple4Fragment.kt line 81 at setup.
I replace start month with one month previous to see that scrolling working or not. But it does not work.
Can you help me on this situation pls.

Old code 
```
binding.exFourCalendar.setup(currentMonth, currentMonth.plusMonths(12), daysOfWeek.first())
        binding.exFourCalendar.scrollToMonth(currentMonth)
```

Replaced:
```
binding.exFourCalendar.setup(currentMonth.minusMonths(1), currentMonth.plusMonths(12), daysOfWeek.first())
binding.exFourCalendar.scrollToMonth(currentMonth)
```

**Comment by kizitonwose** [comment]
I tested this today and it works as expected so I'll close this.

https://user-images.githubusercontent.com/15170090/134796587-5c178025-a31c-4492-a0a6-72787fab5e93.mp4

**Comment by mehmetniyazi** [comment]
thanks for you reply,

Nice project.
