### ISSUE TITLE
Separate header from CalendarView

### ISSUE THREAD

**Issue by eypibee** [kizitonwose/CalendarView#34]
Hi @kizitonwose , is it possible to do this? If not, can I make the header's background transparent? This is what I'm trying to achieve.

![image](https://user-images.githubusercontent.com/46506486/61771071-68fbd880-ae21-11e9-9762-7a281f9cb70e.JPG)

**Comment by kizitonwose** [comment]
This is very much possible. See Example 6 in the sample app where I used a `CardView` as the background much like the one in your screenshot. Also, see Example 1 or 2 where the header is separated from the calendar content.

**Comment by eypibee** [comment]
> This is very much possible. See Example 6 in the sample app where I used a `CardView` as the background much like the one in your screenshot. Also, see Example 1 or 2 where the header is separated from the calendar content.

This is what I'm looking for. My mistake. I immediately focused on 3 and 5. Thanks!

I don't know if I need to file separate issue/question but, can I disallow the swipe/scroll and depend only in arrow navigations?

**Comment by kizitonwose** [comment]
> Can I disallow the swipe/scroll and depend only in arrow navigations?

Yes, this can be done. See #13

**Comment by eypibee** [comment]
> > Can I disallow the swipe/scroll and depend only in arrow navigations?
> 
> Yes, this can be done. See #13

Thanks a lot!
