### ISSUE TITLE
Select day after scroll month programmatically

### ISSUE THREAD

**Issue by Leeeeerich** [kizitonwose/CalendarView#340]
Hello! In the month we can touch day from next or back month. I can change month, but I don't understand: how I can selected day after scroll because I have not found a day list.

![image](https://user-images.githubusercontent.com/26391015/135581605-c092be53-96df-44e0-b189-f6398300b632.png)

![image](https://user-images.githubusercontent.com/26391015/135581568-f917229b-77a8-43a9-a58d-7da9e1e27828.png)

**Comment by kizitonwose** [comment]
Please take a look at the example project or the README.

**Comment by Leeeeerich** [comment]
I can't find solutions in the documentation. I use the sample application, it has no implementation then!
