### ISSUE TITLE
Crash on Calendar Setup on Release Build Variant

### ISSUE THREAD

**Issue by snehilideal** [kizitonwose/CalendarView#344]
Hello,

I am facing an error with the 1.0.4 version 
The crash only in release build variants

Here the crashlog : 

FATAL EXCEPTION: main Process: com.it.offschool, PID: 453 java.lang.NoSuchMethodError: No virtual method compareTo(Lj$/time/YearMonth;)I in class Lj$/time/YearMonth; or its super classes (declaration of 'j$.time.YearMonth' appears in base.apk!classes2.dex)

**Comment by kizitonwose** [comment]
Closing in favour of #249
