### ISSUE TITLE
Where do I call the function to populate content when the calendar is set to a new date?

### ISSUE THREAD

**Issue by madhall** [kizitonwose/CalendarView#346]
Hi,

I am using the calendar Example Fragment 7. In this when ever the calendar is set to a new date, I need to query the DB and present data for that date. If I call  the data population function in the bind function, the data function gets called multiple times and the UI gets messed up...

where is the best place to call the data function whenever the calendar is reset?

Thank for having a look at this

regards
madhall

**Comment by kizitonwose** [comment]
I am not sure I fully understand your question but I think you need to do the query after a click or scroll event.
