### ISSUE TITLE
I want run on all device but why here need check for above O=>

### ISSUE THREAD

**Issue by kamalprs** [kizitonwose/CalendarView#348]
I want run on all device but why here need check for above O=>
-------------------------------------------------------------------
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    container.textView.text = day.date.dayOfMonth.toString()
                }

val currentMonth = YearMonth.now()
        val firstMonth = currentMonth.minusMonths(10)
        val lastMonth = currentMonth.plusMonths(10)
        val firstDayOfWeek = WeekFields.of(Locale.getDefault()).firstDayOfWeek

val currentMonth = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            YearMonth.now()
        } else {
            TODO("VERSION.SDK_INT < O")
        }

**Comment by kizitonwose** [comment]
You do not need this check if you have set up [API desugaring](https://github.com/kizitonwose/CalendarView#setup). 
You can see that this is not used in the sample project with a min sdk of 21.
