### ISSUE TITLE
Feature Request - export calendar as file(ics or any) then import into another device and show in your calendar

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [kizitonwose/CalendarView#349]
@kizitonwose and team, it seems to be great to this library. Thank you guys so much :)

Feature Request - export calendar as file(ics or any) then import into another device and show in your calendar

Kindly please consider this request.
I want to export all the events from my friend's android phone and import it to my android app. In your calendar implementation, Is there any way to achieve that. If not please update me about your advice. Thank you so much.

My plan is programatically export all calender and its events to ics or any supported file and store it in firebase then import it into my device programtically and show the events in your calendar. is this good idea? !! Thanks in advance :)

**Comment by kizitonwose** [comment]
Hi, this is out of the scope of the library. How you choose to export or import data to your app should not be handled by the View.

**Comment by vijayakumarmariyappan** [comment]
@kizitonwose I agree with you. but you could have an option to export only to ics or any famous file format, which will be very useful to the users. Though thanks for your feedback, hope u will be considering export only feature in future. Thanks for your time. Happy Christmas :)
