### ISSUE TITLE
Month paging

### ISSUE THREAD

**Issue by acolombo25** [kizitonwose/CalendarView#35]
I'm currently displaying 6 monhts in a vertical calendar similar to example 2. In my project the bottom month is the most recent one and the top month is 6 months ago. Everything is fine. But I need more than 6 months and I should get the data from a web service.

So I set up this listener:
`calendarView.addOnScrollListener(object : RecyclerView.OnScrollListener() {
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                calendarView.findFirstVisibleMonth()?.let {
                    if (startMonth == it.yearMonth) {
                        lastMonthReachedListener?.invoke(it.yearMonth)
                    }
                }
            }
        })`
which should detect when the top month is reached, trigger the listener and download the data for the next 6 months, then display them.

The problem is every time I setup the CalendarView to change the startMonth, the view gets scrolled to the new months at the start, instead of remaing at the current position, so the listener gets called again and loops like that.

when calling the setup method as reccomended ("You can call this any time") is it possible to mantain position? Or maybe you have some other ideas...

**Comment by acolombo25** [comment]
I've resolved the problem by keeping track of the current visible month with another scroll listener, and then doing this when new data needs to be shown:

- save current month in a temporary variable before the other scroll listener changes it again
- remove the paging listener
- call setup() method with new startDate
- scroll to temporary current month
- add the paging listener again

@kizitonwose, if you any other idea and/or a cleaner solution I'd like to hear it. If not you can just close the issue.

**Comment by kizitonwose** [comment]
Your solution does look a bit tedious but seems to be the only way out for now. 
I will investigate the possibility of retaining the visible position if `setup()` is called multiple times.

**Comment by kizitonwose** [comment]
In version [0.2.6](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.5), calling `setup()` retains the currently visible month and scroll offset.
