### ISSUE TITLE
Week scroll listener for CalendarView 

### ISSUE THREAD

**Issue by yousufshawon** [kizitonwose/CalendarView#352]
Is there any listener or any way i can notify UI after week change by scroll in week mode. As far i found only `monthScrollListener` when scrolls to a new month.

**Comment by kizitonwose** [comment]
Please see example 1, the month scroll listener is called, you just have to bind the UI accordingly.

**Comment by yousufshawon** [comment]
I checked example 1, month scroll listener is called only when month is changed, but i need to notify when week changed in **_week mode_** . month scroll listener doesn't notify for week change
