### ISSUE TITLE
Single day selection.

### ISSUE THREAD

**Issue by NirmalyaSin** [kizitonwose/CalendarView#353]
I used the first calendar example from your demo. There the current date is selected when the calendar view is initiated. It is okay. But when I select another date it is selected but the current date is also kept selected. How can I deselect the current date and change it's background when another date is selected ?

**Comment by kizitonwose** [comment]
You need to call `notifyDateChanged()` on the original date as well so you can update it on the `dayBinder` as done in the examples.
