### ISSUE TITLE
when page the scrolls, skip a month

### ISSUE THREAD

**Issue by wizskjo** [kizitonwose/CalendarView#355]
Dear @kizitonwose 

Thank you for your library.

I am currently programming a calendar that scrolls vertically by page.
A month is made of 5, 6, or 4 week rows,
 and I want to change the height to be flexible every time the number of rows changes.
but, when I scroll from the 6 rows month to the 5 rows, will skip the 5 rows month.

`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/transparent"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_calendar_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:letterSpacing="0"
        android:text="@string/year"
        android:textAllCaps="true"
        android:textColor="@color/font_level9"
        android:textSize="@dimen/dimen_14dp"
        android:textStyle="bold"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.kizitonwose.calendarview.CalendarView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/dimen_19dp"
        android:background="@color/transparent"
        android:visibility="visible"
        app:cv_dayViewResource="@layout/item_calendar_day"
        app:cv_maxRowCount="6"
        app:cv_monthHeaderResource="@layout/item_calendar_head"
        app:cv_orientation="vertical"
        app:cv_scrollMode="paged"
        app:cv_hasBoundaries="true"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tv_calendar_title" />

</androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by kizitonwose** [comment]
Can I have a sample project where this can be reproduced? Or let me know how to reproduce this behavior using the sample project.
