### ISSUE TITLE
Horizontal scrolling limit disable past days

### ISSUE THREAD

**Issue by madhall** [kizitonwose/CalendarView#359]
Hi,

I have successfully implemented the Horizontal scrolling feature, and its been amazing. A new use case requires me to disable past days -  you cannot scroll historically. Only today and future dates are scrollable - is there a way I can do this?

I have currently limited to 1 month scroll for historical dates...

thanks for any inputs in advance

**Comment by kizitonwose** [comment]
You can add a [touch listener](https://github.com/kizitonwose/CalendarView/issues/38#issuecomment-525786644) and disable scroll for past months.
