### ISSUE TITLE
Disabling days 

### ISSUE THREAD

**Issue by polatolu** [kizitonwose/CalendarView#36]
Hi,

Thanks for the great library.

I'm looking for a feature of settings specific days as disabled and not selectable on the `CalendarView`.  These disabled days should also stop range selection if they are inside this range.

Is this something possible for the library? I noticed the library is mostly focused on the UI customisation but just wanted to check with you.

Thanks.

**Comment by kizitonwose** [comment]
Yes, this is possible. You just have to ignore clicks on the "disabled" dates and setup up the UI to look "disabled" accordingly.

**Comment by polatolu** [comment]
Ok, thanks. What about the range selection? The days within the range does not receive clicks.

**Comment by kizitonwose** [comment]
I don't understand what you're trying to achieve regarding range selection. However, since the library does not provide any views, any logic is pretty much achievable.
