### ISSUE TITLE
The height of the calendarView does not change after scrolling month and switching the application to other fragments

### ISSUE THREAD

**Issue by andrey-ananiev** [kizitonwose/CalendarView#360]
In my application, the calendarView is installed in the tooolbar of the main activity. Fragments are switched using a custom navigator.
After scrolling the months, if I switch fragments, the height of the calendar stops changing even if I turn on the week mode.

![image](https://user-images.githubusercontent.com/95143899/151506432-96df15ce-6cea-434c-a917-d4019b25286f.png)

How can I fix this problem?

**Comment by kizitonwose** [comment]
An apk with which I can reproduce this issue would be very helpful.

**Comment by andrey-ananiev** [comment]
Thanks for the fast reply. You can download the app from this link:
[https://drive.google.com/file/d/1S7EgBlVkTwq8sAA_aGXhE3FKVviCVrwa/view?usp=sharing](url)

**Comment by andrey-ananiev** [comment]
The issue is closed. I found an error. I placed the calendarView in the container of the toolbar, and not under it. Thanks.
