### ISSUE TITLE
how to select today date by default

### ISSUE THREAD

**Issue by MoustafaElsaghier** [kizitonwose/CalendarView#361]
I'd like to select today's date by default to perform an action once open the screen, any idea how?

is that possible?

**Comment by kizitonwose** [comment]
Please see the README section on date selection.

**Comment by MoustafaElsaghier** [comment]
i followed but i couldn't find one for selecting today date once open the screen

**Comment by nafiskabbo** [comment]
In month scroll listener:

        binding.calendarView.monthScrollListener = {
            binding.tvMonth.text = DateTimeUtils.getFormattedString(DateTimeUtils.monthFormatPattern, it.yearMonth)
            binding.tvYear.text = DateTimeUtils.getFormattedString(DateTimeUtils.yearFormatPattern, it.yearMonth)
            if (it.month == today.monthValue) selectDate(today) else selectDate(it.yearMonth.atDay(1))
        }

**Comment by nafiskabbo** [comment]
> i followed but i couldn't find one for selecting today date once open the screen

Check my answer once1

**Comment by kizitonwose** [comment]
Basically, the calendar itself does not have the concept of `selection` built-in. If you want to run a logic initially, you just run the logic when the page starts and call "notifyDateChanged" so you can rebind the chosen date to make it look "selected"
