### ISSUE TITLE
Failed to resolve: com.github.kizitonwose:CalendarView

### ISSUE THREAD

**Issue by fullstact69** [kizitonwose/CalendarView#364]
![Screen Shot 2022-03-07 at 10 09 39 AM](https://user-images.githubusercontent.com/53449197/156955913-d6651e00-3b3e-4770-a0f6-31b0f7751cd1.png)

**Comment by dodiyaindrajit** [comment]
maven { url "https://jitpack.io" }
 
 allprojects {
 repositories {
    google()
    jcenter()
    maven { url "https://jitpack.io" }
 }
}
 
 pls, check to add into the project build.gradle file

**Comment by YekaterinaAbd** [comment]
> maven { url "https://jitpack.io" }
> 
> allprojects { repositories { google() jcenter() maven { url "https://jitpack.io" } } }
> 
> pls, check to add into the project build.gradle file

Have all this in the project, didn't help

**Comment by 22sonamu** [comment]
I have the same problem

**Comment by irbp** [comment]
I have the same problem in my project, and this line `maven { url "https://jitpack.io/" }` is added in my gradle repositories.

**Comment by YekaterinaAbd** [comment]
I managed to resolve the problem

I added 
`    repositories {
        google() 
        mavenCentral()
        jcenter() 
        maven { url "https://jitpack.io" }
    }` 

both in build.gradle (Project) and settings.gradle
it wasn't working until I added this in setting.gradle file

**Comment by kizitonwose** [comment]
I am unable to reproduce this issue. I have checked with various projects and it is working fine. Please ensure you follow the [setup](https://github.com/kizitonwose/CalendarView#setup) guide.

**Comment by citrusella** [comment]
Using the setup guide didn't work for me on Arctic Fox... but leaving the project level build.gradle unmodified and using the above settings.gradle (alongside the app-level build.gradle instructions in the setup guide) did get me past the resolution failure.
