### ISSUE TITLE
Disbale Multiple random days in single Month

### ISSUE THREAD

**Issue by khalil05400** [kizitonwose/CalendarView#371]
Is there an option to disable multiple random days in the same month?
if yes please let me know
currently I'm unable to disable multiple days at once, Only able to disable a single day at once in a single month
my scenario is I want to disable 1,15,25 28 date of month

**Comment by kizitonwose** [comment]
Please see the README on disabling dates https://github.com/kizitonwose/CalendarView#disabling-dates

All you have to do is to put the dates in an array and check the array before binding any date so you can make those dates look "disabled". You can then ignore clicks on those dates.
