### ISSUE TITLE
Fatal Exception: java.lang.UnsupportedOperationException Cannot calculate the values for day Width/Height with the current configuration.

### ISSUE THREAD

**Issue by JasonTheDynamite** [kizitonwose/CalendarView#372]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/18309065/168302613-72572eda-79f0-4122-ab1d-db88d4a93b55.png">

**Comment by JasonTheDynamite** [comment]
Occurs on tablets and foldable devices

**Comment by kizitonwose** [comment]
I have not experienced this myself. If you can share how to reproduce this, that would be helpful.

**Comment by JasonTheDynamite** [comment]
This fails on tablets / foldables:
  
  <RelativeLayout
        android:id="@+id/rlMain"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animateLayoutChanges="true"
        android:background="@color/toolbarBackgroundGrey"
        android:focusable="true"
        android:focusableInTouchMode="true"
        tools:ignore="RtlCompat">
  
  <androidx.coordinatorlayout.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            
             <androidx.core.widget.NestedScrollView
                android:id="@+id/ncvScroll"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:animateLayoutChanges="true">
                
                               <LinearLayout
                                            android:layout_width="match_parent"
                                            android:layout_height="wrap_content"
                                            android:orientation="horizontal"
                                            android:weightSum="100"
                                            android:layout_marginBottom="@dimen/dp10"
                                            android:layout_gravity="center"
                                            android:layout_marginLeft="@dimen/dp100"
                                            android:layout_marginRight="@dimen/dp100"
                                            android:clipToPadding="false"
                                            android:clipChildren="false">
                                            
                                              <com.kizitonwose.calendarview.CalendarView
                                                android:id="@+id/calendarView"
                                                android:layout_width="0dp"
                                                android:layout_height="wrap_content"
                                                android:layout_weight="30"
                                                android:layout_gravity="top|end"
                                                android:layout_marginRight="@dimen/dp10"
                                               />
                                               
                                               <View
                                                android:id="@+id/view"
                                                android:layout_width="0dp"
                                                android:layout_height="wrap_content"
                                                android:layout_weight="30"
                                                android:layout_gravity="top|end"
                                                android:layout_marginRight="@dimen/dp10"
                                               />
                                               
                                                 </LinearLayout>
                                               
                                                </androidx.core.widget.NestedScrollView>
                                                
                                                </androidx.coordinatorlayout.widget.CoordinatorLayout>
   </RelativeLayout>

Replacing linearLayout with ConstraintLayout works
