### ISSUE TITLE
Retrieve list of dates from calendar

### ISSUE THREAD

**Issue by chudofishe** [kizitonwose/CalendarView#374]
Hi, is there any way to get a list of all dates that are present in calendar after view is setup?

**Comment by kizitonwose** [comment]
`findFirstVisibleDay()` and `findLastVisibleDay()`

**Comment by chudofishe** [comment]
> `findFirstVisibleDay()` and `findLastVisibleDay()`

This can be used to retrieve dates from the currently visible month. I actually meant the case when we have multiple months

**Comment by kizitonwose** [comment]
No, it works for multiple `visible` months as well.

You can see in implementation [here](https://github.com/kizitonwose/CalendarView/blob/3d8f449ab9c4216648527167c1913a1c4c125195/library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt#L323).
