### ISSUE TITLE
RecyclerView.Adapter.StateRestorationPolicy.PREVENT_WHEN_EMPTY

### ISSUE THREAD

**Issue by akrulec** [kizitonwose/CalendarView#375]
Hi, is there a way to set that flag on the recycler view adapter for the week view of the calendar (example 7 in the demo app)? For example, today is June 14th, user scrolls to June 6th, navigates to a new page, and then presses back. When the user goes back to the page, the calendar starts with June 14th, instead of lingering on June 6th. I fixed this on a different adapter by setting adapter.stateRestorationPolicy to PREVENT_WHEN_EMPTY. Thank you,

**Comment by kizitonwose** [comment]
`calendarView.getAdapter().setStateRestorationStrategy(StateRestorationStrategy.PREVENT_WHEN_EMPTY)`

Just make sure to call this after `calendarView.setup()` has completed otherwise `getAdapter()` would be `null`
