### ISSUE TITLE
Scrolling through the week view and updating data

### ISSUE THREAD

**Issue by akrulec** [kizitonwose/CalendarView#376]
First, thank you for this powerful library. I'm using the week view, and I'm trying to figure out what is the best way to populate/refresh the data. I want the users to be able to scroll from and to infinity if they want, but I don't want to preload their life's worth of data, to show the correct decoration in the day view. What is the best way to detect that the user is scrolling week view? Is there a way to scroll in a paginated way, where it would just snap to the first day of the week (the user would only be able to scroll 7 days at a time, and then each time I detect a scroll I can fetch week worth of data)? Thank you

**Comment by kizitonwose** [comment]
For infinite scroll, you can listen for `monthScrollListener` and call `updateMonthRange` with new values when the calendar gets to the edge. To scroll 7 days at a time, you can use the `paged` scroll mode (this also enables snapping).

Note: You have to enable `inDates` for the first month (`inDateStyle = firstMonth`) if the day texts (M|T|W|T|F|S|S) are static at the top so the pagination aligns with the expected week days.
