### ISSUE TITLE
Is there a way to have only specific months

### ISSUE THREAD

**Issue by gosemathraj** [kizitonwose/CalendarView#378]
I want to display some events on calendar. My calendar is supposed to have months for which events are present. If there are no events for February month, then it should not be displayed. So my calendar months could be January, March, April, June, December. Is there any way to customise this lib to achieve this.

**Comment by kizitonwose** [comment]
This is unfortunately not possible with the current setup, but if you fork the project, you can tweak the adapter (or date generator) to skip those months. This is a very specific use case so may not be worth implementing into the project.
