### ISSUE TITLE
To plot calendar from current date 

### ISSUE THREAD

**Issue by sandeepbhatia4922** [kizitonwose/CalendarView#379]
Hi @kizitonwose  can we plot calendar from current date to specific date. In our case we need to show calendar from current date to next 45 days. But currently I didn't find any method to setup calendar based on dates. Also is there any way to change height of day cell?

**Comment by kizitonwose** [comment]
Hi, you can't start from a specific date. The alternative is to start with the month that contains the date and disable all past dates in that month. Regarding changing height, there are examples in the sample app that do this. You just adjust the height of the calendar itself and the cells will be divided evenly.

**Comment by sandeepbhatia4922** [comment]
@kizitonwose can we scroll to current week and show current date like in outlook app?
![Uploading Screenshot 2022-06-30 at 11.46.35 AM.png…]()

**Comment by kizitonwose** [comment]
Use `scrollToDate()` or `smoothScrollToDate()`

**Comment by sandeepbhatia4922** [comment]
thanks @kizitonwose  let me try it
