### ISSUE TITLE
Refresh daybinder or day events after the data successfully fetched. (WEEK MODE)

### ISSUE THREAD

**Issue by sherwin14** [kizitonwose/CalendarView#384]
from the example code. you setup the day events with a preloaded "Flights data". 

Then how could I refresh the events after successful fetch from the api?

**Comment by kizitonwose** [comment]
You can see example 3 where data is added dynamically. You can call `notifyDateChanged`, `notifyMonthChanged` or `notifyCalendarChanged` (The first one is the most efficient).
