### ISSUE TITLE
Change orientation asynchronously

### ISSUE THREAD

**Issue by TanyaYu** [kizitonwose/CalendarView#385]
I use horizontal orientation for weekly view and vertical for monthly view. I'd like to be able to switch between weekly and monthly view asynchronously. `calendarView.orientation = HORIZONTAL` works but it takes a couple sec to execute and freezes the main thread.

**Comment by kizitonwose** [comment]
This is a bug, changing the orientation should not recalculate the days. I will fix this in the coming version.

**Comment by kizitonwose** [comment]
This is now fixed.
