### ISSUE TITLE
Is it possible to disable drag?

### ISSUE THREAD

**Issue by nasuellia** [kizitonwose/CalendarView#389]
Hello kizitonwose and thank you for the awesome library!

My implementation has arrows / buttons to perform a week-by-week scroll of the calendar; letting the user move between weeks by dragging is actually an issue for me right now.

Is there a way to entirely disable scrolling the calendar by dragging?

Thanks a whole bunch in advance and have a great day!

**Comment by kizitonwose** [comment]
Yes, it's possible. See [this](https://github.com/kizitonwose/CalendarView/issues/38#issuecomment-525786644).

**Comment by nasuellia** [comment]
Thanks mate! Works like a charm!
