### ISSUE TITLE
Weird issues?

### ISSUE THREAD

**Issue by gajicm93** [kizitonwose/CalendarView#4]
Hi, I started by including your Example 5 into my project, but as part of another vertical RecyclerView. Anyways, the calendar shows up fine, but I have 2 weird issues:

1. Month scroll listener gets invoked with one month earlier than shown on the calendar (e.g. calendar shows June days, but it says May on top). I'm using paged calendar, and this is invoked when I page it with finger.

2. When I use buttons (next & previous) to move the calendar, it starts skipping months, but it's mostly skipping into past 1 or 2 months. So for e.g., If I go back from June to May, it ends up showing April.. But if I go forward from June to July, it ends up showing June again (because it skips one month back again).

Do you have any idea what this might be? Otherwise, library is great and very customizable. Thanks!

**Comment by kizitonwose** [comment]
Thank you for reporting this, it's now fixed in the [latest release](https://github.com/kizitonwose/CalendarView/releases/tag/0.1.1). This was happening because `findFirstVisibleItemPosition()` was misbehaving in the layout manager.

**Comment by gajicm93** [comment]
@kizitonwose wow you're amazing, I'll test it right away.
