### ISSUE TITLE
Centre date on calendar view

### ISSUE THREAD

**Issue by L3K0V** [kizitonwose/CalendarView#41]
Hi @kizitonwose, awesome library!

Do you know if I can easily centre a date into the calendar view. 
Using scrollTo date method the selected date is on top so this isn't working for my case.

Thanks

**Comment by kizitonwose** [comment]
> Do you know if I can easily centre a date into the calendar view.

This is currently not possible. However, you can scroll to a date in the past to make the target date look centered. While you cannot guarantee that the target date will be at the exact center of the view with this workaround, the target date will not be at the top either.
