### ISSUE TITLE
Performance issue with unbounded months on long date ranges

### ISSUE THREAD

**Issue by VarHastra** [kizitonwose/CalendarView#46]
Steps to reproduce the issue in the sample app:

1. Open `Example7Fragment.kt` and increase the date range between `startMonth` and `endMonth` in the `setup(..)` method to 10 years (for old and low-end devices even 3-5 years is enough).
2. Run the app and open Example 7.

Expected behavior: the app should become unresponsive for several seconds. The greater the date range, the longer the freeze. The lag is more noticeable on old and low end devices.

Here is an example of how it looks: https://drive.google.com/open?id=10ge9IzonM8EYDdw4Y4oDSc761WrC308l

It seems that the problem only takes place when `CalendarView.hasBoundaries` is set to false. So after some dumb tests with measuring execution time inside `MonthConfig.generateUnboundedMonths(..)` I've discovered that the freezes are caused by `removeAll()` calls on each iteration of [this loop at line 109](https://github.com/kizitonwose/CalendarView/blob/18a2afd402e6f56820795b8467f521bb63921477/library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt#L109-L113).

It looks like that the problem is that remove operations for this type of collection take O(n) time and `allDay` list may contain significant amount of items when the date range is long enough. 

[Here is a small fix](https://github.com/VarHastra/CalendarView/commit/2277f0f4f074aa33f8fd045dbc6790d180efcccb) that uses [`Iterable.chunked(..)`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/chunked.html) to split the `allDays` list and seems to solve the issue. 
I can make a pull request if you want to.

**Comment by kizitonwose** [comment]
Good catch! Please proceed with the pull request.

There are also other parts of the `MonthConfig` class that can benefit from this optimization. 

---

[**Line 64:**](https://github.com/kizitonwose/CalendarView/blob/18a2afd402e6f56820795b8467f521bb63921477/library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt#L64)

This:
```kotlin
while (weekDaysGroup.isNotEmpty()) {
    val monthDays = weekDaysGroup.take(maxRowCount)
    calendarMonths.add(CalendarMonth(currentMonth, monthDays, calendarMonths.size, numberOfSameMonth))
    weekDaysGroup.removeAll(monthDays)
}
```

can be replaced with:
```kotlin
calendarMonths.addAll(weekDaysGroup.chunked(maxRowCount).map { monthDays ->
    CalendarMonth(currentMonth, monthDays, calendarMonths.size, numberOfSameMonth)
})
```

---

[**Line 235:**](https://github.com/kizitonwose/CalendarView/blob/18a2afd402e6f56820795b8467f521bb63921477/library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt#235)

This:
```kotlin
while (thisMonthDays.isNotEmpty()) {
    val nextRow = thisMonthDays.take(7)
    groupBySeven.add(nextRow)
    thisMonthDays.removeAll(nextRow)
}
```

can be replaced with the exact implementation you've come up with for line 109.

---

With these changes, the three lists on which we call `removeAll()` no longer need to be mutable and should be updated as well.
