### ISSUE TITLE
Unable to properly click dates in Samsung S7 Edge 

### ISSUE THREAD

**Issue by eypibee** [kizitonwose/CalendarView#48]
Hi @kizitonwose . I was testing the calendar with S7 Edge but had a hard time clicking on each day.  There are certain day that needs to be clicked hard or lightly. Are there any issues raised like this with using Edge?

**Comment by kizitonwose** [comment]
> Are there any issues raised like this with using Edge?

No such issue has been reported.

**Comment by kizitonwose** [comment]
Closing this issue since we're not sure what's going on. Feel free to reopen when you have more information.

**Comment by eypibee** [comment]
Hi @kizitonwose . I was able to determine my mistake. What I want to do was block the left and right swiping of the calendar and focused only on navigation arrow. This was the code I used:

`calViewActivities.addOnItemTouchListener(object : RecyclerView.SimpleOnItemTouchListener() {
                override fun onInterceptTouchEvent(rv: RecyclerView, e: MotionEvent): Boolean {
                    return if (e.action == MotionEvent.ACTION_MOVE) {
                        true
                    } else {
                        super.onInterceptTouchEvent(rv, e)
                    }
                }
            })`

Sadly, it conflicts with the `View.OnClickListener` of days. How can I properly block the left and right swipe?

**Comment by kizitonwose** [comment]
@eypibee This is a bug with Samsung phones. Please see the workaround [here](https://github.com/kizitonwose/CalendarView/issues/38#issuecomment-525786644).

**Comment by eypibee** [comment]
> @eypibee This is a bug with Samsung phones. Please see the workaround [here](https://github.com/kizitonwose/CalendarView/issues/38#issuecomment-525786644).

It's working now. Thanks a lot!
