### ISSUE TITLE
Continuos selection mode single day?

### ISSUE THREAD

**Issue by robertoestivill** [kizitonwose/CalendarView#51]
Was trying the Example 3 of the demo app and realized that the continuos selection mode doesn't allow for the same day selection for start and end. If the same day is selected only the start date is set. If I click it again, nothing happens.

This does come handy in some use cases, like booking roundtrips transport tickets for the same day.

**Comment by kizitonwose** [comment]
Just for clarity, do you mean example 4? Example 3 does not have range selection.

**Comment by robertoestivill** [comment]
> Just for clarity, do you mean example 4? Example 3 does not have range selection.

Yes, it was a typo. Sorry about that.

**Comment by kizitonwose** [comment]
You just have to tweak the logic for your use case. 

In the click listener set in the `DayViewContainer`'s init block, you can change:

```kotlin
if (date < startDate || endDate != null) {
    startDate = date
    endDate = null
} else if (date != startDate) {
    endDate = date
}
```

to this:

```kotlin
if (date < startDate || endDate != null) {
    startDate = date
    endDate = null
} else {
    endDate = date
}
```

This gives you the desired behavior.
You then have to set the background drawable for the end date accordingly to match the behavior.
