### ISSUE TITLE
What is wrong with your calendar ?

### ISSUE THREAD

**Issue by nekadevmaster** [kizitonwose/CalendarView#53]
![2019-09-02 18 19 44](https://user-images.githubusercontent.com/17720956/64123867-2af1bd00-cdae-11e9-8419-9c84435f2497.jpg)
![2019-09-02 18 19 40](https://user-images.githubusercontent.com/17720956/64123869-2af1bd00-cdae-11e9-85ff-1999f82892a9.jpg)

Whay is not dispay 31

`val firstMonth = currentMonth.minusMonths(10)
        val lastMonth = currentMonth.plusMonths(10)
        val firstDayOfWeek = DayOfWeek.MONDAY
calendarView.setup(firstMonth, lastMonth, firstDayOfWeek)
calendarView.inDateStyle = InDateStyle.ALL_MONTHS
        calendarView.maxRowCount = 5
        calendarView.hasBoundaries = true`

**Comment by kizitonwose** [comment]
I don't understand this issue. Could you kindly explain further?

**Comment by nekadevmaster** [comment]
Look images, why it is not display 31 day ?

**Comment by kizitonwose** [comment]
There's 31 in the first picture so I still don't know what you mean. 
From your code though, maybe you want to use `calendarView.maxRowCount = 6` instead of `calendarView.maxRowCount = 5` and see if that fixes your problem,

**Comment by kizitonwose** [comment]
I'll be closing this now. Let me know if you need any further assistance.

**Comment by emanuellopes** [comment]
Hi have the same issue, using your first example. sometimes the view not stay with 6 rows. this it's related with animation of collapse.
