### ISSUE TITLE
Question- how do I add days of the week to the calendarview?

### ISSUE THREAD

**Issue by AtomicJoseph** [kizitonwose/CalendarView#54]
I can't see any functionality to add days of the week to the calendar view. Is this something I have to implement manually via the Month Header? Thanks.

**Comment by kizitonwose** [comment]
You are correct. You have to implement this via the month header if you want it to scroll with each month(see example 3) or you could just use a separate view placed above the calendar(see example 1).

**Comment by AtomicJoseph** [comment]
OK cheers, thanks for the information!
