### ISSUE TITLE
How to change day padding ?

### ISSUE THREAD

**Issue by nekadevmaster** [kizitonwose/CalendarView#56]
Hello i want to make padding from top android bottom less, how i can do it ?

**Comment by nekadevmaster** [comment]
![Screenshot_1567687096](https://user-images.githubusercontent.com/17720956/64348312-a4331f00-cffd-11e9-84dd-304a59e113b1.png)
white lines it is margings

**Comment by kizitonwose** [comment]
I unfortunately cannot see your attachment.
<img width="450" alt="Screenshot 2019-09-05 at 3 52 57 PM" src="https://user-images.githubusercontent.com/15170090/64353235-51556980-cff5-11e9-9282-ddd0e3d3fadd.png">

**Comment by kizitonwose** [comment]
> I unfortunately cannot see your attachment.

Seems like the attachment suddenly decided to show up.

It looks like you have bottom margins in your `dayViewResource`. There are no added margins in the library so I'm not sure what's going on.

**Comment by kizitonwose** [comment]
Note that you are using the default configuration which sets day width and height to calenderWidth/7. If you don't want this, you have to explicitly set your desired height or width using `calendarView.dayHeight` and `calendarView.dayWidth` respectively.

**Comment by nekadevmaster** [comment]
Thank you i have solved it, maked your lib local and than change one part of your code 
layoutParams = LinearLayout.LayoutParams(config.width, MasterTimeWorkWeekView.pxToDpConver(45, dateView.context), 1F)

**Comment by kizitonwose** [comment]
You can achieve the same result by setting the `dayHeight` property on the calendar instance.

**Comment by kizitonwose** [comment]
Closing this since the issue has been resolved.

**Comment by bitqube** [comment]
Tried your suggestion by setting the dayHeight property. 
exOneCalendar.dayHeight = resources.getDimensionPixelSize(R.dimen.calendar_day_height)
where calendar_day_height = 48dp

This is the result
![Screenshot_20190914-152702_CalendarView Sample](https://user-images.githubusercontent.com/2649008/64908758-5ce71580-d704-11e9-85a8-20b6ed8a8d55.jpg)

**Comment by lorduriel** [comment]
@ol3th 

You neet to set the width also.
```

 val display: Display = windowManager.defaultDisplay
 val size = Point()
 display.getSize(size)
 val width: Int = size.x
 val height: Int = size.y

 calendar.dayHeight = 100
 calendar.dayWidth = width / 7
```
