### ISSUE TITLE
Simple Calendar needs lots of code

### ISSUE THREAD

**Issue by kaushalyap** [kizitonwose/CalendarView#57]
I was using [material-calendar view](https://github.com/prolificinteractive/material-calendarview). Looked at your library to use simple calendar with max date, min date and marking of dates.
After looking at [sample app example 1](https://github.com/kizitonwose/CalendarView/blob/master/sample/src/main/java/com/kizitonwose/calendarviewsample/Example1Fragment.kt) its lots of code to do a simple thing.(lot of boilerplate).

May be it's better if you could provide simple method (in library API) to setup a calendar with simpler syntax.

**Comment by kizitonwose** [comment]
The reason why it looks like it takes a lot of work to set up the calendar is that the library does not do any UI work for you which is the only reason you're able to customize the calendar whichever way you desire. 
Any attempt to help you with some setup work will require customization tradeoffs. 

This library may not be for you if you just want to show a very simple calendar.
