### ISSUE TITLE
How to select dates on gesture(drag)

### ISSUE THREAD

**Issue by parkhepradip** [kizitonwose/CalendarView#61]
Hi 
I want to be  able to drag start date and end date. Is there any way to achieve this?

Thanks

**Comment by kizitonwose** [comment]
I have been putting this off as I hoped I'll eventually get the chance to maybe add support for it. But unfortunately, this will not be supported in the near future. I'll close this for now and reopen if I happen to start working on it.

**Comment by Ayusch** [comment]
Hey guys. I know it's been long. But is there any plans to support this drag-to-select ? Or can you let me know where to start in compose ? 

Or maybe do you know any other calendar libraries that support this ?

**Comment by carstenhag** [comment]
I was also looking for this, as often users want to select multiple dates like this.
