### ISSUE TITLE
Different languages support

### ISSUE THREAD

**Issue by Ice94** [kizitonwose/CalendarView#62]
Hello,
First of all thanks for such a useful library. Could you tell me how to provide months' names in other languages to the calendar view?

**Comment by kizitonwose** [comment]
You need to change the Locale in your formatter.

In [example 1](https://github.com/kizitonwose/CalendarView/blob/9372399dea7758ecc02129812d11efa05851daa9/sample/src/main/java/com/kizitonwose/calendarviewsample/Example1Fragment.kt#L42), we have:

```kotlin
private val monthTitleFormatter = DateTimeFormatter.ofPattern("MMMM")
```

To show the month title text in french, change this to:

```kotlin
private val monthTitleFormatter = DateTimeFormatter.ofPattern("MMMM").withLocale(Locale.FRENCH)
```

If no Locale is specified, the JVM's default Locale is used which may be what you want instead.
