### ISSUE TITLE
[Request] Strict date range 

### ISSUE THREAD

**Issue by cpeppas** [kizitonwose/CalendarView#64]
Is it possible to have a strict date range selection i.e.  from 8th October 2019 until 8th October 2020 (one year sharp) Meaning that the dates after 8th October 2020 are not selectable. The same goes with the dates before 8th October 2019

What is the best way to achieve the above  with the current setup. (I am looking at Example4 from the sample app.)

Do you think this could be a potential feature implemented by the library?

**Comment by kizitonwose** [comment]
The library can achieve this. In Example 4 which you mentioned, you can use the same logic which I used to make dates in the past non-selectable. In the `bind` method of the `dayBinder`, check if the date is less than 8th October 2019 or greater than 8th October 2020 and apply the same logic if true.

**Comment by cpeppas** [comment]
@kizitonwose Thanks for the advice
