### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [kizitonwose/CalendarView#65]
I've recently added the [Chucker library](https://github.com/ChuckerTeam/chucker) to my app and got this build error:

```
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'
```

It turns out that both CalendarView and Chucker are creating the same `META-INF/library_release.kotlin_module` file:

![Captura de Pantalla 2019-10-10 a les 12 58 32](https://user-images.githubusercontent.com/4823860/66566143-80b34500-eb64-11e9-9510-1049d36974ec.png)

I've opened an issue on Chucker with more details about the error and some solutions: https://github.com/ChuckerTeam/chucker/issues/134

While there is a way to fix this, it would be nice that to fix the issue on the library itself, which would avoid having every user apply the same fix :)

**Comment by kizitonwose** [comment]
I'm not sure what the actual fix for this is. I do have a lot on my plate at the moment so if you know the fix, kindly open a PR.

**Comment by AlbertVilaCalvo** [comment]
Thanks @kizitonwose 

On the other library that also has this problem they've opened a PR with a fix: https://github.com/ChuckerTeam/chucker/pull/146

Let's see if it does fix it and I might then open a PR here.

**Comment by samigehi** [comment]
I have excluded this file and worked perfect [Ref](https://stackoverflow.com/questions/44509608/duplicate-files-copied-in-apk-meta-inf-library-release-kotlin-module)

```
packagingOptions {
    exclude 'META-INF/library_release.kotlin_module'
}

```
