### ISSUE TITLE
How can  I customize CalendarView so that there is a view for the year?

### ISSUE THREAD

**Issue by BigBey** [kizitonwose/CalendarView#70]
How can I customize the calendar so that there is a view for the year as a grid view? You can see the example on the picture.
![Screenshot_20191020_132041](https://user-images.githubusercontent.com/24989051/67158115-8b2bc680-f33c-11e9-80d2-de87a8b30bd2.jpg)

**Comment by kizitonwose** [comment]
This is not currently possible. Will add it to the feature list. I think we may be able to achieve it using a Grid layout manager instead of the linear layout manager being used presently.

**Comment by kizitonwose** [comment]
Actually, on second thought, the adapter needs to be changed as well. Changing only the layout manager will result in months overflowing into other years. Will close this issue as it'll involve a major rewrite of the core logic.
