### ISSUE TITLE
Marking as today's date wrong dates

### ISSUE THREAD

**Issue by GalatiaPar** [kizitonwose/CalendarView#73]
I have implemented the Example4 from the samples of this project, where I set a custom rounded background to today's date. Although it should be marking only today's date with that background, I noticed that it marks more dates. My logic says:

if (day.date == today) -> {
// set that background
}

**where** today = LocalDate.now() and the day.date comes from the callback upon the binding. 

I have noticed that 3rd April and some other random dates get marked as today. In the dates callback I receive multiple dates with the today's date as their date. Could someone please help by resolving this issue?

**Comment by devharis** [comment]
I'm experiencing issues with dates as well, setting first day of the week to Monday doesnt seem to work.

**Comment by kizitonwose** [comment]
@GalatiaPar You need to clear the background in the else block. This looks like it's happening because the views are being reused.

```Kotlin
if (day.date == today) {
	// Set background
} else {
	// Remove background
}
```

**Comment by kizitonwose** [comment]
> I'm experiencing issues with dates as well, setting first day of the week to Monday doesnt seem to have any effect.

@devharis How do you mean it does not work? Could you explain further and better still, open a separate issue.

**Comment by devharis** [comment]
@kizitonwose Sorry for the hijacking, it seems to work perfectly. I was doing it wrong obviously :) Thanks!

**Comment by kizitonwose** [comment]
I have to assume this was indeed a recycling issue and is now resolved.
