### ISSUE TITLE
setMonthScrollListener in Java

### ISSUE THREAD

**Issue by rejsiperpalaj** [kizitonwose/CalendarView#74]
I want to call this listener in java class. How can i do that?

**Comment by rejsiperpalaj** [comment]
My problem got fixed when I configured Kotlin compiler and runtime for my Java module with the latest stable version (currently 1.3.50)

Just go to Tools > Kotlin > Configure Kotlin in Project > Android with Gradle and choose your Java module with Single module radio button selected then select your version and OK.

**Comment by hulisani-mudimeli** [comment]
Hi @rejsiperpalaj, I just configured kotlin in project, would you please send your code snippet where you use setMonthScrollListener?

**Comment by kizitonwose** [comment]
@hulisani-mudimeli It should look like this after you have configured Kotlin:

```java
calendarView.setMonthScrollListener(new Function1<CalendarMonth, Unit>() {
    @Override
    public Unit invoke(CalendarMonth calendarMonth) {
        // Use calendarMonth
        return Unit.INSTANCE;
    }
});
```

Or shorter:

```java
calendarView.setMonthScrollListener(calendarMonth -> {
    // Use calendarMonth
    return Unit.INSTANCE;
});
```
