### ISSUE TITLE
How to limit column count to one week?

### ISSUE THREAD

**Issue by chriswiesner** [kizitonwose/CalendarView#75]
I want to have a smaller (height) calendarview

Therefore I set a custom day height/width. but if I make it smaller, more than 7 days are shown in a row.
Can I limit it to just one week?

![image](https://user-images.githubusercontent.com/4553058/68241424-ed5c1b00-000e-11ea-96fd-569c1f2efdf4.png)

Also defining height and width is a bit confusing for me. It would be nice to just set the height, and the calendarview makes sure that width is set properly to show all 7 days.

**Comment by kizitonwose** [comment]
> I want to have a smaller (height) calendarview
> 
> Therefore I set a custom day height/width. but if I make it smaller, more than 7 days are shown in a row.
> Can I limit it to just one week?

You can set the desired height, then divide the screen width by 7 to get the appropriate width for 7 days and set that to the CalendarView.

**Comment by chriswiesner** [comment]
Thanks, yes that's working. Thought of having a feature of the calendarview but doing manually is ok as well.
