### ISSUE TITLE
.setMonthFooterBinder(), footer dissapearing

### ISSUE THREAD

**Issue by Dastroo** [kizitonwose/CalendarView#77]
my footers are dissapearing after i scroll to a point where there are no and then back.

Some events are appearing randomly accross the calendar.

calendat.notifyCalendarChanged() throws exeption when i put it anywhere in the binders or even view containers like it is in the samples

`
calendar.setMonthFooterBinder(new MonthHeaderFooterBinder<MonthFooterVC>() {

            @NonNull
            @Override
            public MonthFooterVC create(@NonNull View view) {
                return new MonthFooterVC(view);
            }

            @Override
            public void bind(@NonNull MonthFooterVC monthFooterVC, @NonNull CalendarMonth calendarMonth) {

                int year = calendarMonth.getYear();
                int month = calendarMonth.getMonth();

                Cursor cursor = getMonthCursor(year, month);

                ArrayList<String> events = getEventsFromCursor(cursor);

                FooterEventAdapter adapter = new FooterEventAdapter(events);

                monthFooterVC.setAdapter(adapter);
            }
        });
`

My footer is a RecyclerView:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/calendar_footer_rv_id"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:background="@color/design_default_color_primary"/>

</LinearLayout>`

this is my footer view container:

`
class MonthFooterVC extends ViewContainer {

    private RecyclerView rv;

    void setAdapter(FooterEventAdapter eventAdapter) {
        rv.setLayoutManager(new StaggeredGridLayoutManager(1,StaggeredGridLayoutManager.HORIZONTAL));
        rv.setAdapter(eventAdapter);
    }

    MonthFooterVC(View view) {
        super(view);

        rv = view.findViewById(R.id.calendar_footer_rv_id);

    }
}
`

**Comment by kizitonwose** [comment]
I'm not sure about how to proceed with this issue without a sample app. If you can provide a repo with some code that I can run to reproduce this issue, that'll be very helpful.

**Comment by Dastroo** [comment]
ok i am gonna try to do it this week

**Comment by kizitonwose** [comment]
Any updates?

**Comment by Dastroo** [comment]
it seems like the calendarDay.getOnwner is not working properly, something must be wrong with the owner because i made it so that only days in (DayOwner.THIS_MONTH == calendarDay.getOwner()) get onclicklistener but i still can click some of the gray days

**Comment by kizitonwose** [comment]
I'm no longer sure what this issue is about. Kindly open a new issue with the problem you currently have and I'll take a look.
