### ISSUE TITLE
Add Events Dynamically and Refreshed CalenderView?

### ISSUE THREAD

**Issue by nicemak** [kizitonwose/CalendarView#78]
Hi, Thanks for the great library.

As title clarifies that i need to add an event, when i select a date a pop up will appear (already done) and upon save i need to add and show that event on calendar view?

second i am getting events data from server so how can i refresh calendar view to show updated events?

I am using Example 5 for my project.

**Comment by kizitonwose** [comment]
Example 5 is the perfect guide which you seem to have followed. To refresh a date, just call `calendarView.notifyDateChanged()` and pass in the date you want to update. This causes the view for that date to be rebound, allowing you to update the view to show that it has an event.

**Comment by kizitonwose** [comment]
The CalendarView does not store your events, you just have to update the UI for dates with an event to display how you prefer in the provided `DayBinder`.

**Comment by nicemak** [comment]
Thanks
