### ISSUE TITLE
How to check if day.owner is from DayOwner.NEXT_MONTH?

### ISSUE THREAD

**Issue by nicemak** [kizitonwose/CalendarView#81]
Hi,

I have a condition to show user current month and next month only to add events, and in current month i don't allow user add event on past day like this:

`
if (day.day < currentDate)
     toast("You can not add events on past days.")
else
     toast("You can add events on this day")
`

the problem i am facing is that when i scroll to next month and click on date to add event it goes to if (day.owner == DayOwner.THIS_MONTH) and i have also added the condition if (day.owner == DayOwner.NEXT_MONTH) but it does not check this condition how can i fulfill this condition?

I hope my question is clear to you :)

**Comment by kizitonwose** [comment]
To be clear, do you want to be able to add events in the next month when you scroll?

**Comment by nicemak** [comment]
Thanks for reply, I managed this myself :)
