### ISSUE TITLE
Scrolling is choppy

### ISSUE THREAD

**Issue by dejiapps** [kizitonwose/CalendarView#88]
First of all excellent job on the library, best calendar view I have tried so far.

I am having issues with scrolling animation of the calendar being choppy: [Video](https://imgur.com/a/JvNK6YZ)

What do you think can be slowing it down, and what can I do to make it scroll smoothly?

first month is set as five years prior to current date, and last 

month is set for 25 years from current date.

here is my calendar_day_layout.xml:

`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    android:orientation="vertical"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/day_constraint"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View
        android:background="?android:attr/textColorPrimary"
        app:layout_constraintTop_toTopOf="parent"
        android:alpha=".1"
        android:layout_width="match_parent"
        android:layout_height=".5dp"/>

    <TextView
        android:id="@+id/calendarDayText"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingStart="8dp"
        android:textSize="16sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.0"
        tools:text="22" />

    <TextView
        android:id="@+id/kelly_indicator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@color/md_blue_500"
        android:text="K"
        android:textSize="16sp"
        android:visibility="gone"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

    <View
        android:id="@+id/shift1"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:layout_marginTop="2dp"
        android:background="@color/md_red_500"
        android:visibility="gone"
        app:layout_constraintTop_toBottomOf="@id/calendarDayText"
        app:layout_goneMarginTop="2dp" />

    <View
        android:id="@+id/shift2"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:layout_marginTop="2dp"
        android:background="@color/md_blue_500"
        android:visibility="gone"
        app:layout_constraintTop_toBottomOf="@id/shift1"
        app:layout_goneMarginTop="2dp" />

    <View
        android:id="@+id/shift3"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:layout_marginTop="2dp"
        android:background="@color/md_green_500"
        android:visibility="gone"
        app:layout_constraintTop_toBottomOf="@id/shift2"
        app:layout_goneMarginTop="2dp" />

    <com.google.android.flexbox.FlexboxLayout
        android:padding="4dp"
        android:layout_weight="1"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:alignContent="space_around"
        app:alignItems="center"
        app:flexDirection="row"
        app:flexWrap="wrap"
        app:justifyContent="center"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/shift3"
        app:layout_constraintBottom_toBottomOf="parent">

        <ImageView
            android:id="@+id/fire_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_red_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="8dp"
            app:srcCompat="@drawable/fire"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/medical_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_red_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/biohazard"
            tools:layout_editor_absoluteX="34dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/hazmart_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_green_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/radioactive"
            tools:layout_editor_absoluteX="69dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/otherexposure_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_blue_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/exposure_other"
            tools:layout_editor_absoluteX="103dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/trade_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/black_semi_transparent"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/ic_swap_horiz_black_24dp"
            tools:layout_editor_absoluteX="137dp"
            tools:layout_editor_absoluteY="336dp" />

        <ImageView
            android:id="@+id/training_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_brown_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/training"
            tools:layout_editor_absoluteX="171dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/sick_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_orange_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/sicktime"
            tools:layout_editor_absoluteX="206dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/vacation_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_deep_purple_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/vacation"
            tools:layout_editor_absoluteX="240dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/overtime_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_green_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/oticon"
            tools:layout_editor_absoluteX="274dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/comptime_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:tint="@color/md_green_500"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/comptime"
            tools:layout_editor_absoluteX="309dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/other_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/unknownicon"
            tools:layout_editor_absoluteX="343dp"
            tools:layout_editor_absoluteY="334dp" />

        <ImageView
            android:id="@+id/pay_icon"
            android:layout_width="16dp"
            android:layout_height="wrap_content"
            android:padding="1dp"
            android:visibility="gone"
            app:layout_flexGrow="1"
            app:layout_maxHeight="30dp"
            app:layout_minHeight="16dp"
            app:srcCompat="@drawable/money"
            tools:layout_editor_absoluteX="377dp"
            tools:layout_editor_absoluteY="336dp" />
    </com.google.android.flexbox.FlexboxLayout>
</androidx.constraintlayout.widget.ConstraintLayout>`

and here is what my calendarView is like:

`<com.kizitonwose.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            app:cv_dayViewResource="@layout/calendar_day_layout"
            app:cv_hasBoundaries="true"
            app:cv_monthHeaderResource="@layout/calendar_header"
            app:cv_orientation="vertical"
            app:cv_outDateStyle="endOfRow"
            app:cv_scrollMode="continuous" />`

Any suggestions for improvement will be appreciated.

**Comment by kizitonwose** [comment]
If the initial setup is smooth(this is where the major work is), I don't see why scrolling would be an issue. Maybe you're doing some big work in the Day binder which gets called pretty often(approx 30 times for each month)?

**Comment by dejiapps** [comment]
You are absolute correct, when I commented out the work in Day binder it became smooth again. Thank you @kizitonwose.
