### ISSUE TITLE
DayOwner.THIS_MONTH days been marked as inDates and outDates

### ISSUE THREAD

**Issue by dejiapps** [kizitonwose/CalendarView#97]
@kizitonwose 
Some dates that belong to the current month are being treated as inDates and outDates when they shouldn't be. Also after scrolling a few months and then scrolling back to the current month, the current month gets messed up to. Please see attached screenshots:

![this month](https://user-images.githubusercontent.com/21183832/70436574-9d320780-1a57-11ea-98cf-c7b851d0a9e4.png)

![Screenshot_20191209-063836](https://user-images.githubusercontent.com/21183832/70436197-ba1a0b00-1a56-11ea-83b8-fc3de45f2716.png)

![Screenshot_20191209-065402](https://user-images.githubusercontent.com/21183832/70436198-ba1a0b00-1a56-11ea-8ada-4e8d1652dc93.png)

![Screenshot_20191209-065414](https://user-images.githubusercontent.com/21183832/70436199-ba1a0b00-1a56-11ea-9f96-7fd0b7e6d75d.png)

![Screenshot_20191209-065421](https://user-images.githubusercontent.com/21183832/70436200-ba1a0b00-1a56-11ea-946e-30f82a0cd181.png)

**Comment by kizitonwose** [comment]
Did you update the library? Has it always been this way?

**Comment by dejiapps** [comment]
It was like this with V.0.2.9, I updated it this morning to v.0.3.0 and it is still like this.

**Comment by kizitonwose** [comment]
Can you replicate this issue using any of the sample projects?

**Comment by dejiapps** [comment]
I couldn't replicate it in the sample projects. I did find the solution though. 

I initially set the inDates and outDates as gone or with reduced opacity. I didn't think I had to the specify that the days in the current month have full opacity.  But when I did that, the issue resolved itself.
