### ISSUE TITLE
Calendar does not fit properly in tablet (>7") with landscape mode only.

### ISSUE THREAD

**Issue by bhaumik2712** [kizitonwose/CalendarView#99]
Hi,
Thanks for providing such helpful library. Really appreciate!!

My project is specific to tablet having 7 inch and above screen size and landscape mode only.

I just tried to render it on UI but it does not look properly and shows dates of next month.

Please check attached screenshot and help me to fix it. 

![Screenshot_1576132238](https://user-images.githubusercontent.com/11713742/70688514-fa3bf080-1cd7-11ea-82e1-9f63ea1cbcb5.png)

**Comment by kizitonwose** [comment]
Looks like this may have something to do with cell sizing. How are you setting the size on the calendar?

**Comment by bhaumik2712** [comment]
Hi @kizitonwose 
Thanks for your reply!
I was trying by setting fixed height and width. I just fixed it by applying dynamic height and width of cell hence closing this defect. 
Thanks!
